package sb

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"slices"
	"sync"
	"time"

)

// Code generated by sb generator. DO NOT EDIT.
var _ = slices.Equal[[]int, int]
var _ = HeaderSize

// --- API Handlers ---

func UserGetAbcHandler(w http.ResponseWriter, r *http.Request) {
	if !parseEmptyRequest(w, r) { return }
	result, status := user_get_abc(r.Context())
	status = normalizeHandlerStatus(r.Context(), status)
	if !checkStatus(w, status) { return }
	var body bytes.Buffer
	{
		if !isAssignableOrderStatus(result) { w.WriteHeader(http.StatusInternalServerError); return }
		if err := SetU8(&body, uint8(normalizeOrderStatus(result))); err != nil { w.WriteHeader(http.StatusInternalServerError); return }
	}
	sendResponse(w, body.Bytes())
}

func UserGetAbcdHandler(w http.ResponseWriter, r *http.Request) {
	var page uint8
	var size uint8

	buf, ok := parseRequest(w, r)
	if !ok { return }
	{
		value, err := GetU8(buf)
		if err != nil { w.WriteHeader(http.StatusBadRequest); return }
		page = value
	}
	{
		value, err := GetU8(buf)
		if err != nil { w.WriteHeader(http.StatusBadRequest); return }
		size = value
	}
	if buf.Len() != 0 { w.WriteHeader(http.StatusBadRequest); return }

	result, status := user_get_abcd(r.Context(), page, size)
	status = normalizeHandlerStatus(r.Context(), status)
	if !checkStatus(w, status) { return }
	var body bytes.Buffer
	{
		if !isAssignableOrderStatus(result) { w.WriteHeader(http.StatusInternalServerError); return }
		if err := SetU8(&body, uint8(normalizeOrderStatus(result))); err != nil { w.WriteHeader(http.StatusInternalServerError); return }
	}
	sendResponse(w, body.Bytes())
}

func UserSetSimInfoHandler(w http.ResponseWriter, r *http.Request) {
	var info *SimInfo

	buf, ok := parseRequest(w, r)
	if !ok { return }
	{
		value, err := ReadSimInfo(buf)
		if err != nil { w.WriteHeader(http.StatusBadRequest); return }
		info = value
	}
	if buf.Len() != 0 { w.WriteHeader(http.StatusBadRequest); return }

	status := user_set_sim_info(r.Context(), info)
	status = normalizeHandlerStatus(r.Context(), status)
	if !checkStatus(w, status) { return }
	w.WriteHeader(http.StatusOK)
}

func GetCountHandler(w http.ResponseWriter, r *http.Request) {
	var page uint8

	buf, ok := parseRequest(w, r)
	if !ok { return }
	{
		value, err := GetU8(buf)
		if err != nil { w.WriteHeader(http.StatusBadRequest); return }
		page = value
	}
	if buf.Len() != 0 { w.WriteHeader(http.StatusBadRequest); return }

	result, status := get_count(r.Context(), page)
	status = normalizeHandlerStatus(r.Context(), status)
	if !checkStatus(w, status) { return }
	var body bytes.Buffer
	{
		if err := SetU8(&body, result); err != nil { w.WriteHeader(http.StatusInternalServerError); return }
	}
	sendResponse(w, body.Bytes())
}

func GetBinHandler(w http.ResponseWriter, r *http.Request) {
	var page uint8

	buf, ok := parseRequest(w, r)
	if !ok { return }
	{
		value, err := GetU8(buf)
		if err != nil { w.WriteHeader(http.StatusBadRequest); return }
		page = value
	}
	if buf.Len() != 0 { w.WriteHeader(http.StatusBadRequest); return }

	result, status := get_bin(r.Context(), page)
	status = normalizeHandlerStatus(r.Context(), status)
	if !checkStatus(w, status) { return }
	var body bytes.Buffer
	{
		state, err := BinState(len(result))
		if err != nil { w.WriteHeader(http.StatusInternalServerError); return }
		if err := SetU8(&body, state); err != nil { w.WriteHeader(http.StatusInternalServerError); return }
		if err := SetBin(&body, state, result); err != nil { w.WriteHeader(http.StatusInternalServerError); return }
	}
	sendResponse(w, body.Bytes())
}

// --- 路由注册 ---

type Middleware func(http.HandlerFunc) http.HandlerFunc

func composeMiddleware(mws ...Middleware) func(http.HandlerFunc) http.HandlerFunc {
	return func(h http.HandlerFunc) http.HandlerFunc {
		for i := len(mws) - 1; i >= 0; i-- { h = mws[i](h) }
		return h
	}
}

func TimeoutMiddleware(timeout time.Duration) Middleware {
	return func(h http.HandlerFunc) http.HandlerFunc {
		if timeout <= 0 { return h }
		return func(w http.ResponseWriter, r *http.Request) {
			ctx, cancel := context.WithTimeout(r.Context(), timeout)
			defer cancel()
			tw := newTimeoutResponseWriter()
			done := make(chan struct{})
			go func() {
				defer close(done)
				h(tw, r.WithContext(ctx))
			}()
			select {
			case <-done:
				if ctx.Err() == context.DeadlineExceeded {
					tw.timeout()
					w.WriteHeader(http.StatusRequestTimeout)
					return
				}
				tw.writeTo(w)
			case <-ctx.Done():
				tw.timeout()
				if ctx.Err() == context.DeadlineExceeded {
					w.WriteHeader(http.StatusRequestTimeout)
				}
			}
		}
	}
}

type timeoutResponseWriter struct {
	mu sync.Mutex
	header http.Header
	code int
	wroteHeader bool
	body bytes.Buffer
	timedOut bool
}

func newTimeoutResponseWriter() *timeoutResponseWriter {
	return &timeoutResponseWriter{header: make(http.Header)}
}

func (tw *timeoutResponseWriter) Header() http.Header { return tw.header }

func (tw *timeoutResponseWriter) WriteHeader(statusCode int) {
	tw.mu.Lock()
	defer tw.mu.Unlock()
	if tw.timedOut || tw.wroteHeader { return }
	tw.code = statusCode
	tw.wroteHeader = true
}

func (tw *timeoutResponseWriter) Write(data []byte) (int, error) {
	tw.mu.Lock()
	defer tw.mu.Unlock()
	if tw.timedOut { return 0, http.ErrHandlerTimeout }
	if !tw.wroteHeader {
		tw.code = http.StatusOK
		tw.wroteHeader = true
	}
	return tw.body.Write(data)
}

func (tw *timeoutResponseWriter) timeout() {
	tw.mu.Lock()
	tw.timedOut = true
	tw.mu.Unlock()
}

func (tw *timeoutResponseWriter) writeTo(w http.ResponseWriter) {
	tw.mu.Lock()
	if tw.timedOut {
		tw.mu.Unlock()
		return
	}
	header := tw.header.Clone()
	code := tw.code
	wroteHeader := tw.wroteHeader
	body := append([]byte(nil), tw.body.Bytes()...)
	tw.mu.Unlock()
	for k, values := range header {
		for _, value := range values {
			w.Header().Add(k, value)
		}
	}
	if !wroteHeader { code = http.StatusOK }
	w.WriteHeader(code)
	if len(body) == 0 { return }
	_, _ = w.Write(body)
}

func RegisterApi(mux *http.ServeMux, mws ...Middleware) {
	mw := composeMiddleware(mws...)
	mux.HandleFunc("POST /get_count", mw(GetCountHandler))
	mux.HandleFunc("POST /get_bin", mw(GetBinHandler))
}

func RegisterUserApi(mux *http.ServeMux, mws ...Middleware) {
	mw := composeMiddleware(mws...)
	mux.HandleFunc("POST /user.get_abc", mw(UserGetAbcHandler))
	mux.HandleFunc("POST /user.get_abcd", mw(UserGetAbcdHandler))
	mux.HandleFunc("POST /user.set_sim_info", mw(UserSetSimInfoHandler))
}

// --- 内部辅助函数 ---

const defaultMaxReqBytes int64 = 4 * 1024 * 1024

func normalizeHandlerStatus(ctx context.Context, status RpcErrCode) RpcErrCode {
	if status != RpcOk || ctx == nil { return status }
	if ctx.Err() == context.DeadlineExceeded { return RpcTimeout }
	return status
}

func httpStatusFromRPC(status RpcErrCode) int {
	switch status {
	case RpcOk:
		return http.StatusOK
	case RpcReqErr:
		return http.StatusBadRequest
	case RpcNotAuth:
		return http.StatusUnauthorized
	case RpcNotExist:
		return http.StatusNotFound
	case RpcTimeout:
		return http.StatusRequestTimeout
	default:
		return http.StatusInternalServerError
	}
}

func checkStatus(w http.ResponseWriter, status RpcErrCode) bool {
	if status == RpcOk { return true }
	w.WriteHeader(httpStatusFromRPC(status)); return false
}

func parseEmptyRequest(w http.ResponseWriter, r *http.Request) bool {
	body, err := io.ReadAll(io.LimitReader(r.Body, 1)); if err != nil { w.WriteHeader(http.StatusBadRequest); return false }
	if len(body) != 0 { w.WriteHeader(http.StatusBadRequest); return false }
	return true
}

func parseRequest(w http.ResponseWriter, r *http.Request) (*bytes.Buffer, bool) {
	readLimit := defaultMaxReqBytes + 1
	body, err := io.ReadAll(io.LimitReader(r.Body, readLimit)); if err != nil { w.WriteHeader(http.StatusBadRequest); return nil, false }
	if int64(len(body)) > defaultMaxReqBytes { w.WriteHeader(http.StatusRequestEntityTooLarge); return nil, false }
	return bytes.NewBuffer(body), true
}

func sendResponse(w http.ResponseWriter, body []byte) {
	if w.Header().Get("Content-Type") == "" {
		w.Header().Set("Content-Type", "application/octet-stream")
	}
	if _, err := w.Write(body); err != nil { w.WriteHeader(http.StatusInternalServerError); return }
}
