package sbv2

import (
	"bytes"
	"fmt"
	"math"
	"slices"

	rt "sb/go/sb/v2"
)

// Code generated by sb v2 generator. DO NOT EDIT.
var _ = slices.Equal[[]int, int]
var _ = rt.HeaderSize

func eqBin(a, b []byte) bool { return bytes.Equal(a, b) }
func eqBinList(a, b [][]byte) bool { return slices.EqualFunc(a, b, bytes.Equal) }
func eqF32(a, b float32) bool { return math.Abs(float64(a-b)) < 1e-6 }
func eqF64(a, b float64) bool { return math.Abs(a-b) < 1e-9 }

// AccountStatus 账户状态
type AccountStatus uint8

const (
	AccountStatusOffline AccountStatus = 0
	AccountStatusOnline AccountStatus = 1
	AccountStatusDeleted AccountStatus = 2
)

func defaultAccountStatus() AccountStatus { return AccountStatusOffline }
func isAccountStatus(v AccountStatus) bool {
	switch v {
	case AccountStatusOffline, AccountStatusOnline, AccountStatusDeleted:
		return true
	default:
		return false
	}
}

func normalizeAccountStatus(v AccountStatus) AccountStatus {
	if isAccountStatus(v) { return v }
	if v == 0 {
		return defaultAccountStatus()
	}
	return v
}

func isDefaultAccountStatus(v AccountStatus) bool { return normalizeAccountStatus(v) == defaultAccountStatus() }
func isAssignableAccountStatus(v AccountStatus) bool { return isAccountStatus(v) || (v == 0 && !isAccountStatus(0)) }
func eqAccountStatusValue(a, b AccountStatus) bool { return normalizeAccountStatus(a) == normalizeAccountStatus(b) }
func eqAccountStatusList(a, b []AccountStatus) bool { return slices.EqualFunc(a, b, eqAccountStatusValue) }

func sizeAccountStatusListItem(item AccountStatus) (int, error) {
	if !isAssignableAccountStatus(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return 1, nil
}

func getAccountStatusListItem(buf *bytes.Buffer) (AccountStatus, error) {
	value, err := rt.GetU8(buf)
	if err != nil { return 0, err }
	item := AccountStatus(value)
	if !isAccountStatus(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return item, nil
}

func setAccountStatusListItem(buf *bytes.Buffer, item AccountStatus) error {
	if !isAccountStatus(item) { return fmt.Errorf("非法枚举值: %d", item) }
	return rt.SetU8(buf, uint8(item))
}

func getAccountStatusListBody(buf *bytes.Buffer, state uint8) ([]AccountStatus, error) {
	return getAccountStatusListBodyReuse(buf, state, nil)
}

func getAccountStatusListBodyReuse(buf *bytes.Buffer, state uint8, dst []AccountStatus) ([]AccountStatus, error) {
	return rt.GetBitmapListCompactInto(
		buf,
		state,
		dst,
		defaultAccountStatus,
		getAccountStatusListItem,
	)
}

func setAccountStatusListBody(buf *bytes.Buffer, state uint8, v []AccountStatus) error {
	return rt.SetBitmapListCompactSized(
		buf,
		state,
		v,
		isDefaultAccountStatus,
		sizeAccountStatusListItem,
		setAccountStatusListItem,
	)
}

func sizeAccountStatusListBody(v []AccountStatus) (int, error) {
	return rt.SizeBitmapListCompact(
		v,
		isDefaultAccountStatus,
		sizeAccountStatusListItem,
	)
}

// Type 类型
type Type uint8

const (
	TypeSim Type = 0
	TypeRecharge Type = 1
)

func defaultType() Type { return TypeSim }
func isType(v Type) bool {
	switch v {
	case TypeSim, TypeRecharge:
		return true
	default:
		return false
	}
}

func normalizeType(v Type) Type {
	if isType(v) { return v }
	if v == 0 {
		return defaultType()
	}
	return v
}

func isDefaultType(v Type) bool { return normalizeType(v) == defaultType() }
func isAssignableType(v Type) bool { return isType(v) || (v == 0 && !isType(0)) }
func eqTypeValue(a, b Type) bool { return normalizeType(a) == normalizeType(b) }
func eqTypeList(a, b []Type) bool { return slices.EqualFunc(a, b, eqTypeValue) }

func sizeTypeListItem(item Type) (int, error) {
	if !isAssignableType(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return 1, nil
}

func getTypeListItem(buf *bytes.Buffer) (Type, error) {
	value, err := rt.GetU8(buf)
	if err != nil { return 0, err }
	item := Type(value)
	if !isType(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return item, nil
}

func setTypeListItem(buf *bytes.Buffer, item Type) error {
	if !isType(item) { return fmt.Errorf("非法枚举值: %d", item) }
	return rt.SetU8(buf, uint8(item))
}

func getTypeListBody(buf *bytes.Buffer, state uint8) ([]Type, error) {
	return getTypeListBodyReuse(buf, state, nil)
}

func getTypeListBodyReuse(buf *bytes.Buffer, state uint8, dst []Type) ([]Type, error) {
	return rt.GetBitmapListCompactInto(
		buf,
		state,
		dst,
		defaultType,
		getTypeListItem,
	)
}

func setTypeListBody(buf *bytes.Buffer, state uint8, v []Type) error {
	return rt.SetBitmapListCompactSized(
		buf,
		state,
		v,
		isDefaultType,
		sizeTypeListItem,
		setTypeListItem,
	)
}

func sizeTypeListBody(v []Type) (int, error) {
	return rt.SizeBitmapListCompact(
		v,
		isDefaultType,
		sizeTypeListItem,
	)
}

// Status 错误码
type Status uint8

const (
	StatusOk Status = 0
	StatusErr Status = 1
	StatusTwo Status = 2
	StatusThree Status = 3
	StatusFour Status = 4
	StatusFive Status = 5
	StatusSix Status = 6
	StatusSeven Status = 7
	StatusOne Status = 11
)

func defaultStatus() Status { return StatusOk }
func isStatus(v Status) bool {
	switch v {
	case StatusOk, StatusErr, StatusTwo, StatusThree, StatusFour, StatusFive, StatusSix, StatusSeven, StatusOne:
		return true
	default:
		return false
	}
}

func normalizeStatus(v Status) Status {
	if isStatus(v) { return v }
	if v == 0 {
		return defaultStatus()
	}
	return v
}

func isDefaultStatus(v Status) bool { return normalizeStatus(v) == defaultStatus() }
func isAssignableStatus(v Status) bool { return isStatus(v) || (v == 0 && !isStatus(0)) }
func eqStatusValue(a, b Status) bool { return normalizeStatus(a) == normalizeStatus(b) }
func eqStatusList(a, b []Status) bool { return slices.EqualFunc(a, b, eqStatusValue) }

func sizeStatusListItem(item Status) (int, error) {
	if !isAssignableStatus(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return 1, nil
}

func getStatusListItem(buf *bytes.Buffer) (Status, error) {
	value, err := rt.GetU8(buf)
	if err != nil { return 0, err }
	item := Status(value)
	if !isStatus(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return item, nil
}

func setStatusListItem(buf *bytes.Buffer, item Status) error {
	if !isStatus(item) { return fmt.Errorf("非法枚举值: %d", item) }
	return rt.SetU8(buf, uint8(item))
}

func getStatusListBody(buf *bytes.Buffer, state uint8) ([]Status, error) {
	return getStatusListBodyReuse(buf, state, nil)
}

func getStatusListBodyReuse(buf *bytes.Buffer, state uint8, dst []Status) ([]Status, error) {
	return rt.GetBitmapListCompactInto(
		buf,
		state,
		dst,
		defaultStatus,
		getStatusListItem,
	)
}

func setStatusListBody(buf *bytes.Buffer, state uint8, v []Status) error {
	return rt.SetBitmapListCompactSized(
		buf,
		state,
		v,
		isDefaultStatus,
		sizeStatusListItem,
		setStatusListItem,
	)
}

func sizeStatusListBody(v []Status) (int, error) {
	return rt.SizeBitmapListCompact(
		v,
		isDefaultStatus,
		sizeStatusListItem,
	)
}

// StatusA 状态A
type StatusA uint8

const (
	StatusAOk StatusA = 0
	StatusAOne StatusA = 1
	StatusATwo StatusA = 2
	StatusAThree StatusA = 3
	StatusAFour StatusA = 4
	StatusAFive StatusA = 5
	StatusASix StatusA = 6
	StatusASeven StatusA = 7
)

func defaultStatusA() StatusA { return StatusAOk }
func isStatusA(v StatusA) bool {
	switch v {
	case StatusAOk, StatusAOne, StatusATwo, StatusAThree, StatusAFour, StatusAFive, StatusASix, StatusASeven:
		return true
	default:
		return false
	}
}

func normalizeStatusA(v StatusA) StatusA {
	if isStatusA(v) { return v }
	if v == 0 {
		return defaultStatusA()
	}
	return v
}

func isDefaultStatusA(v StatusA) bool { return normalizeStatusA(v) == defaultStatusA() }
func isAssignableStatusA(v StatusA) bool { return isStatusA(v) || (v == 0 && !isStatusA(0)) }
func eqStatusAValue(a, b StatusA) bool { return normalizeStatusA(a) == normalizeStatusA(b) }
func eqStatusAList(a, b []StatusA) bool { return slices.EqualFunc(a, b, eqStatusAValue) }

func sizeStatusAListItem(item StatusA) (int, error) {
	if !isAssignableStatusA(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return 1, nil
}

func getStatusAListItem(buf *bytes.Buffer) (StatusA, error) {
	value, err := rt.GetU8(buf)
	if err != nil { return 0, err }
	item := StatusA(value)
	if !isStatusA(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return item, nil
}

func setStatusAListItem(buf *bytes.Buffer, item StatusA) error {
	if !isStatusA(item) { return fmt.Errorf("非法枚举值: %d", item) }
	return rt.SetU8(buf, uint8(item))
}

func getStatusAListBody(buf *bytes.Buffer, state uint8) ([]StatusA, error) {
	return getStatusAListBodyReuse(buf, state, nil)
}

func getStatusAListBodyReuse(buf *bytes.Buffer, state uint8, dst []StatusA) ([]StatusA, error) {
	return rt.GetBitmapListCompactInto(
		buf,
		state,
		dst,
		defaultStatusA,
		getStatusAListItem,
	)
}

func setStatusAListBody(buf *bytes.Buffer, state uint8, v []StatusA) error {
	return rt.SetBitmapListCompactSized(
		buf,
		state,
		v,
		isDefaultStatusA,
		sizeStatusAListItem,
		setStatusAListItem,
	)
}

func sizeStatusAListBody(v []StatusA) (int, error) {
	return rt.SizeBitmapListCompact(
		v,
		isDefaultStatusA,
		sizeStatusAListItem,
	)
}

// ItemStatus 订单状态
type ItemStatus uint8

const (
	ItemStatusOffline ItemStatus = 0
	ItemStatusOnline ItemStatus = 1
)

func defaultItemStatus() ItemStatus { return ItemStatusOffline }
func isItemStatus(v ItemStatus) bool {
	switch v {
	case ItemStatusOffline, ItemStatusOnline:
		return true
	default:
		return false
	}
}

func normalizeItemStatus(v ItemStatus) ItemStatus {
	if isItemStatus(v) { return v }
	if v == 0 {
		return defaultItemStatus()
	}
	return v
}

func isDefaultItemStatus(v ItemStatus) bool { return normalizeItemStatus(v) == defaultItemStatus() }
func isAssignableItemStatus(v ItemStatus) bool { return isItemStatus(v) || (v == 0 && !isItemStatus(0)) }
func eqItemStatusValue(a, b ItemStatus) bool { return normalizeItemStatus(a) == normalizeItemStatus(b) }
func eqItemStatusList(a, b []ItemStatus) bool { return slices.EqualFunc(a, b, eqItemStatusValue) }

func sizeItemStatusListItem(item ItemStatus) (int, error) {
	if !isAssignableItemStatus(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return 1, nil
}

func getItemStatusListItem(buf *bytes.Buffer) (ItemStatus, error) {
	value, err := rt.GetU8(buf)
	if err != nil { return 0, err }
	item := ItemStatus(value)
	if !isItemStatus(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return item, nil
}

func setItemStatusListItem(buf *bytes.Buffer, item ItemStatus) error {
	if !isItemStatus(item) { return fmt.Errorf("非法枚举值: %d", item) }
	return rt.SetU8(buf, uint8(item))
}

func getItemStatusListBody(buf *bytes.Buffer, state uint8) ([]ItemStatus, error) {
	return getItemStatusListBodyReuse(buf, state, nil)
}

func getItemStatusListBodyReuse(buf *bytes.Buffer, state uint8, dst []ItemStatus) ([]ItemStatus, error) {
	return rt.GetBitmapListCompactInto(
		buf,
		state,
		dst,
		defaultItemStatus,
		getItemStatusListItem,
	)
}

func setItemStatusListBody(buf *bytes.Buffer, state uint8, v []ItemStatus) error {
	return rt.SetBitmapListCompactSized(
		buf,
		state,
		v,
		isDefaultItemStatus,
		sizeItemStatusListItem,
		setItemStatusListItem,
	)
}

func sizeItemStatusListBody(v []ItemStatus) (int, error) {
	return rt.SizeBitmapListCompact(
		v,
		isDefaultItemStatus,
		sizeItemStatusListItem,
	)
}

// SimPickPhone 可否选号
type SimPickPhone uint8

const (
	SimPickPhoneNo SimPickPhone = 0
	SimPickPhoneYes SimPickPhone = 1
	SimPickPhoneActive SimPickPhone = 3
	SimPickPhoneAbcc SimPickPhone = 4
)

func defaultSimPickPhone() SimPickPhone { return SimPickPhoneNo }
func isSimPickPhone(v SimPickPhone) bool {
	switch v {
	case SimPickPhoneNo, SimPickPhoneYes, SimPickPhoneActive, SimPickPhoneAbcc:
		return true
	default:
		return false
	}
}

func normalizeSimPickPhone(v SimPickPhone) SimPickPhone {
	if isSimPickPhone(v) { return v }
	if v == 0 {
		return defaultSimPickPhone()
	}
	return v
}

func isDefaultSimPickPhone(v SimPickPhone) bool { return normalizeSimPickPhone(v) == defaultSimPickPhone() }
func isAssignableSimPickPhone(v SimPickPhone) bool { return isSimPickPhone(v) || (v == 0 && !isSimPickPhone(0)) }
func eqSimPickPhoneValue(a, b SimPickPhone) bool { return normalizeSimPickPhone(a) == normalizeSimPickPhone(b) }
func eqSimPickPhoneList(a, b []SimPickPhone) bool { return slices.EqualFunc(a, b, eqSimPickPhoneValue) }

func sizeSimPickPhoneListItem(item SimPickPhone) (int, error) {
	if !isAssignableSimPickPhone(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return 1, nil
}

func getSimPickPhoneListItem(buf *bytes.Buffer) (SimPickPhone, error) {
	value, err := rt.GetU8(buf)
	if err != nil { return 0, err }
	item := SimPickPhone(value)
	if !isSimPickPhone(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return item, nil
}

func setSimPickPhoneListItem(buf *bytes.Buffer, item SimPickPhone) error {
	if !isSimPickPhone(item) { return fmt.Errorf("非法枚举值: %d", item) }
	return rt.SetU8(buf, uint8(item))
}

func getSimPickPhoneListBody(buf *bytes.Buffer, state uint8) ([]SimPickPhone, error) {
	return getSimPickPhoneListBodyReuse(buf, state, nil)
}

func getSimPickPhoneListBodyReuse(buf *bytes.Buffer, state uint8, dst []SimPickPhone) ([]SimPickPhone, error) {
	return rt.GetBitmapListCompactInto(
		buf,
		state,
		dst,
		defaultSimPickPhone,
		getSimPickPhoneListItem,
	)
}

func setSimPickPhoneListBody(buf *bytes.Buffer, state uint8, v []SimPickPhone) error {
	return rt.SetBitmapListCompactSized(
		buf,
		state,
		v,
		isDefaultSimPickPhone,
		sizeSimPickPhoneListItem,
		setSimPickPhoneListItem,
	)
}

func sizeSimPickPhoneListBody(v []SimPickPhone) (int, error) {
	return rt.SizeBitmapListCompact(
		v,
		isDefaultSimPickPhone,
		sizeSimPickPhoneListItem,
	)
}

// SimOperator 运营商
type SimOperator uint8

const (
	SimOperatorZz SimOperator = 2
	SimOperatorLt SimOperator = 3
	SimOperatorYd SimOperator = 4
	SimOperatorDx SimOperator = 5
	SimOperatorGd SimOperator = 6
	SimOperatorXx SimOperator = 7
	SimOperatorA SimOperator = 11
	SimOperatorB SimOperator = 12
)

func defaultSimOperator() SimOperator { return SimOperatorZz }
func isSimOperator(v SimOperator) bool {
	switch v {
	case SimOperatorZz, SimOperatorLt, SimOperatorYd, SimOperatorDx, SimOperatorGd, SimOperatorXx, SimOperatorA, SimOperatorB:
		return true
	default:
		return false
	}
}

func normalizeSimOperator(v SimOperator) SimOperator {
	if isSimOperator(v) { return v }
	if v == 0 {
		return defaultSimOperator()
	}
	return v
}

func isDefaultSimOperator(v SimOperator) bool { return normalizeSimOperator(v) == defaultSimOperator() }
func isAssignableSimOperator(v SimOperator) bool { return isSimOperator(v) || (v == 0 && !isSimOperator(0)) }
func eqSimOperatorValue(a, b SimOperator) bool { return normalizeSimOperator(a) == normalizeSimOperator(b) }
func eqSimOperatorList(a, b []SimOperator) bool { return slices.EqualFunc(a, b, eqSimOperatorValue) }

func sizeSimOperatorListItem(item SimOperator) (int, error) {
	if !isAssignableSimOperator(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return 1, nil
}

func getSimOperatorListItem(buf *bytes.Buffer) (SimOperator, error) {
	value, err := rt.GetU8(buf)
	if err != nil { return 0, err }
	item := SimOperator(value)
	if !isSimOperator(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return item, nil
}

func setSimOperatorListItem(buf *bytes.Buffer, item SimOperator) error {
	if !isSimOperator(item) { return fmt.Errorf("非法枚举值: %d", item) }
	return rt.SetU8(buf, uint8(item))
}

func getSimOperatorListBody(buf *bytes.Buffer, state uint8) ([]SimOperator, error) {
	return getSimOperatorListBodyReuse(buf, state, nil)
}

func getSimOperatorListBodyReuse(buf *bytes.Buffer, state uint8, dst []SimOperator) ([]SimOperator, error) {
	return rt.GetBitmapListCompactInto(
		buf,
		state,
		dst,
		defaultSimOperator,
		getSimOperatorListItem,
	)
}

func setSimOperatorListBody(buf *bytes.Buffer, state uint8, v []SimOperator) error {
	return rt.SetBitmapListCompactSized(
		buf,
		state,
		v,
		isDefaultSimOperator,
		sizeSimOperatorListItem,
		setSimOperatorListItem,
	)
}

func sizeSimOperatorListBody(v []SimOperator) (int, error) {
	return rt.SizeBitmapListCompact(
		v,
		isDefaultSimOperator,
		sizeSimOperatorListItem,
	)
}

// OrderStatus 订单状态
// Pending      待处理
// Closed       已关闭
// Canceled     已取消
// Shipped      已发货
// Delivered    已送达
// Actived      已激活
// Settled      已结算
type OrderStatus uint8

const (
	OrderStatusPending OrderStatus = 0
	OrderStatusClosed OrderStatus = 1
	OrderStatusCanceled OrderStatus = 2
	OrderStatusShipped OrderStatus = 3
	OrderStatusDelivered OrderStatus = 4
	OrderStatusActived OrderStatus = 5
	OrderStatusSettled OrderStatus = 6
)

func defaultOrderStatus() OrderStatus { return OrderStatusPending }
func isOrderStatus(v OrderStatus) bool {
	switch v {
	case OrderStatusPending, OrderStatusClosed, OrderStatusCanceled, OrderStatusShipped, OrderStatusDelivered, OrderStatusActived, OrderStatusSettled:
		return true
	default:
		return false
	}
}

func normalizeOrderStatus(v OrderStatus) OrderStatus {
	if isOrderStatus(v) { return v }
	if v == 0 {
		return defaultOrderStatus()
	}
	return v
}

func isDefaultOrderStatus(v OrderStatus) bool { return normalizeOrderStatus(v) == defaultOrderStatus() }
func isAssignableOrderStatus(v OrderStatus) bool { return isOrderStatus(v) || (v == 0 && !isOrderStatus(0)) }
func eqOrderStatusValue(a, b OrderStatus) bool { return normalizeOrderStatus(a) == normalizeOrderStatus(b) }
func eqOrderStatusList(a, b []OrderStatus) bool { return slices.EqualFunc(a, b, eqOrderStatusValue) }

func sizeOrderStatusListItem(item OrderStatus) (int, error) {
	if !isAssignableOrderStatus(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return 1, nil
}

func getOrderStatusListItem(buf *bytes.Buffer) (OrderStatus, error) {
	value, err := rt.GetU8(buf)
	if err != nil { return 0, err }
	item := OrderStatus(value)
	if !isOrderStatus(item) { return 0, fmt.Errorf("非法枚举值: %d", item) }
	return item, nil
}

func setOrderStatusListItem(buf *bytes.Buffer, item OrderStatus) error {
	if !isOrderStatus(item) { return fmt.Errorf("非法枚举值: %d", item) }
	return rt.SetU8(buf, uint8(item))
}

func getOrderStatusListBody(buf *bytes.Buffer, state uint8) ([]OrderStatus, error) {
	return getOrderStatusListBodyReuse(buf, state, nil)
}

func getOrderStatusListBodyReuse(buf *bytes.Buffer, state uint8, dst []OrderStatus) ([]OrderStatus, error) {
	return rt.GetBitmapListCompactInto(
		buf,
		state,
		dst,
		defaultOrderStatus,
		getOrderStatusListItem,
	)
}

func setOrderStatusListBody(buf *bytes.Buffer, state uint8, v []OrderStatus) error {
	return rt.SetBitmapListCompactSized(
		buf,
		state,
		v,
		isDefaultOrderStatus,
		sizeOrderStatusListItem,
		setOrderStatusListItem,
	)
}

func sizeOrderStatusListBody(v []OrderStatus) (int, error) {
	return rt.SizeBitmapListCompact(
		v,
		isDefaultOrderStatus,
		sizeOrderStatusListItem,
	)
}

type Recharge struct {
	// abcd
	Id uint32 `bson:"_id" json:"_id"`
	Type []OrderStatus `bson:"type" json:"type"`
	Phone []string `bson:"phone" json:"phone"`
	Si *SimInfo `bson:"si" json:"si"`
}

func resetRecharge(s *Recharge) {
	if s == nil { return }
	*s = Recharge{}
}

func defaultRecharge() *Recharge {
	s := &Recharge{}
	resetRecharge(s)
	return s
}

func isZeroRecharge(s *Recharge) bool {
	if s == nil { return true }
	if s.Id != 0 { return false }
	if len(s.Type) != 0 { return false }
	if len(s.Phone) != 0 { return false }
	if !isZeroSimInfo(s.Si) { return false }
	return true
}

func validateRecharge(s *Recharge) error {
	if s == nil { return nil }
	for i, item := range s.Type {
		if !isAssignableOrderStatus(item) { return fmt.Errorf("Type[%d] 非法枚举值: %d", i, item) }
	}
	for i, item := range s.Phone {
		if _, err := rt.TextState(len(item)); err != nil { return fmt.Errorf("Phone[%d]: %w", i, err) }
	}
	if err := validateSimInfo(s.Si); err != nil { return fmt.Errorf("Si: %w", err) }
	return nil
}

func sizeRechargeValidated(s *Recharge) (int, error) {
	if s == nil { return 0, fmt.Errorf("SizeRecharge: nil value") }
	size := rt.HeaderSize(6)
	if s.Id != 0 { size += 4 }
	fieldSizeType, err := sizeOrderStatusListBody(s.Type)
	if err != nil { return 0, fmt.Errorf("SizeRecharge Type: %w", err) }
	size += fieldSizeType
	fieldSizePhone, err := rt.SizeTextListCompact(s.Phone)
	if err != nil { return 0, fmt.Errorf("SizeRecharge Phone: %w", err) }
	size += fieldSizePhone
	if !isZeroSimInfo(s.Si) {
		fieldSizeSi, err := SizeSimInfo(s.Si)
		if err != nil { return 0, fmt.Errorf("SizeRecharge Si: %w", err) }
		size += fieldSizeSi
	}
	return size, nil
}

func SizeRecharge(s *Recharge) (int, error) {
	if err := validateRecharge(s); err != nil { return 0, fmt.Errorf("ValidateRecharge: %w", err) }
	return sizeRechargeValidated(s)
}

func GetRecharge(buf *bytes.Buffer, s *Recharge) error {
	if s == nil { return fmt.Errorf("GetRecharge: nil value") }
	reuseType := s.Type
	reusePhone := s.Phone
	reuseSi := s.Si
	resetRecharge(s)
	const headerBits = 6
	headerSize := rt.HeaderSize(headerBits)
	if buf.Len() < headerSize { return fmt.Errorf("GetRecharge header: %d - %d", buf.Len(), headerSize) }
	header := buf.Next(headerSize)
	if err := rt.ValidatePaddingZero(header, headerBits, "Recharge header"); err != nil { return err }
	r := rt.NewBitReader(header, headerBits)
	idPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetRecharge Id header: %w", err) }
	typeState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetRecharge Type header: %w", err) }
	phoneState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetRecharge Phone header: %w", err) }
	siPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetRecharge Si header: %w", err) }
	if idPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetRecharge Id: %w", err) }
		s.Id = value
	}
	valueType, err := getOrderStatusListBodyReuse(buf, typeState, reuseType)
	if err != nil { return fmt.Errorf("GetRecharge Type: %w", err) }
	s.Type = valueType
	valuePhone, err := rt.GetTextListCompactInto(buf, phoneState, reusePhone)
	if err != nil { return fmt.Errorf("GetRecharge Phone: %w", err) }
	s.Phone = valuePhone
	if siPresent {
		valueSi := reuseSi
		if valueSi == nil { valueSi = defaultSimInfo() }
		if err := GetSimInfo(buf, valueSi); err != nil { return fmt.Errorf("GetRecharge Si: %w", err) }
		s.Si = valueSi
	}
	return nil
}

func setRechargeValidated(buf *bytes.Buffer, s *Recharge) error {
	if s == nil { return fmt.Errorf("SetRecharge: nil value") }
	typeState, err := rt.ListCountState(len(s.Type)); if err != nil { return err }
	phoneState, err := rt.ListCountState(len(s.Phone)); if err != nil { return err }
	size, err := sizeRechargeValidated(s)
	if err != nil { return err }
	var headerData [1]byte
	if s.Id != 0 { headerData[0] |= 1 << 7 }
	headerData[0] |= typeState << 5
	headerData[0] |= phoneState << 3
	if !isZeroSimInfo(s.Si) { headerData[0] |= 1 << 2 }
	buf.Grow(size)
	if _, err := buf.Write(headerData[:]); err != nil { return fmt.Errorf("SetRecharge write header: %w", err) }
	if s.Id != 0 {
		if err := rt.SetU32(buf, s.Id); err != nil { return fmt.Errorf("SetRecharge Id: %w", err) }
	}
	if err := setOrderStatusListBody(buf, typeState, s.Type); err != nil { return fmt.Errorf("SetRecharge Type: %w", err) }
	if err := rt.SetTextListCompact(buf, phoneState, s.Phone); err != nil { return fmt.Errorf("SetRecharge Phone: %w", err) }
	if !isZeroSimInfo(s.Si) {
		if err := SetSimInfo(buf, s.Si); err != nil { return fmt.Errorf("SetRecharge Si: %w", err) }
	}
	return nil
}

func SetRecharge(buf *bytes.Buffer, s *Recharge) error {
	if s == nil { return fmt.Errorf("SetRecharge: nil value") }
	if err := validateRecharge(s); err != nil { return fmt.Errorf("ValidateRecharge: %w", err) }
	return setRechargeValidated(buf, s)
}

func ReadRecharge(buf *bytes.Buffer) (*Recharge, error) {
	s := defaultRecharge()
	return s, GetRecharge(buf, s)
}

func EqRecharge(a, b *Recharge) bool {
	if isZeroRecharge(a) && isZeroRecharge(b) { return true }
	if a == nil || b == nil { return false }
	if !(a.Id == b.Id) { return false }
	if !(eqOrderStatusList(a.Type, b.Type)) { return false }
	if !(slices.Equal(a.Phone, b.Phone)) { return false }
	if !(EqSimInfo(a.Si, b.Si)) { return false }
	return true
}

func getRechargeListBody(buf *bytes.Buffer, state uint8) ([]*Recharge, error) {
	return getRechargeListBodyReuse(buf, state, nil)
}

func getRechargeListBodyReuse(buf *bytes.Buffer, state uint8, dst []*Recharge) ([]*Recharge, error) {
	return rt.GetBitmapPtrListCompactInto(buf, state, dst, defaultRecharge, GetRecharge)
}

func setRechargeListBody(buf *bytes.Buffer, state uint8, v []*Recharge) error {
	return rt.SetBitmapPtrListCompactValidated(
		buf,
		state,
		v,
		"Recharge",
		validateRecharge,
		isZeroRecharge,
		SizeRecharge,
		setRechargeValidated,
	)
}

func sizeRechargeListBody(v []*Recharge) (int, error) {
	return rt.SizeBitmapPtrListCompactValidated(
		v,
		"Recharge",
		validateRecharge,
		isZeroRecharge,
		SizeRecharge,
	)
}

type RechargeA struct {
	// abcd
	Id uint32 `bson:"_id" json:"_id"`
	Type []OrderStatus `bson:"type" json:"type"`
	Phone []string `bson:"phone" json:"phone"`
	Si *SimInfo `bson:"si" json:"si"`
	Aid uint32 `bson:"aid" json:"aid"`
}

func resetRechargeA(s *RechargeA) {
	if s == nil { return }
	*s = RechargeA{}
}

func defaultRechargeA() *RechargeA {
	s := &RechargeA{}
	resetRechargeA(s)
	return s
}

func isZeroRechargeA(s *RechargeA) bool {
	if s == nil { return true }
	if s.Id != 0 { return false }
	if len(s.Type) != 0 { return false }
	if len(s.Phone) != 0 { return false }
	if !isZeroSimInfo(s.Si) { return false }
	if s.Aid != 0 { return false }
	return true
}

func validateRechargeA(s *RechargeA) error {
	if s == nil { return nil }
	for i, item := range s.Type {
		if !isAssignableOrderStatus(item) { return fmt.Errorf("Type[%d] 非法枚举值: %d", i, item) }
	}
	for i, item := range s.Phone {
		if _, err := rt.TextState(len(item)); err != nil { return fmt.Errorf("Phone[%d]: %w", i, err) }
	}
	if err := validateSimInfo(s.Si); err != nil { return fmt.Errorf("Si: %w", err) }
	return nil
}

func sizeRechargeAValidated(s *RechargeA) (int, error) {
	if s == nil { return 0, fmt.Errorf("SizeRechargeA: nil value") }
	size := rt.HeaderSize(7)
	if s.Id != 0 { size += 4 }
	fieldSizeType, err := sizeOrderStatusListBody(s.Type)
	if err != nil { return 0, fmt.Errorf("SizeRechargeA Type: %w", err) }
	size += fieldSizeType
	fieldSizePhone, err := rt.SizeTextListCompact(s.Phone)
	if err != nil { return 0, fmt.Errorf("SizeRechargeA Phone: %w", err) }
	size += fieldSizePhone
	if !isZeroSimInfo(s.Si) {
		fieldSizeSi, err := SizeSimInfo(s.Si)
		if err != nil { return 0, fmt.Errorf("SizeRechargeA Si: %w", err) }
		size += fieldSizeSi
	}
	if s.Aid != 0 { size += 4 }
	return size, nil
}

func SizeRechargeA(s *RechargeA) (int, error) {
	if err := validateRechargeA(s); err != nil { return 0, fmt.Errorf("ValidateRechargeA: %w", err) }
	return sizeRechargeAValidated(s)
}

func GetRechargeA(buf *bytes.Buffer, s *RechargeA) error {
	if s == nil { return fmt.Errorf("GetRechargeA: nil value") }
	reuseType := s.Type
	reusePhone := s.Phone
	reuseSi := s.Si
	resetRechargeA(s)
	const headerBits = 7
	headerSize := rt.HeaderSize(headerBits)
	if buf.Len() < headerSize { return fmt.Errorf("GetRechargeA header: %d - %d", buf.Len(), headerSize) }
	header := buf.Next(headerSize)
	if err := rt.ValidatePaddingZero(header, headerBits, "RechargeA header"); err != nil { return err }
	r := rt.NewBitReader(header, headerBits)
	idPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetRechargeA Id header: %w", err) }
	typeState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetRechargeA Type header: %w", err) }
	phoneState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetRechargeA Phone header: %w", err) }
	siPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetRechargeA Si header: %w", err) }
	aidPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetRechargeA Aid header: %w", err) }
	if idPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetRechargeA Id: %w", err) }
		s.Id = value
	}
	valueType, err := getOrderStatusListBodyReuse(buf, typeState, reuseType)
	if err != nil { return fmt.Errorf("GetRechargeA Type: %w", err) }
	s.Type = valueType
	valuePhone, err := rt.GetTextListCompactInto(buf, phoneState, reusePhone)
	if err != nil { return fmt.Errorf("GetRechargeA Phone: %w", err) }
	s.Phone = valuePhone
	if siPresent {
		valueSi := reuseSi
		if valueSi == nil { valueSi = defaultSimInfo() }
		if err := GetSimInfo(buf, valueSi); err != nil { return fmt.Errorf("GetRechargeA Si: %w", err) }
		s.Si = valueSi
	}
	if aidPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetRechargeA Aid: %w", err) }
		s.Aid = value
	}
	return nil
}

func setRechargeAValidated(buf *bytes.Buffer, s *RechargeA) error {
	if s == nil { return fmt.Errorf("SetRechargeA: nil value") }
	typeState, err := rt.ListCountState(len(s.Type)); if err != nil { return err }
	phoneState, err := rt.ListCountState(len(s.Phone)); if err != nil { return err }
	size, err := sizeRechargeAValidated(s)
	if err != nil { return err }
	var headerData [1]byte
	if s.Id != 0 { headerData[0] |= 1 << 7 }
	headerData[0] |= typeState << 5
	headerData[0] |= phoneState << 3
	if !isZeroSimInfo(s.Si) { headerData[0] |= 1 << 2 }
	if s.Aid != 0 { headerData[0] |= 1 << 1 }
	buf.Grow(size)
	if _, err := buf.Write(headerData[:]); err != nil { return fmt.Errorf("SetRechargeA write header: %w", err) }
	if s.Id != 0 {
		if err := rt.SetU32(buf, s.Id); err != nil { return fmt.Errorf("SetRechargeA Id: %w", err) }
	}
	if err := setOrderStatusListBody(buf, typeState, s.Type); err != nil { return fmt.Errorf("SetRechargeA Type: %w", err) }
	if err := rt.SetTextListCompact(buf, phoneState, s.Phone); err != nil { return fmt.Errorf("SetRechargeA Phone: %w", err) }
	if !isZeroSimInfo(s.Si) {
		if err := SetSimInfo(buf, s.Si); err != nil { return fmt.Errorf("SetRechargeA Si: %w", err) }
	}
	if s.Aid != 0 {
		if err := rt.SetU32(buf, s.Aid); err != nil { return fmt.Errorf("SetRechargeA Aid: %w", err) }
	}
	return nil
}

func SetRechargeA(buf *bytes.Buffer, s *RechargeA) error {
	if s == nil { return fmt.Errorf("SetRechargeA: nil value") }
	if err := validateRechargeA(s); err != nil { return fmt.Errorf("ValidateRechargeA: %w", err) }
	return setRechargeAValidated(buf, s)
}

func ReadRechargeA(buf *bytes.Buffer) (*RechargeA, error) {
	s := defaultRechargeA()
	return s, GetRechargeA(buf, s)
}

func EqRechargeA(a, b *RechargeA) bool {
	if isZeroRechargeA(a) && isZeroRechargeA(b) { return true }
	if a == nil || b == nil { return false }
	if !(a.Id == b.Id) { return false }
	if !(eqOrderStatusList(a.Type, b.Type)) { return false }
	if !(slices.Equal(a.Phone, b.Phone)) { return false }
	if !(EqSimInfo(a.Si, b.Si)) { return false }
	if !(a.Aid == b.Aid) { return false }
	return true
}

func getRechargeAListBody(buf *bytes.Buffer, state uint8) ([]*RechargeA, error) {
	return getRechargeAListBodyReuse(buf, state, nil)
}

func getRechargeAListBodyReuse(buf *bytes.Buffer, state uint8, dst []*RechargeA) ([]*RechargeA, error) {
	return rt.GetBitmapPtrListCompactInto(buf, state, dst, defaultRechargeA, GetRechargeA)
}

func setRechargeAListBody(buf *bytes.Buffer, state uint8, v []*RechargeA) error {
	return rt.SetBitmapPtrListCompactValidated(
		buf,
		state,
		v,
		"RechargeA",
		validateRechargeA,
		isZeroRechargeA,
		SizeRechargeA,
		setRechargeAValidated,
	)
}

func sizeRechargeAListBody(v []*RechargeA) (int, error) {
	return rt.SizeBitmapPtrListCompactValidated(
		v,
		"RechargeA",
		validateRechargeA,
		isZeroRechargeA,
		SizeRechargeA,
	)
}

type RechargeB struct {
	// abcd
	Id uint32 `bson:"_id" json:"_id"`
	Type []OrderStatus `bson:"type" json:"type"`
	Phone []string `bson:"phone" json:"phone"`
	Si *SimInfo `bson:"si" json:"si"`
	Bid uint32 `bson:"bid" json:"bid"`
}

func resetRechargeB(s *RechargeB) {
	if s == nil { return }
	*s = RechargeB{}
}

func defaultRechargeB() *RechargeB {
	s := &RechargeB{}
	resetRechargeB(s)
	return s
}

func isZeroRechargeB(s *RechargeB) bool {
	if s == nil { return true }
	if s.Id != 0 { return false }
	if len(s.Type) != 0 { return false }
	if len(s.Phone) != 0 { return false }
	if !isZeroSimInfo(s.Si) { return false }
	if s.Bid != 0 { return false }
	return true
}

func validateRechargeB(s *RechargeB) error {
	if s == nil { return nil }
	for i, item := range s.Type {
		if !isAssignableOrderStatus(item) { return fmt.Errorf("Type[%d] 非法枚举值: %d", i, item) }
	}
	for i, item := range s.Phone {
		if _, err := rt.TextState(len(item)); err != nil { return fmt.Errorf("Phone[%d]: %w", i, err) }
	}
	if err := validateSimInfo(s.Si); err != nil { return fmt.Errorf("Si: %w", err) }
	return nil
}

func sizeRechargeBValidated(s *RechargeB) (int, error) {
	if s == nil { return 0, fmt.Errorf("SizeRechargeB: nil value") }
	size := rt.HeaderSize(7)
	if s.Id != 0 { size += 4 }
	fieldSizeType, err := sizeOrderStatusListBody(s.Type)
	if err != nil { return 0, fmt.Errorf("SizeRechargeB Type: %w", err) }
	size += fieldSizeType
	fieldSizePhone, err := rt.SizeTextListCompact(s.Phone)
	if err != nil { return 0, fmt.Errorf("SizeRechargeB Phone: %w", err) }
	size += fieldSizePhone
	if !isZeroSimInfo(s.Si) {
		fieldSizeSi, err := SizeSimInfo(s.Si)
		if err != nil { return 0, fmt.Errorf("SizeRechargeB Si: %w", err) }
		size += fieldSizeSi
	}
	if s.Bid != 0 { size += 4 }
	return size, nil
}

func SizeRechargeB(s *RechargeB) (int, error) {
	if err := validateRechargeB(s); err != nil { return 0, fmt.Errorf("ValidateRechargeB: %w", err) }
	return sizeRechargeBValidated(s)
}

func GetRechargeB(buf *bytes.Buffer, s *RechargeB) error {
	if s == nil { return fmt.Errorf("GetRechargeB: nil value") }
	reuseType := s.Type
	reusePhone := s.Phone
	reuseSi := s.Si
	resetRechargeB(s)
	const headerBits = 7
	headerSize := rt.HeaderSize(headerBits)
	if buf.Len() < headerSize { return fmt.Errorf("GetRechargeB header: %d - %d", buf.Len(), headerSize) }
	header := buf.Next(headerSize)
	if err := rt.ValidatePaddingZero(header, headerBits, "RechargeB header"); err != nil { return err }
	r := rt.NewBitReader(header, headerBits)
	idPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetRechargeB Id header: %w", err) }
	typeState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetRechargeB Type header: %w", err) }
	phoneState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetRechargeB Phone header: %w", err) }
	siPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetRechargeB Si header: %w", err) }
	bidPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetRechargeB Bid header: %w", err) }
	if idPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetRechargeB Id: %w", err) }
		s.Id = value
	}
	valueType, err := getOrderStatusListBodyReuse(buf, typeState, reuseType)
	if err != nil { return fmt.Errorf("GetRechargeB Type: %w", err) }
	s.Type = valueType
	valuePhone, err := rt.GetTextListCompactInto(buf, phoneState, reusePhone)
	if err != nil { return fmt.Errorf("GetRechargeB Phone: %w", err) }
	s.Phone = valuePhone
	if siPresent {
		valueSi := reuseSi
		if valueSi == nil { valueSi = defaultSimInfo() }
		if err := GetSimInfo(buf, valueSi); err != nil { return fmt.Errorf("GetRechargeB Si: %w", err) }
		s.Si = valueSi
	}
	if bidPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetRechargeB Bid: %w", err) }
		s.Bid = value
	}
	return nil
}

func setRechargeBValidated(buf *bytes.Buffer, s *RechargeB) error {
	if s == nil { return fmt.Errorf("SetRechargeB: nil value") }
	typeState, err := rt.ListCountState(len(s.Type)); if err != nil { return err }
	phoneState, err := rt.ListCountState(len(s.Phone)); if err != nil { return err }
	size, err := sizeRechargeBValidated(s)
	if err != nil { return err }
	var headerData [1]byte
	if s.Id != 0 { headerData[0] |= 1 << 7 }
	headerData[0] |= typeState << 5
	headerData[0] |= phoneState << 3
	if !isZeroSimInfo(s.Si) { headerData[0] |= 1 << 2 }
	if s.Bid != 0 { headerData[0] |= 1 << 1 }
	buf.Grow(size)
	if _, err := buf.Write(headerData[:]); err != nil { return fmt.Errorf("SetRechargeB write header: %w", err) }
	if s.Id != 0 {
		if err := rt.SetU32(buf, s.Id); err != nil { return fmt.Errorf("SetRechargeB Id: %w", err) }
	}
	if err := setOrderStatusListBody(buf, typeState, s.Type); err != nil { return fmt.Errorf("SetRechargeB Type: %w", err) }
	if err := rt.SetTextListCompact(buf, phoneState, s.Phone); err != nil { return fmt.Errorf("SetRechargeB Phone: %w", err) }
	if !isZeroSimInfo(s.Si) {
		if err := SetSimInfo(buf, s.Si); err != nil { return fmt.Errorf("SetRechargeB Si: %w", err) }
	}
	if s.Bid != 0 {
		if err := rt.SetU32(buf, s.Bid); err != nil { return fmt.Errorf("SetRechargeB Bid: %w", err) }
	}
	return nil
}

func SetRechargeB(buf *bytes.Buffer, s *RechargeB) error {
	if s == nil { return fmt.Errorf("SetRechargeB: nil value") }
	if err := validateRechargeB(s); err != nil { return fmt.Errorf("ValidateRechargeB: %w", err) }
	return setRechargeBValidated(buf, s)
}

func ReadRechargeB(buf *bytes.Buffer) (*RechargeB, error) {
	s := defaultRechargeB()
	return s, GetRechargeB(buf, s)
}

func EqRechargeB(a, b *RechargeB) bool {
	if isZeroRechargeB(a) && isZeroRechargeB(b) { return true }
	if a == nil || b == nil { return false }
	if !(a.Id == b.Id) { return false }
	if !(eqOrderStatusList(a.Type, b.Type)) { return false }
	if !(slices.Equal(a.Phone, b.Phone)) { return false }
	if !(EqSimInfo(a.Si, b.Si)) { return false }
	if !(a.Bid == b.Bid) { return false }
	return true
}

func getRechargeBListBody(buf *bytes.Buffer, state uint8) ([]*RechargeB, error) {
	return getRechargeBListBodyReuse(buf, state, nil)
}

func getRechargeBListBodyReuse(buf *bytes.Buffer, state uint8, dst []*RechargeB) ([]*RechargeB, error) {
	return rt.GetBitmapPtrListCompactInto(buf, state, dst, defaultRechargeB, GetRechargeB)
}

func setRechargeBListBody(buf *bytes.Buffer, state uint8, v []*RechargeB) error {
	return rt.SetBitmapPtrListCompactValidated(
		buf,
		state,
		v,
		"RechargeB",
		validateRechargeB,
		isZeroRechargeB,
		SizeRechargeB,
		setRechargeBValidated,
	)
}

func sizeRechargeBListBody(v []*RechargeB) (int, error) {
	return rt.SizeBitmapPtrListCompactValidated(
		v,
		"RechargeB",
		validateRechargeB,
		isZeroRechargeB,
		SizeRechargeB,
	)
}

type Sim struct {
	// SIM卡ID
	Id uint32 `bson:"_id" json:"_id"`
	Type Type `bson:"type" json:"type"`
	Status ItemStatus `bson:"status" json:"status"`
	// 佣金
	Commission uint16 `bson:"commission" json:"commission"`
	// 供应商ID
	Supplier uint32 `bson:"supplier" json:"supplier"`
	// 推广员ID
	Aff uint32 `bson:"aff" json:"aff"`
	// 合约期(月), 0:长期
	ContractDuration uint8 `bson:"contract_duration" json:"contract_duration"`
	Name string `bson:"name" json:"name"`
	// 运营商
	Operator SimOperator `bson:"operator" json:"operator"`
	// 月租
	Monthly uint16 `bson:"monthly" json:"monthly"`
	// 通用流量
	FlowUniversal uint16 `bson:"flow_universal" json:"flow_universal"`
	// 定向流量
	FlowDirectional uint16 `bson:"flow_directional" json:"flow_directional"`
	// 流量是否结转
	CanMoveFlow bool `bson:"can_move_flow" json:"can_move_flow"`
	// 每月通话(分钟)
	CallMonth uint16 `bson:"call_month" json:"call_month"`
	CallPrice uint16 `bson:"call_price" json:"call_price"`
	// 每月短信(条)
	SmsMonth uint16 `bson:"sms_month" json:"sms_month"`
	SmsPrice uint16 `bson:"sms_price" json:"sms_price"`
	MinAge uint8 `bson:"min_age" json:"min_age"`
	MaxAge uint8 `bson:"max_age" json:"max_age"`
	// 归属地, 0:随机, 1:收货地
	Attribution uint32 `bson:"attribution" json:"attribution"`
	// 选号
	PickPhone []SimPickPhone `bson:"pick_phone" json:"pick_phone"`
	// 首充渠道
	FirstChargeLink string `bson:"first_charge_link" json:"first_charge_link"`
	// 首充金额
	FirstChargeMoney string `bson:"first_charge_money" json:"first_charge_money"`
	// 首充返额
	FirstChargeReturn string `bson:"first_charge_return" json:"first_charge_return"`
	// 禁发区域
	BanCity []uint32 `bson:"ban_city" json:"ban_city"`
	Info []*SimInfo `bson:"info" json:"info"`
	// 套餐截图
	Snapshot []string `bson:"snapshot" json:"snapshot"`
}

func resetSim(s *Sim) {
	if s == nil { return }
	*s = Sim{}
	s.Type = defaultType()
	s.Status = defaultItemStatus()
	s.Operator = defaultSimOperator()
}

func defaultSim() *Sim {
	s := &Sim{}
	resetSim(s)
	return s
}

func isZeroSim(s *Sim) bool {
	if s == nil { return true }
	if s.Id != 0 { return false }
	if !isDefaultType(s.Type) { return false }
	if !isDefaultItemStatus(s.Status) { return false }
	if s.Commission != 0 { return false }
	if s.Supplier != 0 { return false }
	if s.Aff != 0 { return false }
	if s.ContractDuration != 0 { return false }
	if s.Name != "" { return false }
	if !isDefaultSimOperator(s.Operator) { return false }
	if s.Monthly != 0 { return false }
	if s.FlowUniversal != 0 { return false }
	if s.FlowDirectional != 0 { return false }
	if s.CanMoveFlow { return false }
	if s.CallMonth != 0 { return false }
	if s.CallPrice != 0 { return false }
	if s.SmsMonth != 0 { return false }
	if s.SmsPrice != 0 { return false }
	if s.MinAge != 0 { return false }
	if s.MaxAge != 0 { return false }
	if s.Attribution != 0 { return false }
	if len(s.PickPhone) != 0 { return false }
	if s.FirstChargeLink != "" { return false }
	if s.FirstChargeMoney != "" { return false }
	if s.FirstChargeReturn != "" { return false }
	if len(s.BanCity) != 0 { return false }
	if len(s.Info) != 0 { return false }
	if len(s.Snapshot) != 0 { return false }
	return true
}

func validateSim(s *Sim) error {
	if s == nil { return nil }
	if !isAssignableType(s.Type) { return fmt.Errorf("Type 非法枚举值: %d", s.Type) }
	if !isAssignableItemStatus(s.Status) { return fmt.Errorf("Status 非法枚举值: %d", s.Status) }
	if _, err := rt.TextState(len(s.Name)); err != nil { return fmt.Errorf("Name: %w", err) }
	if !isAssignableSimOperator(s.Operator) { return fmt.Errorf("Operator 非法枚举值: %d", s.Operator) }
	for i, item := range s.PickPhone {
		if !isAssignableSimPickPhone(item) { return fmt.Errorf("PickPhone[%d] 非法枚举值: %d", i, item) }
	}
	if _, err := rt.TextState(len(s.FirstChargeLink)); err != nil { return fmt.Errorf("FirstChargeLink: %w", err) }
	if _, err := rt.TextState(len(s.FirstChargeMoney)); err != nil { return fmt.Errorf("FirstChargeMoney: %w", err) }
	if _, err := rt.TextState(len(s.FirstChargeReturn)); err != nil { return fmt.Errorf("FirstChargeReturn: %w", err) }
	if _, err := rt.ListCountState(len(s.BanCity)); err != nil { return fmt.Errorf("BanCity: %w", err) }
	for i, item := range s.Info {
		if err := validateSimInfo(item); err != nil { return fmt.Errorf("Info[%d]: %w", i, err) }
	}
	for i, item := range s.Snapshot {
		if _, err := rt.TextState(len(item)); err != nil { return fmt.Errorf("Snapshot[%d]: %w", i, err) }
	}
	return nil
}

func sizeSimValidated(s *Sim) (int, error) {
	if s == nil { return 0, fmt.Errorf("SizeSim: nil value") }
	size := rt.HeaderSize(35)
	if s.Id != 0 { size += 4 }
	if !isDefaultType(s.Type) { size += 1 }
	if !isDefaultItemStatus(s.Status) { size += 1 }
	if s.Commission != 0 { size += 2 }
	if s.Supplier != 0 { size += 4 }
	if s.Aff != 0 { size += 4 }
	if s.ContractDuration != 0 { size += 1 }
	fieldSizeName, err := rt.SizeTextCompact(s.Name)
	if err != nil { return 0, fmt.Errorf("SizeSim Name: %w", err) }
	size += fieldSizeName
	if !isDefaultSimOperator(s.Operator) { size += 1 }
	if s.Monthly != 0 { size += 2 }
	if s.FlowUniversal != 0 { size += 2 }
	if s.FlowDirectional != 0 { size += 2 }
	if s.CallMonth != 0 { size += 2 }
	if s.CallPrice != 0 { size += 2 }
	if s.SmsMonth != 0 { size += 2 }
	if s.SmsPrice != 0 { size += 2 }
	if s.MinAge != 0 { size += 1 }
	if s.MaxAge != 0 { size += 1 }
	if s.Attribution != 0 { size += 4 }
	fieldSizePickPhone, err := sizeSimPickPhoneListBody(s.PickPhone)
	if err != nil { return 0, fmt.Errorf("SizeSim PickPhone: %w", err) }
	size += fieldSizePickPhone
	fieldSizeFirstChargeLink, err := rt.SizeTextCompact(s.FirstChargeLink)
	if err != nil { return 0, fmt.Errorf("SizeSim FirstChargeLink: %w", err) }
	size += fieldSizeFirstChargeLink
	fieldSizeFirstChargeMoney, err := rt.SizeTextCompact(s.FirstChargeMoney)
	if err != nil { return 0, fmt.Errorf("SizeSim FirstChargeMoney: %w", err) }
	size += fieldSizeFirstChargeMoney
	fieldSizeFirstChargeReturn, err := rt.SizeTextCompact(s.FirstChargeReturn)
	if err != nil { return 0, fmt.Errorf("SizeSim FirstChargeReturn: %w", err) }
	size += fieldSizeFirstChargeReturn
	fieldSizeBanCity, err := rt.SizeZeroFixedListCompact(s.BanCity, 4)
	if err != nil { return 0, fmt.Errorf("SizeSim BanCity: %w", err) }
	size += fieldSizeBanCity
	fieldSizeInfo, err := sizeSimInfoListBody(s.Info)
	if err != nil { return 0, fmt.Errorf("SizeSim Info: %w", err) }
	size += fieldSizeInfo
	fieldSizeSnapshot, err := rt.SizeTextListCompact(s.Snapshot)
	if err != nil { return 0, fmt.Errorf("SizeSim Snapshot: %w", err) }
	size += fieldSizeSnapshot
	return size, nil
}

func SizeSim(s *Sim) (int, error) {
	if err := validateSim(s); err != nil { return 0, fmt.Errorf("ValidateSim: %w", err) }
	return sizeSimValidated(s)
}

func GetSim(buf *bytes.Buffer, s *Sim) error {
	if s == nil { return fmt.Errorf("GetSim: nil value") }
	reusePickPhone := s.PickPhone
	reuseBanCity := s.BanCity
	reuseInfo := s.Info
	reuseSnapshot := s.Snapshot
	resetSim(s)
	const headerBits = 35
	headerSize := rt.HeaderSize(headerBits)
	if buf.Len() < headerSize { return fmt.Errorf("GetSim header: %d - %d", buf.Len(), headerSize) }
	header := buf.Next(headerSize)
	if err := rt.ValidatePaddingZero(header, headerBits, "Sim header"); err != nil { return err }
	r := rt.NewBitReader(header, headerBits)
	idPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim Id header: %w", err) }
	typePresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim Type header: %w", err) }
	statusPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim Status header: %w", err) }
	commissionPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim Commission header: %w", err) }
	supplierPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim Supplier header: %w", err) }
	affPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim Aff header: %w", err) }
	contractDurationPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim ContractDuration header: %w", err) }
	nameState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSim Name header: %w", err) }
	operatorPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim Operator header: %w", err) }
	monthlyPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim Monthly header: %w", err) }
	flowUniversalPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim FlowUniversal header: %w", err) }
	flowDirectionalPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim FlowDirectional header: %w", err) }
	canMoveFlowState, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim CanMoveFlow header: %w", err) }
	callMonthPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim CallMonth header: %w", err) }
	callPricePresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim CallPrice header: %w", err) }
	smsMonthPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim SmsMonth header: %w", err) }
	smsPricePresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim SmsPrice header: %w", err) }
	minAgePresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim MinAge header: %w", err) }
	maxAgePresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim MaxAge header: %w", err) }
	attributionPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSim Attribution header: %w", err) }
	pickPhoneState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSim PickPhone header: %w", err) }
	firstChargeLinkState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSim FirstChargeLink header: %w", err) }
	firstChargeMoneyState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSim FirstChargeMoney header: %w", err) }
	firstChargeReturnState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSim FirstChargeReturn header: %w", err) }
	banCityState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSim BanCity header: %w", err) }
	infoState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSim Info header: %w", err) }
	snapshotState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSim Snapshot header: %w", err) }
	if idPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetSim Id: %w", err) }
		s.Id = value
	}
	if typePresent {
		value, err := rt.GetU8(buf)
		if err != nil { return fmt.Errorf("GetSim Type: %w", err) }
		item := Type(value)
		if !isType(item) { return fmt.Errorf("GetSim Type: 非法枚举值: %d", item) }
		s.Type = item
	}
	if statusPresent {
		value, err := rt.GetU8(buf)
		if err != nil { return fmt.Errorf("GetSim Status: %w", err) }
		item := ItemStatus(value)
		if !isItemStatus(item) { return fmt.Errorf("GetSim Status: 非法枚举值: %d", item) }
		s.Status = item
	}
	if commissionPresent {
		value, err := rt.GetU16(buf)
		if err != nil { return fmt.Errorf("GetSim Commission: %w", err) }
		s.Commission = value
	}
	if supplierPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetSim Supplier: %w", err) }
		s.Supplier = value
	}
	if affPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetSim Aff: %w", err) }
		s.Aff = value
	}
	if contractDurationPresent {
		value, err := rt.GetU8(buf)
		if err != nil { return fmt.Errorf("GetSim ContractDuration: %w", err) }
		s.ContractDuration = value
	}
	valueName, err := rt.GetTextCompact(buf, nameState)
	if err != nil { return fmt.Errorf("GetSim Name: %w", err) }
	s.Name = valueName
	if operatorPresent {
		value, err := rt.GetU8(buf)
		if err != nil { return fmt.Errorf("GetSim Operator: %w", err) }
		item := SimOperator(value)
		if !isSimOperator(item) { return fmt.Errorf("GetSim Operator: 非法枚举值: %d", item) }
		s.Operator = item
	}
	if monthlyPresent {
		value, err := rt.GetU16(buf)
		if err != nil { return fmt.Errorf("GetSim Monthly: %w", err) }
		s.Monthly = value
	}
	if flowUniversalPresent {
		value, err := rt.GetU16(buf)
		if err != nil { return fmt.Errorf("GetSim FlowUniversal: %w", err) }
		s.FlowUniversal = value
	}
	if flowDirectionalPresent {
		value, err := rt.GetU16(buf)
		if err != nil { return fmt.Errorf("GetSim FlowDirectional: %w", err) }
		s.FlowDirectional = value
	}
	s.CanMoveFlow = canMoveFlowState
	if callMonthPresent {
		value, err := rt.GetU16(buf)
		if err != nil { return fmt.Errorf("GetSim CallMonth: %w", err) }
		s.CallMonth = value
	}
	if callPricePresent {
		value, err := rt.GetU16(buf)
		if err != nil { return fmt.Errorf("GetSim CallPrice: %w", err) }
		s.CallPrice = value
	}
	if smsMonthPresent {
		value, err := rt.GetU16(buf)
		if err != nil { return fmt.Errorf("GetSim SmsMonth: %w", err) }
		s.SmsMonth = value
	}
	if smsPricePresent {
		value, err := rt.GetU16(buf)
		if err != nil { return fmt.Errorf("GetSim SmsPrice: %w", err) }
		s.SmsPrice = value
	}
	if minAgePresent {
		value, err := rt.GetU8(buf)
		if err != nil { return fmt.Errorf("GetSim MinAge: %w", err) }
		s.MinAge = value
	}
	if maxAgePresent {
		value, err := rt.GetU8(buf)
		if err != nil { return fmt.Errorf("GetSim MaxAge: %w", err) }
		s.MaxAge = value
	}
	if attributionPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetSim Attribution: %w", err) }
		s.Attribution = value
	}
	valuePickPhone, err := getSimPickPhoneListBodyReuse(buf, pickPhoneState, reusePickPhone)
	if err != nil { return fmt.Errorf("GetSim PickPhone: %w", err) }
	s.PickPhone = valuePickPhone
	valueFirstChargeLink, err := rt.GetTextCompact(buf, firstChargeLinkState)
	if err != nil { return fmt.Errorf("GetSim FirstChargeLink: %w", err) }
	s.FirstChargeLink = valueFirstChargeLink
	valueFirstChargeMoney, err := rt.GetTextCompact(buf, firstChargeMoneyState)
	if err != nil { return fmt.Errorf("GetSim FirstChargeMoney: %w", err) }
	s.FirstChargeMoney = valueFirstChargeMoney
	valueFirstChargeReturn, err := rt.GetTextCompact(buf, firstChargeReturnState)
	if err != nil { return fmt.Errorf("GetSim FirstChargeReturn: %w", err) }
	s.FirstChargeReturn = valueFirstChargeReturn
	valueBanCity, err := rt.GetZeroFixedListCompactInto(buf, banCityState, reuseBanCity, rt.GetU32)
	if err != nil { return fmt.Errorf("GetSim BanCity: %w", err) }
	s.BanCity = valueBanCity
	valueInfo, err := getSimInfoListBodyReuse(buf, infoState, reuseInfo)
	if err != nil { return fmt.Errorf("GetSim Info: %w", err) }
	s.Info = valueInfo
	valueSnapshot, err := rt.GetTextListCompactInto(buf, snapshotState, reuseSnapshot)
	if err != nil { return fmt.Errorf("GetSim Snapshot: %w", err) }
	s.Snapshot = valueSnapshot
	return nil
}

func setSimValidated(buf *bytes.Buffer, s *Sim) error {
	if s == nil { return fmt.Errorf("SetSim: nil value") }
	nameState, err := rt.TextState(len(s.Name)); if err != nil { return err }
	pickPhoneState, err := rt.ListCountState(len(s.PickPhone)); if err != nil { return err }
	firstChargeLinkState, err := rt.TextState(len(s.FirstChargeLink)); if err != nil { return err }
	firstChargeMoneyState, err := rt.TextState(len(s.FirstChargeMoney)); if err != nil { return err }
	firstChargeReturnState, err := rt.TextState(len(s.FirstChargeReturn)); if err != nil { return err }
	banCityState, err := rt.ListCountState(len(s.BanCity)); if err != nil { return err }
	infoState, err := rt.ListCountState(len(s.Info)); if err != nil { return err }
	snapshotState, err := rt.ListCountState(len(s.Snapshot)); if err != nil { return err }
	size, err := sizeSimValidated(s)
	if err != nil { return err }
	var headerData [5]byte
	if s.Id != 0 { headerData[0] |= 1 << 7 }
	if !isDefaultType(s.Type) { headerData[0] |= 1 << 6 }
	if !isDefaultItemStatus(s.Status) { headerData[0] |= 1 << 5 }
	if s.Commission != 0 { headerData[0] |= 1 << 4 }
	if s.Supplier != 0 { headerData[0] |= 1 << 3 }
	if s.Aff != 0 { headerData[0] |= 1 << 2 }
	if s.ContractDuration != 0 { headerData[0] |= 1 << 1 }
	headerData[0] |= (nameState >> 1) & 0x01
	headerData[1] |= (nameState & 0x01) << 7
	if !isDefaultSimOperator(s.Operator) { headerData[1] |= 1 << 6 }
	if s.Monthly != 0 { headerData[1] |= 1 << 5 }
	if s.FlowUniversal != 0 { headerData[1] |= 1 << 4 }
	if s.FlowDirectional != 0 { headerData[1] |= 1 << 3 }
	if s.CanMoveFlow { headerData[1] |= 1 << 2 }
	if s.CallMonth != 0 { headerData[1] |= 1 << 1 }
	if s.CallPrice != 0 { headerData[1] |= 1 << 0 }
	if s.SmsMonth != 0 { headerData[2] |= 1 << 7 }
	if s.SmsPrice != 0 { headerData[2] |= 1 << 6 }
	if s.MinAge != 0 { headerData[2] |= 1 << 5 }
	if s.MaxAge != 0 { headerData[2] |= 1 << 4 }
	if s.Attribution != 0 { headerData[2] |= 1 << 3 }
	headerData[2] |= pickPhoneState << 1
	headerData[2] |= (firstChargeLinkState >> 1) & 0x01
	headerData[3] |= (firstChargeLinkState & 0x01) << 7
	headerData[3] |= firstChargeMoneyState << 5
	headerData[3] |= firstChargeReturnState << 3
	headerData[3] |= banCityState << 1
	headerData[3] |= (infoState >> 1) & 0x01
	headerData[4] |= (infoState & 0x01) << 7
	headerData[4] |= snapshotState << 5
	buf.Grow(size)
	if _, err := buf.Write(headerData[:]); err != nil { return fmt.Errorf("SetSim write header: %w", err) }
	if s.Id != 0 {
		if err := rt.SetU32(buf, s.Id); err != nil { return fmt.Errorf("SetSim Id: %w", err) }
	}
	if !isDefaultType(s.Type) {
		if err := rt.SetU8(buf, uint8(normalizeType(s.Type))); err != nil { return fmt.Errorf("SetSim Type: %w", err) }
	}
	if !isDefaultItemStatus(s.Status) {
		if err := rt.SetU8(buf, uint8(normalizeItemStatus(s.Status))); err != nil { return fmt.Errorf("SetSim Status: %w", err) }
	}
	if s.Commission != 0 {
		if err := rt.SetU16(buf, s.Commission); err != nil { return fmt.Errorf("SetSim Commission: %w", err) }
	}
	if s.Supplier != 0 {
		if err := rt.SetU32(buf, s.Supplier); err != nil { return fmt.Errorf("SetSim Supplier: %w", err) }
	}
	if s.Aff != 0 {
		if err := rt.SetU32(buf, s.Aff); err != nil { return fmt.Errorf("SetSim Aff: %w", err) }
	}
	if s.ContractDuration != 0 {
		if err := rt.SetU8(buf, s.ContractDuration); err != nil { return fmt.Errorf("SetSim ContractDuration: %w", err) }
	}
	if err := rt.SetTextCompact(buf, nameState, s.Name); err != nil { return fmt.Errorf("SetSim Name: %w", err) }
	if !isDefaultSimOperator(s.Operator) {
		if err := rt.SetU8(buf, uint8(normalizeSimOperator(s.Operator))); err != nil { return fmt.Errorf("SetSim Operator: %w", err) }
	}
	if s.Monthly != 0 {
		if err := rt.SetU16(buf, s.Monthly); err != nil { return fmt.Errorf("SetSim Monthly: %w", err) }
	}
	if s.FlowUniversal != 0 {
		if err := rt.SetU16(buf, s.FlowUniversal); err != nil { return fmt.Errorf("SetSim FlowUniversal: %w", err) }
	}
	if s.FlowDirectional != 0 {
		if err := rt.SetU16(buf, s.FlowDirectional); err != nil { return fmt.Errorf("SetSim FlowDirectional: %w", err) }
	}
	if s.CallMonth != 0 {
		if err := rt.SetU16(buf, s.CallMonth); err != nil { return fmt.Errorf("SetSim CallMonth: %w", err) }
	}
	if s.CallPrice != 0 {
		if err := rt.SetU16(buf, s.CallPrice); err != nil { return fmt.Errorf("SetSim CallPrice: %w", err) }
	}
	if s.SmsMonth != 0 {
		if err := rt.SetU16(buf, s.SmsMonth); err != nil { return fmt.Errorf("SetSim SmsMonth: %w", err) }
	}
	if s.SmsPrice != 0 {
		if err := rt.SetU16(buf, s.SmsPrice); err != nil { return fmt.Errorf("SetSim SmsPrice: %w", err) }
	}
	if s.MinAge != 0 {
		if err := rt.SetU8(buf, s.MinAge); err != nil { return fmt.Errorf("SetSim MinAge: %w", err) }
	}
	if s.MaxAge != 0 {
		if err := rt.SetU8(buf, s.MaxAge); err != nil { return fmt.Errorf("SetSim MaxAge: %w", err) }
	}
	if s.Attribution != 0 {
		if err := rt.SetU32(buf, s.Attribution); err != nil { return fmt.Errorf("SetSim Attribution: %w", err) }
	}
	if err := setSimPickPhoneListBody(buf, pickPhoneState, s.PickPhone); err != nil { return fmt.Errorf("SetSim PickPhone: %w", err) }
	if err := rt.SetTextCompact(buf, firstChargeLinkState, s.FirstChargeLink); err != nil { return fmt.Errorf("SetSim FirstChargeLink: %w", err) }
	if err := rt.SetTextCompact(buf, firstChargeMoneyState, s.FirstChargeMoney); err != nil { return fmt.Errorf("SetSim FirstChargeMoney: %w", err) }
	if err := rt.SetTextCompact(buf, firstChargeReturnState, s.FirstChargeReturn); err != nil { return fmt.Errorf("SetSim FirstChargeReturn: %w", err) }
	if err := rt.SetZeroFixedListCompactSized(buf, banCityState, s.BanCity, 4, rt.SetU32); err != nil { return fmt.Errorf("SetSim BanCity: %w", err) }
	if err := setSimInfoListBody(buf, infoState, s.Info); err != nil { return fmt.Errorf("SetSim Info: %w", err) }
	if err := rt.SetTextListCompact(buf, snapshotState, s.Snapshot); err != nil { return fmt.Errorf("SetSim Snapshot: %w", err) }
	return nil
}

func SetSim(buf *bytes.Buffer, s *Sim) error {
	if s == nil { return fmt.Errorf("SetSim: nil value") }
	if err := validateSim(s); err != nil { return fmt.Errorf("ValidateSim: %w", err) }
	return setSimValidated(buf, s)
}

func ReadSim(buf *bytes.Buffer) (*Sim, error) {
	s := defaultSim()
	return s, GetSim(buf, s)
}

func EqSim(a, b *Sim) bool {
	if isZeroSim(a) && isZeroSim(b) { return true }
	if a == nil || b == nil { return false }
	if !(a.Id == b.Id) { return false }
	if !(eqTypeValue(a.Type, b.Type)) { return false }
	if !(eqItemStatusValue(a.Status, b.Status)) { return false }
	if !(a.Commission == b.Commission) { return false }
	if !(a.Supplier == b.Supplier) { return false }
	if !(a.Aff == b.Aff) { return false }
	if !(a.ContractDuration == b.ContractDuration) { return false }
	if !(a.Name == b.Name) { return false }
	if !(eqSimOperatorValue(a.Operator, b.Operator)) { return false }
	if !(a.Monthly == b.Monthly) { return false }
	if !(a.FlowUniversal == b.FlowUniversal) { return false }
	if !(a.FlowDirectional == b.FlowDirectional) { return false }
	if !(a.CanMoveFlow == b.CanMoveFlow) { return false }
	if !(a.CallMonth == b.CallMonth) { return false }
	if !(a.CallPrice == b.CallPrice) { return false }
	if !(a.SmsMonth == b.SmsMonth) { return false }
	if !(a.SmsPrice == b.SmsPrice) { return false }
	if !(a.MinAge == b.MinAge) { return false }
	if !(a.MaxAge == b.MaxAge) { return false }
	if !(a.Attribution == b.Attribution) { return false }
	if !(eqSimPickPhoneList(a.PickPhone, b.PickPhone)) { return false }
	if !(a.FirstChargeLink == b.FirstChargeLink) { return false }
	if !(a.FirstChargeMoney == b.FirstChargeMoney) { return false }
	if !(a.FirstChargeReturn == b.FirstChargeReturn) { return false }
	if !(slices.Equal(a.BanCity, b.BanCity)) { return false }
	if !(slices.EqualFunc(a.Info, b.Info, EqSimInfo)) { return false }
	if !(slices.Equal(a.Snapshot, b.Snapshot)) { return false }
	return true
}

func getSimListBody(buf *bytes.Buffer, state uint8) ([]*Sim, error) {
	return getSimListBodyReuse(buf, state, nil)
}

func getSimListBodyReuse(buf *bytes.Buffer, state uint8, dst []*Sim) ([]*Sim, error) {
	return rt.GetBitmapPtrListCompactInto(buf, state, dst, defaultSim, GetSim)
}

func setSimListBody(buf *bytes.Buffer, state uint8, v []*Sim) error {
	return rt.SetBitmapPtrListCompactValidated(
		buf,
		state,
		v,
		"Sim",
		validateSim,
		isZeroSim,
		SizeSim,
		setSimValidated,
	)
}

func sizeSimListBody(v []*Sim) (int, error) {
	return rt.SizeBitmapPtrListCompactValidated(
		v,
		"Sim",
		validateSim,
		isZeroSim,
		SizeSim,
	)
}

type SimInfo struct {
	Id uint32 `bson:"id" json:"id"`
	Title string `bson:"title" json:"title"`
	Content string `bson:"content" json:"content"`
	A bool `bson:"a" json:"a"`
	B bool `bson:"b" json:"b"`
	C bool `bson:"c" json:"c"`
	D bool `bson:"d" json:"d"`
	Zip []byte `bson:"zip" json:"zip"`
}

func resetSimInfo(s *SimInfo) {
	if s == nil { return }
	*s = SimInfo{}
}

func defaultSimInfo() *SimInfo {
	s := &SimInfo{}
	resetSimInfo(s)
	return s
}

func isZeroSimInfo(s *SimInfo) bool {
	if s == nil { return true }
	if s.Id != 0 { return false }
	if s.Title != "" { return false }
	if s.Content != "" { return false }
	if s.A { return false }
	if s.B { return false }
	if s.C { return false }
	if s.D { return false }
	if len(s.Zip) != 0 { return false }
	return true
}

func validateSimInfo(s *SimInfo) error {
	if s == nil { return nil }
	if _, err := rt.TextState(len(s.Title)); err != nil { return fmt.Errorf("Title: %w", err) }
	if _, err := rt.TextState(len(s.Content)); err != nil { return fmt.Errorf("Content: %w", err) }
	if _, err := rt.BinState(len(s.Zip)); err != nil { return fmt.Errorf("Zip: %w", err) }
	return nil
}

func sizeSimInfoValidated(s *SimInfo) (int, error) {
	if s == nil { return 0, fmt.Errorf("SizeSimInfo: nil value") }
	size := rt.HeaderSize(11)
	if s.Id != 0 { size += 4 }
	fieldSizeTitle, err := rt.SizeTextCompact(s.Title)
	if err != nil { return 0, fmt.Errorf("SizeSimInfo Title: %w", err) }
	size += fieldSizeTitle
	fieldSizeContent, err := rt.SizeTextCompact(s.Content)
	if err != nil { return 0, fmt.Errorf("SizeSimInfo Content: %w", err) }
	size += fieldSizeContent
	fieldSizeZip, err := rt.SizeBinCompact(s.Zip)
	if err != nil { return 0, fmt.Errorf("SizeSimInfo Zip: %w", err) }
	size += fieldSizeZip
	return size, nil
}

func SizeSimInfo(s *SimInfo) (int, error) {
	if err := validateSimInfo(s); err != nil { return 0, fmt.Errorf("ValidateSimInfo: %w", err) }
	return sizeSimInfoValidated(s)
}

func GetSimInfo(buf *bytes.Buffer, s *SimInfo) error {
	if s == nil { return fmt.Errorf("GetSimInfo: nil value") }
	reuseZip := s.Zip
	resetSimInfo(s)
	const headerBits = 11
	headerSize := rt.HeaderSize(headerBits)
	if buf.Len() < headerSize { return fmt.Errorf("GetSimInfo header: %d - %d", buf.Len(), headerSize) }
	header := buf.Next(headerSize)
	if err := rt.ValidatePaddingZero(header, headerBits, "SimInfo header"); err != nil { return err }
	r := rt.NewBitReader(header, headerBits)
	idPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimInfo Id header: %w", err) }
	titleState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimInfo Title header: %w", err) }
	contentState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimInfo Content header: %w", err) }
	aState, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimInfo A header: %w", err) }
	bState, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimInfo B header: %w", err) }
	cState, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimInfo C header: %w", err) }
	dState, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimInfo D header: %w", err) }
	zipState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimInfo Zip header: %w", err) }
	if idPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetSimInfo Id: %w", err) }
		s.Id = value
	}
	valueTitle, err := rt.GetTextCompact(buf, titleState)
	if err != nil { return fmt.Errorf("GetSimInfo Title: %w", err) }
	s.Title = valueTitle
	valueContent, err := rt.GetTextCompact(buf, contentState)
	if err != nil { return fmt.Errorf("GetSimInfo Content: %w", err) }
	s.Content = valueContent
	s.A = aState
	s.B = bState
	s.C = cState
	s.D = dState
	valueZip, err := rt.GetBinCompactInto(buf, zipState, reuseZip)
	if err != nil { return fmt.Errorf("GetSimInfo Zip: %w", err) }
	s.Zip = valueZip
	return nil
}

func setSimInfoValidated(buf *bytes.Buffer, s *SimInfo) error {
	if s == nil { return fmt.Errorf("SetSimInfo: nil value") }
	titleState, err := rt.TextState(len(s.Title)); if err != nil { return err }
	contentState, err := rt.TextState(len(s.Content)); if err != nil { return err }
	zipState, err := rt.BinState(len(s.Zip)); if err != nil { return err }
	size, err := sizeSimInfoValidated(s)
	if err != nil { return err }
	var headerData [2]byte
	if s.Id != 0 { headerData[0] |= 1 << 7 }
	headerData[0] |= titleState << 5
	headerData[0] |= contentState << 3
	if s.A { headerData[0] |= 1 << 2 }
	if s.B { headerData[0] |= 1 << 1 }
	if s.C { headerData[0] |= 1 << 0 }
	if s.D { headerData[1] |= 1 << 7 }
	headerData[1] |= zipState << 5
	buf.Grow(size)
	if _, err := buf.Write(headerData[:]); err != nil { return fmt.Errorf("SetSimInfo write header: %w", err) }
	if s.Id != 0 {
		if err := rt.SetU32(buf, s.Id); err != nil { return fmt.Errorf("SetSimInfo Id: %w", err) }
	}
	if err := rt.SetTextCompact(buf, titleState, s.Title); err != nil { return fmt.Errorf("SetSimInfo Title: %w", err) }
	if err := rt.SetTextCompact(buf, contentState, s.Content); err != nil { return fmt.Errorf("SetSimInfo Content: %w", err) }
	if err := rt.SetBinCompact(buf, zipState, s.Zip); err != nil { return fmt.Errorf("SetSimInfo Zip: %w", err) }
	return nil
}

func SetSimInfo(buf *bytes.Buffer, s *SimInfo) error {
	if s == nil { return fmt.Errorf("SetSimInfo: nil value") }
	if err := validateSimInfo(s); err != nil { return fmt.Errorf("ValidateSimInfo: %w", err) }
	return setSimInfoValidated(buf, s)
}

func ReadSimInfo(buf *bytes.Buffer) (*SimInfo, error) {
	s := defaultSimInfo()
	return s, GetSimInfo(buf, s)
}

func EqSimInfo(a, b *SimInfo) bool {
	if isZeroSimInfo(a) && isZeroSimInfo(b) { return true }
	if a == nil || b == nil { return false }
	if !(a.Id == b.Id) { return false }
	if !(a.Title == b.Title) { return false }
	if !(a.Content == b.Content) { return false }
	if !(a.A == b.A) { return false }
	if !(a.B == b.B) { return false }
	if !(a.C == b.C) { return false }
	if !(a.D == b.D) { return false }
	if !(eqBin(a.Zip, b.Zip)) { return false }
	return true
}

func getSimInfoListBody(buf *bytes.Buffer, state uint8) ([]*SimInfo, error) {
	return getSimInfoListBodyReuse(buf, state, nil)
}

func getSimInfoListBodyReuse(buf *bytes.Buffer, state uint8, dst []*SimInfo) ([]*SimInfo, error) {
	return rt.GetBitmapPtrListCompactInto(buf, state, dst, defaultSimInfo, GetSimInfo)
}

func setSimInfoListBody(buf *bytes.Buffer, state uint8, v []*SimInfo) error {
	return rt.SetBitmapPtrListCompactValidated(
		buf,
		state,
		v,
		"SimInfo",
		validateSimInfo,
		isZeroSimInfo,
		SizeSimInfo,
		setSimInfoValidated,
	)
}

func sizeSimInfoListBody(v []*SimInfo) (int, error) {
	return rt.SizeBitmapPtrListCompactValidated(
		v,
		"SimInfo",
		validateSimInfo,
		isZeroSimInfo,
		SizeSimInfo,
	)
}

type SimOrder2 struct {
	// SIM卡ID
	Id uint32 `bson:"id" json:"id"`
	// 办理人姓名
	Name string `bson:"name" json:"name"`
	// 联系电话
	Phone string `bson:"phone" json:"phone"`
	// 身份证号
	IdNo string `bson:"id_no" json:"id_no"`
	// 所在城市
	CityCode uint32 `bson:"city_code" json:"city_code"`
	// 详细地址
	Address string `bson:"address" json:"address"`
	// 新手机号码
	NewPhone string `bson:"new_phone" json:"new_phone"`
}

func resetSimOrder2(s *SimOrder2) {
	if s == nil { return }
	*s = SimOrder2{}
}

func defaultSimOrder2() *SimOrder2 {
	s := &SimOrder2{}
	resetSimOrder2(s)
	return s
}

func isZeroSimOrder2(s *SimOrder2) bool {
	if s == nil { return true }
	if s.Id != 0 { return false }
	if s.Name != "" { return false }
	if s.Phone != "" { return false }
	if s.IdNo != "" { return false }
	if s.CityCode != 0 { return false }
	if s.Address != "" { return false }
	if s.NewPhone != "" { return false }
	return true
}

func validateSimOrder2(s *SimOrder2) error {
	if s == nil { return nil }
	if _, err := rt.TextState(len(s.Name)); err != nil { return fmt.Errorf("Name: %w", err) }
	if _, err := rt.TextState(len(s.Phone)); err != nil { return fmt.Errorf("Phone: %w", err) }
	if _, err := rt.TextState(len(s.IdNo)); err != nil { return fmt.Errorf("IdNo: %w", err) }
	if _, err := rt.TextState(len(s.Address)); err != nil { return fmt.Errorf("Address: %w", err) }
	if _, err := rt.TextState(len(s.NewPhone)); err != nil { return fmt.Errorf("NewPhone: %w", err) }
	return nil
}

func sizeSimOrder2Validated(s *SimOrder2) (int, error) {
	if s == nil { return 0, fmt.Errorf("SizeSimOrder2: nil value") }
	size := rt.HeaderSize(12)
	if s.Id != 0 { size += 4 }
	fieldSizeName, err := rt.SizeTextCompact(s.Name)
	if err != nil { return 0, fmt.Errorf("SizeSimOrder2 Name: %w", err) }
	size += fieldSizeName
	fieldSizePhone, err := rt.SizeTextCompact(s.Phone)
	if err != nil { return 0, fmt.Errorf("SizeSimOrder2 Phone: %w", err) }
	size += fieldSizePhone
	fieldSizeIdNo, err := rt.SizeTextCompact(s.IdNo)
	if err != nil { return 0, fmt.Errorf("SizeSimOrder2 IdNo: %w", err) }
	size += fieldSizeIdNo
	if s.CityCode != 0 { size += 4 }
	fieldSizeAddress, err := rt.SizeTextCompact(s.Address)
	if err != nil { return 0, fmt.Errorf("SizeSimOrder2 Address: %w", err) }
	size += fieldSizeAddress
	fieldSizeNewPhone, err := rt.SizeTextCompact(s.NewPhone)
	if err != nil { return 0, fmt.Errorf("SizeSimOrder2 NewPhone: %w", err) }
	size += fieldSizeNewPhone
	return size, nil
}

func SizeSimOrder2(s *SimOrder2) (int, error) {
	if err := validateSimOrder2(s); err != nil { return 0, fmt.Errorf("ValidateSimOrder2: %w", err) }
	return sizeSimOrder2Validated(s)
}

func GetSimOrder2(buf *bytes.Buffer, s *SimOrder2) error {
	if s == nil { return fmt.Errorf("GetSimOrder2: nil value") }
	resetSimOrder2(s)
	const headerBits = 12
	headerSize := rt.HeaderSize(headerBits)
	if buf.Len() < headerSize { return fmt.Errorf("GetSimOrder2 header: %d - %d", buf.Len(), headerSize) }
	header := buf.Next(headerSize)
	if err := rt.ValidatePaddingZero(header, headerBits, "SimOrder2 header"); err != nil { return err }
	r := rt.NewBitReader(header, headerBits)
	idPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimOrder2 Id header: %w", err) }
	nameState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimOrder2 Name header: %w", err) }
	phoneState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimOrder2 Phone header: %w", err) }
	idNoState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimOrder2 IdNo header: %w", err) }
	cityCodePresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimOrder2 CityCode header: %w", err) }
	addressState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimOrder2 Address header: %w", err) }
	newPhoneState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimOrder2 NewPhone header: %w", err) }
	if idPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetSimOrder2 Id: %w", err) }
		s.Id = value
	}
	valueName, err := rt.GetTextCompact(buf, nameState)
	if err != nil { return fmt.Errorf("GetSimOrder2 Name: %w", err) }
	s.Name = valueName
	valuePhone, err := rt.GetTextCompact(buf, phoneState)
	if err != nil { return fmt.Errorf("GetSimOrder2 Phone: %w", err) }
	s.Phone = valuePhone
	valueIdNo, err := rt.GetTextCompact(buf, idNoState)
	if err != nil { return fmt.Errorf("GetSimOrder2 IdNo: %w", err) }
	s.IdNo = valueIdNo
	if cityCodePresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetSimOrder2 CityCode: %w", err) }
		s.CityCode = value
	}
	valueAddress, err := rt.GetTextCompact(buf, addressState)
	if err != nil { return fmt.Errorf("GetSimOrder2 Address: %w", err) }
	s.Address = valueAddress
	valueNewPhone, err := rt.GetTextCompact(buf, newPhoneState)
	if err != nil { return fmt.Errorf("GetSimOrder2 NewPhone: %w", err) }
	s.NewPhone = valueNewPhone
	return nil
}

func setSimOrder2Validated(buf *bytes.Buffer, s *SimOrder2) error {
	if s == nil { return fmt.Errorf("SetSimOrder2: nil value") }
	nameState, err := rt.TextState(len(s.Name)); if err != nil { return err }
	phoneState, err := rt.TextState(len(s.Phone)); if err != nil { return err }
	idNoState, err := rt.TextState(len(s.IdNo)); if err != nil { return err }
	addressState, err := rt.TextState(len(s.Address)); if err != nil { return err }
	newPhoneState, err := rt.TextState(len(s.NewPhone)); if err != nil { return err }
	size, err := sizeSimOrder2Validated(s)
	if err != nil { return err }
	var headerData [2]byte
	if s.Id != 0 { headerData[0] |= 1 << 7 }
	headerData[0] |= nameState << 5
	headerData[0] |= phoneState << 3
	headerData[0] |= idNoState << 1
	if s.CityCode != 0 { headerData[0] |= 1 << 0 }
	headerData[1] |= addressState << 6
	headerData[1] |= newPhoneState << 4
	buf.Grow(size)
	if _, err := buf.Write(headerData[:]); err != nil { return fmt.Errorf("SetSimOrder2 write header: %w", err) }
	if s.Id != 0 {
		if err := rt.SetU32(buf, s.Id); err != nil { return fmt.Errorf("SetSimOrder2 Id: %w", err) }
	}
	if err := rt.SetTextCompact(buf, nameState, s.Name); err != nil { return fmt.Errorf("SetSimOrder2 Name: %w", err) }
	if err := rt.SetTextCompact(buf, phoneState, s.Phone); err != nil { return fmt.Errorf("SetSimOrder2 Phone: %w", err) }
	if err := rt.SetTextCompact(buf, idNoState, s.IdNo); err != nil { return fmt.Errorf("SetSimOrder2 IdNo: %w", err) }
	if s.CityCode != 0 {
		if err := rt.SetU32(buf, s.CityCode); err != nil { return fmt.Errorf("SetSimOrder2 CityCode: %w", err) }
	}
	if err := rt.SetTextCompact(buf, addressState, s.Address); err != nil { return fmt.Errorf("SetSimOrder2 Address: %w", err) }
	if err := rt.SetTextCompact(buf, newPhoneState, s.NewPhone); err != nil { return fmt.Errorf("SetSimOrder2 NewPhone: %w", err) }
	return nil
}

func SetSimOrder2(buf *bytes.Buffer, s *SimOrder2) error {
	if s == nil { return fmt.Errorf("SetSimOrder2: nil value") }
	if err := validateSimOrder2(s); err != nil { return fmt.Errorf("ValidateSimOrder2: %w", err) }
	return setSimOrder2Validated(buf, s)
}

func ReadSimOrder2(buf *bytes.Buffer) (*SimOrder2, error) {
	s := defaultSimOrder2()
	return s, GetSimOrder2(buf, s)
}

func EqSimOrder2(a, b *SimOrder2) bool {
	if isZeroSimOrder2(a) && isZeroSimOrder2(b) { return true }
	if a == nil || b == nil { return false }
	if !(a.Id == b.Id) { return false }
	if !(a.Name == b.Name) { return false }
	if !(a.Phone == b.Phone) { return false }
	if !(a.IdNo == b.IdNo) { return false }
	if !(a.CityCode == b.CityCode) { return false }
	if !(a.Address == b.Address) { return false }
	if !(a.NewPhone == b.NewPhone) { return false }
	return true
}

func getSimOrder2ListBody(buf *bytes.Buffer, state uint8) ([]*SimOrder2, error) {
	return getSimOrder2ListBodyReuse(buf, state, nil)
}

func getSimOrder2ListBodyReuse(buf *bytes.Buffer, state uint8, dst []*SimOrder2) ([]*SimOrder2, error) {
	return rt.GetBitmapPtrListCompactInto(buf, state, dst, defaultSimOrder2, GetSimOrder2)
}

func setSimOrder2ListBody(buf *bytes.Buffer, state uint8, v []*SimOrder2) error {
	return rt.SetBitmapPtrListCompactValidated(
		buf,
		state,
		v,
		"SimOrder2",
		validateSimOrder2,
		isZeroSimOrder2,
		SizeSimOrder2,
		setSimOrder2Validated,
	)
}

func sizeSimOrder2ListBody(v []*SimOrder2) (int, error) {
	return rt.SizeBitmapPtrListCompactValidated(
		v,
		"SimOrder2",
		validateSimOrder2,
		isZeroSimOrder2,
		SizeSimOrder2,
	)
}

type SimOrder struct {
	Id uint32 `bson:"id" json:"id"`
	AccountId uint32 `bson:"account_id" json:"account_id"`
	ItemId uint32 `bson:"item_id" json:"item_id"`
	// 办理人姓名
	Name string `bson:"name" json:"name"`
	// 联系电话
	Phone string `bson:"phone" json:"phone"`
	// 身份证号
	IdNo string `bson:"id_no" json:"id_no"`
	// 所在城市
	CityCode uint32 `bson:"city_code" json:"city_code"`
	// 详细地址
	Address string `bson:"address" json:"address"`
	// 新手机号码
	NewPhone string `bson:"new_phone" json:"new_phone"`
	// 佣金
	Commission uint16 `bson:"commission" json:"commission"`
	Status OrderStatus `bson:"status" json:"status"`
}

func resetSimOrder(s *SimOrder) {
	if s == nil { return }
	*s = SimOrder{}
	s.Status = defaultOrderStatus()
}

func defaultSimOrder() *SimOrder {
	s := &SimOrder{}
	resetSimOrder(s)
	return s
}

func isZeroSimOrder(s *SimOrder) bool {
	if s == nil { return true }
	if s.Id != 0 { return false }
	if s.AccountId != 0 { return false }
	if s.ItemId != 0 { return false }
	if s.Name != "" { return false }
	if s.Phone != "" { return false }
	if s.IdNo != "" { return false }
	if s.CityCode != 0 { return false }
	if s.Address != "" { return false }
	if s.NewPhone != "" { return false }
	if s.Commission != 0 { return false }
	if !isDefaultOrderStatus(s.Status) { return false }
	return true
}

func validateSimOrder(s *SimOrder) error {
	if s == nil { return nil }
	if _, err := rt.TextState(len(s.Name)); err != nil { return fmt.Errorf("Name: %w", err) }
	if _, err := rt.TextState(len(s.Phone)); err != nil { return fmt.Errorf("Phone: %w", err) }
	if _, err := rt.TextState(len(s.IdNo)); err != nil { return fmt.Errorf("IdNo: %w", err) }
	if _, err := rt.TextState(len(s.Address)); err != nil { return fmt.Errorf("Address: %w", err) }
	if _, err := rt.TextState(len(s.NewPhone)); err != nil { return fmt.Errorf("NewPhone: %w", err) }
	if !isAssignableOrderStatus(s.Status) { return fmt.Errorf("Status 非法枚举值: %d", s.Status) }
	return nil
}

func sizeSimOrderValidated(s *SimOrder) (int, error) {
	if s == nil { return 0, fmt.Errorf("SizeSimOrder: nil value") }
	size := rt.HeaderSize(16)
	if s.Id != 0 { size += 4 }
	if s.AccountId != 0 { size += 4 }
	if s.ItemId != 0 { size += 4 }
	fieldSizeName, err := rt.SizeTextCompact(s.Name)
	if err != nil { return 0, fmt.Errorf("SizeSimOrder Name: %w", err) }
	size += fieldSizeName
	fieldSizePhone, err := rt.SizeTextCompact(s.Phone)
	if err != nil { return 0, fmt.Errorf("SizeSimOrder Phone: %w", err) }
	size += fieldSizePhone
	fieldSizeIdNo, err := rt.SizeTextCompact(s.IdNo)
	if err != nil { return 0, fmt.Errorf("SizeSimOrder IdNo: %w", err) }
	size += fieldSizeIdNo
	if s.CityCode != 0 { size += 4 }
	fieldSizeAddress, err := rt.SizeTextCompact(s.Address)
	if err != nil { return 0, fmt.Errorf("SizeSimOrder Address: %w", err) }
	size += fieldSizeAddress
	fieldSizeNewPhone, err := rt.SizeTextCompact(s.NewPhone)
	if err != nil { return 0, fmt.Errorf("SizeSimOrder NewPhone: %w", err) }
	size += fieldSizeNewPhone
	if s.Commission != 0 { size += 2 }
	if !isDefaultOrderStatus(s.Status) { size += 1 }
	return size, nil
}

func SizeSimOrder(s *SimOrder) (int, error) {
	if err := validateSimOrder(s); err != nil { return 0, fmt.Errorf("ValidateSimOrder: %w", err) }
	return sizeSimOrderValidated(s)
}

func GetSimOrder(buf *bytes.Buffer, s *SimOrder) error {
	if s == nil { return fmt.Errorf("GetSimOrder: nil value") }
	resetSimOrder(s)
	const headerBits = 16
	headerSize := rt.HeaderSize(headerBits)
	if buf.Len() < headerSize { return fmt.Errorf("GetSimOrder header: %d - %d", buf.Len(), headerSize) }
	header := buf.Next(headerSize)
	if err := rt.ValidatePaddingZero(header, headerBits, "SimOrder header"); err != nil { return err }
	r := rt.NewBitReader(header, headerBits)
	idPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimOrder Id header: %w", err) }
	accountIdPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimOrder AccountId header: %w", err) }
	itemIdPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimOrder ItemId header: %w", err) }
	nameState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimOrder Name header: %w", err) }
	phoneState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimOrder Phone header: %w", err) }
	idNoState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimOrder IdNo header: %w", err) }
	cityCodePresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimOrder CityCode header: %w", err) }
	addressState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimOrder Address header: %w", err) }
	newPhoneState, err := r.ReadBits(2)
	if err != nil { return fmt.Errorf("GetSimOrder NewPhone header: %w", err) }
	commissionPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimOrder Commission header: %w", err) }
	statusPresent, err := r.ReadBit()
	if err != nil { return fmt.Errorf("GetSimOrder Status header: %w", err) }
	if idPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetSimOrder Id: %w", err) }
		s.Id = value
	}
	if accountIdPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetSimOrder AccountId: %w", err) }
		s.AccountId = value
	}
	if itemIdPresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetSimOrder ItemId: %w", err) }
		s.ItemId = value
	}
	valueName, err := rt.GetTextCompact(buf, nameState)
	if err != nil { return fmt.Errorf("GetSimOrder Name: %w", err) }
	s.Name = valueName
	valuePhone, err := rt.GetTextCompact(buf, phoneState)
	if err != nil { return fmt.Errorf("GetSimOrder Phone: %w", err) }
	s.Phone = valuePhone
	valueIdNo, err := rt.GetTextCompact(buf, idNoState)
	if err != nil { return fmt.Errorf("GetSimOrder IdNo: %w", err) }
	s.IdNo = valueIdNo
	if cityCodePresent {
		value, err := rt.GetU32(buf)
		if err != nil { return fmt.Errorf("GetSimOrder CityCode: %w", err) }
		s.CityCode = value
	}
	valueAddress, err := rt.GetTextCompact(buf, addressState)
	if err != nil { return fmt.Errorf("GetSimOrder Address: %w", err) }
	s.Address = valueAddress
	valueNewPhone, err := rt.GetTextCompact(buf, newPhoneState)
	if err != nil { return fmt.Errorf("GetSimOrder NewPhone: %w", err) }
	s.NewPhone = valueNewPhone
	if commissionPresent {
		value, err := rt.GetU16(buf)
		if err != nil { return fmt.Errorf("GetSimOrder Commission: %w", err) }
		s.Commission = value
	}
	if statusPresent {
		value, err := rt.GetU8(buf)
		if err != nil { return fmt.Errorf("GetSimOrder Status: %w", err) }
		item := OrderStatus(value)
		if !isOrderStatus(item) { return fmt.Errorf("GetSimOrder Status: 非法枚举值: %d", item) }
		s.Status = item
	}
	return nil
}

func setSimOrderValidated(buf *bytes.Buffer, s *SimOrder) error {
	if s == nil { return fmt.Errorf("SetSimOrder: nil value") }
	nameState, err := rt.TextState(len(s.Name)); if err != nil { return err }
	phoneState, err := rt.TextState(len(s.Phone)); if err != nil { return err }
	idNoState, err := rt.TextState(len(s.IdNo)); if err != nil { return err }
	addressState, err := rt.TextState(len(s.Address)); if err != nil { return err }
	newPhoneState, err := rt.TextState(len(s.NewPhone)); if err != nil { return err }
	size, err := sizeSimOrderValidated(s)
	if err != nil { return err }
	var headerData [2]byte
	if s.Id != 0 { headerData[0] |= 1 << 7 }
	if s.AccountId != 0 { headerData[0] |= 1 << 6 }
	if s.ItemId != 0 { headerData[0] |= 1 << 5 }
	headerData[0] |= nameState << 3
	headerData[0] |= phoneState << 1
	headerData[0] |= (idNoState >> 1) & 0x01
	headerData[1] |= (idNoState & 0x01) << 7
	if s.CityCode != 0 { headerData[1] |= 1 << 6 }
	headerData[1] |= addressState << 4
	headerData[1] |= newPhoneState << 2
	if s.Commission != 0 { headerData[1] |= 1 << 1 }
	if !isDefaultOrderStatus(s.Status) { headerData[1] |= 1 << 0 }
	buf.Grow(size)
	if _, err := buf.Write(headerData[:]); err != nil { return fmt.Errorf("SetSimOrder write header: %w", err) }
	if s.Id != 0 {
		if err := rt.SetU32(buf, s.Id); err != nil { return fmt.Errorf("SetSimOrder Id: %w", err) }
	}
	if s.AccountId != 0 {
		if err := rt.SetU32(buf, s.AccountId); err != nil { return fmt.Errorf("SetSimOrder AccountId: %w", err) }
	}
	if s.ItemId != 0 {
		if err := rt.SetU32(buf, s.ItemId); err != nil { return fmt.Errorf("SetSimOrder ItemId: %w", err) }
	}
	if err := rt.SetTextCompact(buf, nameState, s.Name); err != nil { return fmt.Errorf("SetSimOrder Name: %w", err) }
	if err := rt.SetTextCompact(buf, phoneState, s.Phone); err != nil { return fmt.Errorf("SetSimOrder Phone: %w", err) }
	if err := rt.SetTextCompact(buf, idNoState, s.IdNo); err != nil { return fmt.Errorf("SetSimOrder IdNo: %w", err) }
	if s.CityCode != 0 {
		if err := rt.SetU32(buf, s.CityCode); err != nil { return fmt.Errorf("SetSimOrder CityCode: %w", err) }
	}
	if err := rt.SetTextCompact(buf, addressState, s.Address); err != nil { return fmt.Errorf("SetSimOrder Address: %w", err) }
	if err := rt.SetTextCompact(buf, newPhoneState, s.NewPhone); err != nil { return fmt.Errorf("SetSimOrder NewPhone: %w", err) }
	if s.Commission != 0 {
		if err := rt.SetU16(buf, s.Commission); err != nil { return fmt.Errorf("SetSimOrder Commission: %w", err) }
	}
	if !isDefaultOrderStatus(s.Status) {
		if err := rt.SetU8(buf, uint8(normalizeOrderStatus(s.Status))); err != nil { return fmt.Errorf("SetSimOrder Status: %w", err) }
	}
	return nil
}

func SetSimOrder(buf *bytes.Buffer, s *SimOrder) error {
	if s == nil { return fmt.Errorf("SetSimOrder: nil value") }
	if err := validateSimOrder(s); err != nil { return fmt.Errorf("ValidateSimOrder: %w", err) }
	return setSimOrderValidated(buf, s)
}

func ReadSimOrder(buf *bytes.Buffer) (*SimOrder, error) {
	s := defaultSimOrder()
	return s, GetSimOrder(buf, s)
}

func EqSimOrder(a, b *SimOrder) bool {
	if isZeroSimOrder(a) && isZeroSimOrder(b) { return true }
	if a == nil || b == nil { return false }
	if !(a.Id == b.Id) { return false }
	if !(a.AccountId == b.AccountId) { return false }
	if !(a.ItemId == b.ItemId) { return false }
	if !(a.Name == b.Name) { return false }
	if !(a.Phone == b.Phone) { return false }
	if !(a.IdNo == b.IdNo) { return false }
	if !(a.CityCode == b.CityCode) { return false }
	if !(a.Address == b.Address) { return false }
	if !(a.NewPhone == b.NewPhone) { return false }
	if !(a.Commission == b.Commission) { return false }
	if !(eqOrderStatusValue(a.Status, b.Status)) { return false }
	return true
}

func getSimOrderListBody(buf *bytes.Buffer, state uint8) ([]*SimOrder, error) {
	return getSimOrderListBodyReuse(buf, state, nil)
}

func getSimOrderListBodyReuse(buf *bytes.Buffer, state uint8, dst []*SimOrder) ([]*SimOrder, error) {
	return rt.GetBitmapPtrListCompactInto(buf, state, dst, defaultSimOrder, GetSimOrder)
}

func setSimOrderListBody(buf *bytes.Buffer, state uint8, v []*SimOrder) error {
	return rt.SetBitmapPtrListCompactValidated(
		buf,
		state,
		v,
		"SimOrder",
		validateSimOrder,
		isZeroSimOrder,
		SizeSimOrder,
		setSimOrderValidated,
	)
}

func sizeSimOrderListBody(v []*SimOrder) (int, error) {
	return rt.SizeBitmapPtrListCompactValidated(
		v,
		"SimOrder",
		validateSimOrder,
		isZeroSimOrder,
		SizeSimOrder,
	)
}
