package internal

import (
	"os"
	"testing"
)

func TestRenameContract(t *testing.T) {
	goMod, err := os.ReadFile("../go.mod")
	if err != nil {
		t.Fatalf("read go.mod: %v", err)
	}
	mainGo, err := os.ReadFile("../main.go")
	if err != nil {
		t.Fatalf("read main.go: %v", err)
	}
	readme, err := os.ReadFile("../README.md")
	if err != nil {
		t.Fatalf("read README.md: %v", err)
	}
	changelog, err := os.ReadFile("../CHANGELOG.md")
	if err != nil {
		t.Fatalf("read CHANGELOG.md: %v", err)
	}
	schema, err := os.ReadFile("../aaa.sb")
	if err != nil {
		t.Fatalf("read aaa.sb: %v", err)
	}
	protocol, err := os.ReadFile("../PROTOCOL.md")
	if err != nil {
		t.Fatalf("read PROTOCOL.md: %v", err)
	}
	if _, err := os.Stat("../go/sb/rt"); !os.IsNotExist(err) {
		t.Fatalf("go/sb/rt should not exist, err=%v", err)
	}
	runtimeGo, err := os.ReadFile("../go/sb/runtime.go")
	if err != nil {
		t.Fatalf("read go/sb/runtime.go: %v", err)
	}
	cross, err := os.ReadFile("../go/sb/cross_consistency_test.go")
	if err != nil {
		t.Fatalf("read go/sb/cross_consistency_test.go: %v", err)
	}
	demoGoDoc, err := os.ReadFile("../demo/go/sb/DOC.md")
	if err != nil {
		t.Fatalf("read demo/go/sb/DOC.md: %v", err)
	}
	demoGoAPI, err := os.ReadFile("../demo/go/sb/api._.go")
	if err != nil {
		t.Fatalf("read demo/go/sb/api._.go: %v", err)
	}
	demoTsSmoke, err := os.ReadFile("../demo/ts/sb/rpc_smoke.test.ts")
	if err != nil {
		t.Fatalf("read demo/ts/sb/rpc_smoke.test.ts: %v", err)
	}

	assertContains(t, string(goMod), "module sb")
	assertNotContains(t, string(goMod), "module simple-bin")
	assertContains(t, string(mainGo), "\"sb/internal\"")
	assertNotContains(t, string(mainGo), "\"simple-bin/internal\"")
	assertContains(t, string(readme), "# sb")
	assertContains(t, string(readme), "`sb/internal`")
	assertNotContains(t, string(readme), "# simple-bin")
	assertNotContains(t, string(readme), "`simple-bin/internal`")
	assertContains(t, string(readme), "go build -o sb")
	assertContains(t, string(readme), "../sb -go")
	assertContains(t, string(changelog), "# Changelog")
	assertContains(t, string(schema), "get_count(page u8) => u8")
	assertContains(t, string(protocol), "# sb 协议规范")
	assertNotContains(t, string(protocol), "# simple-bin 协议规范")
	assertContains(t, string(runtimeGo), "package sb")
	assertNotContains(t, string(cross), "simple-bin/go/sb/rt")
	assertNotContains(t, string(cross), "sb/go/sb/rt")
	assertContains(t, string(demoGoDoc), "\"your_project/sb\"")
	assertNotContains(t, string(demoGoDoc), "\"your_project/go/sb\"")
	assertNotContains(t, string(demoGoAPI), "simple-bin/go/sb/rt")
	assertNotContains(t, string(demoGoAPI), "sb/go/sb/rt")
	assertContains(t, string(demoGoAPI), "Code generated by sb generator")
	assertNotContains(t, string(demoGoAPI), "sb/go/sb/v2")
	assertContains(t, string(demoTsSmoke), "process.env.SB_BASE_URL")
	assertNotContains(t, string(demoTsSmoke), "process.env.SIMPLE_BIN_BASE_URL")
}
