package internal

import (
	"os"
	"testing"
)

func TestRenameContract(t *testing.T) {
	goMod, err := os.ReadFile("../go.mod")
	if err != nil {
		t.Fatalf("read go.mod: %v", err)
	}
	mainGo, err := os.ReadFile("../main.go")
	if err != nil {
		t.Fatalf("read main.go: %v", err)
	}
	readme, err := os.ReadFile("../README.md")
	if err != nil {
		t.Fatalf("read README.md: %v", err)
	}
	implementation, err := os.ReadFile("../IMPLEMENTATION.md")
	if err != nil {
		t.Fatalf("read IMPLEMENTATION.md: %v", err)
	}
	changelog, err := os.ReadFile("../CHANGELOG.md")
	if err != nil {
		t.Fatalf("read CHANGELOG.md: %v", err)
	}
	if _, err := os.Stat("../aaa.sb"); !os.IsNotExist(err) {
		t.Fatalf("aaa.sb should not exist in repo root, err=%v", err)
	}
	if _, err := os.Stat("../go"); !os.IsNotExist(err) {
		t.Fatalf("go should not exist in repo root, err=%v", err)
	}
	if _, err := os.Stat("../ts"); !os.IsNotExist(err) {
		t.Fatalf("ts should not exist in repo root, err=%v", err)
	}
	if _, err := os.Stat("../demo/go"); !os.IsNotExist(err) {
		t.Fatalf("demo/go should not exist, err=%v", err)
	}
	if _, err := os.Stat("../demo/ts"); !os.IsNotExist(err) {
		t.Fatalf("demo/ts should not exist, err=%v", err)
	}
	schema, err := os.ReadFile("../demo/all_rules.sb")
	if err != nil {
		t.Fatalf("read demo/all_rules.sb: %v", err)
	}
	demoReadme, err := os.ReadFile("../demo/README.md")
	if err != nil {
		t.Fatalf("read demo/README.md: %v", err)
	}
	protocol, err := os.ReadFile("../PROTOCOL.md")
	if err != nil {
		t.Fatalf("read PROTOCOL.md: %v", err)
	}
	if _, err := os.Stat("../fixtures/go/sb/rt"); !os.IsNotExist(err) {
		t.Fatalf("fixtures/go/sb/rt should not exist, err=%v", err)
	}
	runtimeGo, err := os.ReadFile("../fixtures/go/sb/runtime.go")
	if err != nil {
		t.Fatalf("read fixtures/go/sb/runtime.go: %v", err)
	}
	fixtureGoDoc, err := os.ReadFile("../fixtures/go/sb/DOC.md")
	if err != nil {
		t.Fatalf("read fixtures/go/sb/DOC.md: %v", err)
	}
	fixtureGoAPI, err := os.ReadFile("../fixtures/go/sb/api._.go")
	if err != nil {
		t.Fatalf("read fixtures/go/sb/api._.go: %v", err)
	}
	fixtureTsSmoke, err := os.ReadFile("../fixtures/ts/sb/rpc_smoke.test.ts")
	if err != nil {
		t.Fatalf("read fixtures/ts/sb/rpc_smoke.test.ts: %v", err)
	}

	assertContains(t, string(goMod), "module sb")
	assertNotContains(t, string(goMod), "module simple-bin")
	assertContains(t, string(mainGo), "\"sb/internal\"")
	assertNotContains(t, string(mainGo), "\"simple-bin/internal\"")
	assertContains(t, string(readme), "# sb")
	assertContains(t, string(readme), "`sb/internal`")
	assertContains(t, string(readme), "[PROTOCOL.md](PROTOCOL.md)")
	assertContains(t, string(readme), "[IMPLEMENTATION.md](IMPLEMENTATION.md)")
	assertNotContains(t, string(readme), "# simple-bin")
	assertNotContains(t, string(readme), "`simple-bin/internal`")
	assertContains(t, string(readme), "go build -o sb")
	assertContains(t, string(readme), "./sb -go ./out/go -ts ./out/ts -tag bson,json ./demo/all_rules.sb")
	assertContains(t, string(changelog), "# Changelog")
	assertContains(t, string(schema), "single_ping() => nil")
	assertContains(t, string(schema), "service.get_info(id u32) => ExtendedInfo")
	assertContains(t, string(demoReadme), "# Demo Rules")
	assertContains(t, string(demoReadme), "all_rules.sb")
	assertContains(t, string(protocol), "# sb 协议规范")
	assertNotContains(t, string(protocol), "# simple-bin 协议规范")
	assertNotContains(t, string(protocol), "fixtures/go/sb/runtime.go")
	assertNotContains(t, string(protocol), "fixtures/ts/sb/type.ts")
	assertNotContains(t, string(protocol), "internal/tpl_go_render.go")
	assertNotContains(t, string(protocol), "cross_consistency_test.go")
	assertContains(t, string(runtimeGo), "package sb")
	assertContains(t, string(implementation), "# Implementation")
	assertContains(t, string(implementation), "PROTOCOL.md")
	assertContains(t, string(implementation), "demo/all_rules.sb")
	assertContains(t, string(implementation), "fixtures/go/sb/runtime.go")
	assertContains(t, string(implementation), "fixtures/ts/sb/type.ts")
	assertContains(t, string(implementation), "internal/tpl_go_*.go")
	assertContains(t, string(implementation), "internal/tpl_ts_*.go")
	assertContains(t, string(implementation), "internal/tpl_doc_*.go")
	assertContains(t, string(implementation), "fixtures/go/sb/cross_consistency_test.go")
	assertContains(t, string(implementation), "fixtures/ts/sb/cross_consistency.test.ts")
	assertContains(t, string(fixtureGoDoc), "\"your_project/sb\"")
	assertNotContains(t, string(fixtureGoDoc), "\"your_project/go/sb\"")
	assertNotContains(t, string(fixtureGoAPI), "simple-bin/go/sb/rt")
	assertNotContains(t, string(fixtureGoAPI), "sb/go/sb/rt")
	assertContains(t, string(fixtureGoAPI), "Code generated by sb generator")
	assertNotContains(t, string(fixtureGoAPI), "sb/go/sb/v2")
	assertContains(t, string(fixtureTsSmoke), "process.env.SB_BASE_URL")
	assertNotContains(t, string(fixtureTsSmoke), "process.env.SIMPLE_BIN_BASE_URL")
}
