package internal

func (g *GoGenerator) renderSchemaFile(schema *TplSchema) string {
	var w sourceWriter
	w.Line("package sb")
	w.Blank()
	w.Line("import (")
	w.Line("\t\"bytes\"")
	w.Line("\t\"fmt\"")
	w.Line("\t\"math\"")
	w.Line("\t\"slices\"")
	w.Line("")
	w.Line(")")
	w.Blank()
	w.Line("// Code generated by sb generator. DO NOT EDIT.")
	w.Line("var _ = slices.Equal[[]int, int]")
	w.Line("var _ = HeaderSize")
	w.Blank()
	g.renderSharedHelpers(&w)
	for _, enum := range schema.Enums {
		w.Blank()
		g.renderEnum(&w, enum)
	}
	for _, st := range schema.Structs {
		w.Blank()
		g.renderStruct(&w, st)
	}
	return w.String()
}
