package internal

func renderGoRuntimeSource() string {
	var w sourceWriter
	w.Line("package sb")
	w.Blank()
	w.Line("import (")
	w.Line("\t\"bytes\"")
	w.Line("\t\"encoding/binary\"")
	w.Line("\t\"fmt\"")
	w.Line("\t\"math\"")
	w.Line("\t\"slices\"")
	w.Line(")")
	w.Blank()
	w.Line("type Setter func(*bytes.Buffer) error")
	w.Line("type Getter func(*bytes.Buffer) error")
	w.Blank()
	w.Line("func SetAll(buf *bytes.Buffer, args ...Setter) error {")
	w.Line("\tfor i, arg := range args {")
	w.Line("\t\tif arg == nil { return fmt.Errorf(\"SetAll arg[%d] is nil\", i) }")
	w.Line("\t\tif err := arg(buf); err != nil { return err }")
	w.Line("\t}")
	w.Line("\treturn nil")
	w.Line("}")
	w.Blank()
	w.Line("func GetAll(buf *bytes.Buffer, args ...Getter) error {")
	w.Line("\tfor i, arg := range args {")
	w.Line("\t\tif arg == nil { return fmt.Errorf(\"GetAll arg[%d] is nil\", i) }")
	w.Line("\t\tif err := arg(buf); err != nil { return err }")
	w.Line("\t}")
	w.Line("\treturn nil")
	w.Line("}")
	w.Blank()
	w.Line("// Helpers")
	w.Line("func getList[T any, L ~[]T](buf *bytes.Buffer, getItem func(*bytes.Buffer) (T, error)) (L, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\tlist := make([]T, count)")
	w.Line("\tfor i := range list {")
	w.Line("\t\tif list[i], err = getItem(buf); err != nil { return nil, err }")
	w.Line("\t}")
	w.Line("\treturn L(list), nil")
	w.Line("}")
	w.Blank()
	w.Line("func setList[T any](buf *bytes.Buffer, list []T, setItem func(*bytes.Buffer, T) error) error {")
	w.Line("\tif len(list) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tif err := SetU16(buf, uint16(len(list))); err != nil { return err }")
	w.Line("\tfor _, item := range list {")
	w.Line("\t\tif err := setItem(buf, item); err != nil { return err }")
	w.Line("\t}")
	w.Line("\treturn nil")
	w.Line("}")
	w.Blank()
	w.Line("func GetBit(bits []byte, i uint8) bool {")
	w.Line("\tif int(i/8) >= len(bits) { return false }")
	w.Line("\treturn (bits[i/8] & (1 << (i % 8))) != 0")
	w.Line("}")
	w.Blank()
	w.Line("func SetBit(bits []byte, i uint8, v bool) {")
	w.Line("\tif int(i/8) >= len(bits) { return }")
	w.Line("\tif v { bits[i/8] |= (1 << (i % 8)) } else { bits[i/8] &= ^(1 << (i % 8)) }")
	w.Line("}")
	w.Blank()
	w.Line("// Bool")
	w.Line("type Bool bool")
	w.Line("func GetBool(buf *bytes.Buffer) (bool, error) {")
	w.Line("\tb, err := buf.ReadByte()")
	w.Line("\treturn b == 1, err")
	w.Line("}")
	w.Line("func SetBool(buf *bytes.Buffer, v bool) error {")
	w.Line("\tif v { return buf.WriteByte(1) }")
	w.Line("\treturn buf.WriteByte(0)")
	w.Line("}")
	w.Line("func EqBool(a, b bool) bool { return a == b }")
	w.Blank()
	w.Line("type BoolList []bool")
	w.Line("func GetBoolList(buf *bytes.Buffer) ([]bool, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\tbitSize := (int(count) + 7) / 8")
	w.Line("\tif buf.Len() < bitSize { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\tbits := buf.Next(bitSize)")
	w.Line("\tbools := make([]bool, int(count))")
	w.Line("\tfor i := 0; i < int(count); i++ { bools[i] = GetBit(bits, uint8(i)) }")
	w.Line("\treturn bools, nil")
	w.Line("}")
	w.Line("func SetBoolList(buf *bytes.Buffer, v []bool) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tbits := make([]byte, (len(v)+7)/8)")
	w.Line("\tfor i, val := range v { SetBit(bits, uint8(i), val) }")
	w.Line("\t_, err := buf.Write(bits)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqBoolList(a, b []bool) bool { return slices.Equal(a, b) }")
	w.Blank()
	w.Line("// Primitives Macro")
	w.Line("type I8 int8")
	w.Line("func GetI8(buf *bytes.Buffer) (int8, error) {")
	w.Line("\tb, err := buf.ReadByte()")
	w.Line("\treturn int8(b), err")
	w.Line("}")
	w.Line("func SetI8(buf *bytes.Buffer, v int8) error {")
	w.Line("\treturn buf.WriteByte(uint8(v))")
	w.Line("}")
	w.Line("func EqI8(a, b int8) bool { return a == b }")
	w.Blank()
	w.Line("type I8List []int8")
	w.Line("func GetI8List(buf *bytes.Buffer) ([]int8, error) { return getList[int8, []int8](buf, GetI8) }")
	w.Line("func SetI8List(buf *bytes.Buffer, v []int8) error { return setList(buf, v, SetI8) }")
	w.Line("func EqI8List(a, b []int8) bool { return slices.Equal(a, b) }")
	w.Line("type U8 uint8")
	w.Line("func GetU8(buf *bytes.Buffer) (uint8, error) {")
	w.Line("\tb, err := buf.ReadByte()")
	w.Line("\treturn uint8(b), err")
	w.Line("}")
	w.Line("func SetU8(buf *bytes.Buffer, v uint8) error {")
	w.Line("\treturn buf.WriteByte(uint8(v))")
	w.Line("}")
	w.Line("func EqU8(a, b uint8) bool { return a == b }")
	w.Blank()
	w.Line("type U8List []uint8")
	w.Line("func GetU8List(buf *bytes.Buffer) ([]uint8, error) { return getList[uint8, []uint8](buf, GetU8) }")
	w.Line("func SetU8List(buf *bytes.Buffer, v []uint8) error { return setList(buf, v, SetU8) }")
	w.Line("func EqU8List(a, b []uint8) bool { return slices.Equal(a, b) }")
	w.Line("type I16 int16")
	w.Line("func GetI16(buf *bytes.Buffer) (int16, error) {")
	w.Line("\tvar b [2]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn int16(binary.LittleEndian.Uint16(b[:])), nil")
	w.Line("}")
	w.Line("func SetI16(buf *bytes.Buffer, v int16) error {")
	w.Line("\tvar b [2]byte")
	w.Line("\tbinary.LittleEndian.PutUint16(b[:], uint16(v))")
	w.Line("\t_, err := buf.Write(b[:])")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqI16(a, b int16) bool { return a == b }")
	w.Blank()
	w.Line("type I16List []int16")
	w.Line("func GetI16List(buf *bytes.Buffer) ([]int16, error) { return getList[int16, []int16](buf, GetI16) }")
	w.Line("func SetI16List(buf *bytes.Buffer, v []int16) error { return setList(buf, v, SetI16) }")
	w.Line("func EqI16List(a, b []int16) bool { return slices.Equal(a, b) }")
	w.Line("type U16 uint16")
	w.Line("func GetU16(buf *bytes.Buffer) (uint16, error) {")
	w.Line("\tvar b [2]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn uint16(binary.LittleEndian.Uint16(b[:])), nil")
	w.Line("}")
	w.Line("func SetU16(buf *bytes.Buffer, v uint16) error {")
	w.Line("\tvar b [2]byte")
	w.Line("\tbinary.LittleEndian.PutUint16(b[:], uint16(v))")
	w.Line("\t_, err := buf.Write(b[:])")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqU16(a, b uint16) bool { return a == b }")
	w.Blank()
	w.Line("type U16List []uint16")
	w.Line("func GetU16List(buf *bytes.Buffer) ([]uint16, error) { return getList[uint16, []uint16](buf, GetU16) }")
	w.Line("func SetU16List(buf *bytes.Buffer, v []uint16) error { return setList(buf, v, SetU16) }")
	w.Line("func EqU16List(a, b []uint16) bool { return slices.Equal(a, b) }")
	w.Line("type I32 int32")
	w.Line("func GetI32(buf *bytes.Buffer) (int32, error) {")
	w.Line("\tvar b [4]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn int32(binary.LittleEndian.Uint32(b[:])), nil")
	w.Line("}")
	w.Line("func SetI32(buf *bytes.Buffer, v int32) error {")
	w.Line("\tvar b [4]byte")
	w.Line("\tbinary.LittleEndian.PutUint32(b[:], uint32(v))")
	w.Line("\t_, err := buf.Write(b[:])")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqI32(a, b int32) bool { return a == b }")
	w.Blank()
	w.Line("type I32List []int32")
	w.Line("func GetI32List(buf *bytes.Buffer) ([]int32, error) { return getList[int32, []int32](buf, GetI32) }")
	w.Line("func SetI32List(buf *bytes.Buffer, v []int32) error { return setList(buf, v, SetI32) }")
	w.Line("func EqI32List(a, b []int32) bool { return slices.Equal(a, b) }")
	w.Line("type U32 uint32")
	w.Line("func GetU32(buf *bytes.Buffer) (uint32, error) {")
	w.Line("\tvar b [4]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn uint32(binary.LittleEndian.Uint32(b[:])), nil")
	w.Line("}")
	w.Line("func SetU32(buf *bytes.Buffer, v uint32) error {")
	w.Line("\tvar b [4]byte")
	w.Line("\tbinary.LittleEndian.PutUint32(b[:], uint32(v))")
	w.Line("\t_, err := buf.Write(b[:])")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqU32(a, b uint32) bool { return a == b }")
	w.Blank()
	w.Line("type U32List []uint32")
	w.Line("func GetU32List(buf *bytes.Buffer) ([]uint32, error) { return getList[uint32, []uint32](buf, GetU32) }")
	w.Line("func SetU32List(buf *bytes.Buffer, v []uint32) error { return setList(buf, v, SetU32) }")
	w.Line("func EqU32List(a, b []uint32) bool { return slices.Equal(a, b) }")
	w.Line("type I64 int64")
	w.Line("func GetI64(buf *bytes.Buffer) (int64, error) {")
	w.Line("\tvar b [8]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn int64(binary.LittleEndian.Uint64(b[:])), nil")
	w.Line("}")
	w.Line("func SetI64(buf *bytes.Buffer, v int64) error {")
	w.Line("\tvar b [8]byte")
	w.Line("\tbinary.LittleEndian.PutUint64(b[:], uint64(v))")
	w.Line("\t_, err := buf.Write(b[:])")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqI64(a, b int64) bool { return a == b }")
	w.Blank()
	w.Line("type I64List []int64")
	w.Line("func GetI64List(buf *bytes.Buffer) ([]int64, error) { return getList[int64, []int64](buf, GetI64) }")
	w.Line("func SetI64List(buf *bytes.Buffer, v []int64) error { return setList(buf, v, SetI64) }")
	w.Line("func EqI64List(a, b []int64) bool { return slices.Equal(a, b) }")
	w.Line("type U64 uint64")
	w.Line("func GetU64(buf *bytes.Buffer) (uint64, error) {")
	w.Line("\tvar b [8]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn uint64(binary.LittleEndian.Uint64(b[:])), nil")
	w.Line("}")
	w.Line("func SetU64(buf *bytes.Buffer, v uint64) error {")
	w.Line("\tvar b [8]byte")
	w.Line("\tbinary.LittleEndian.PutUint64(b[:], uint64(v))")
	w.Line("\t_, err := buf.Write(b[:])")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqU64(a, b uint64) bool { return a == b }")
	w.Blank()
	w.Line("type U64List []uint64")
	w.Line("func GetU64List(buf *bytes.Buffer) ([]uint64, error) { return getList[uint64, []uint64](buf, GetU64) }")
	w.Line("func SetU64List(buf *bytes.Buffer, v []uint64) error { return setList(buf, v, SetU64) }")
	w.Line("func EqU64List(a, b []uint64) bool { return slices.Equal(a, b) }")
	w.Line("type F32 float32")
	w.Line("func GetF32(buf *bytes.Buffer) (float32, error) {")
	w.Line("\tvar b [4]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn math.Float32frombits(binary.LittleEndian.Uint32(b[:])), nil")
	w.Line("}")
	w.Line("func SetF32(buf *bytes.Buffer, v float32) error {")
	w.Line("\tvar b [4]byte")
	w.Line("\tbinary.LittleEndian.PutUint32(b[:], math.Float32bits(v))")
	w.Line("\t_, err := buf.Write(b[:])")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqF32(a, b float32) bool { return math.Abs(float64(a-b)) < 1e-6 }")
	w.Blank()
	w.Line("type F32List []float32")
	w.Line("func GetF32List(buf *bytes.Buffer) ([]float32, error) { return getList[float32, []float32](buf, GetF32) }")
	w.Line("func SetF32List(buf *bytes.Buffer, v []float32) error { return setList(buf, v, SetF32) }")
	w.Line("func EqF32List(a, b []float32) bool { return slices.Equal(a, b) }")
	w.Line("type F64 float64")
	w.Line("func GetF64(buf *bytes.Buffer) (float64, error) {")
	w.Line("\tvar b [8]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn math.Float64frombits(binary.LittleEndian.Uint64(b[:])), nil")
	w.Line("}")
	w.Line("func SetF64(buf *bytes.Buffer, v float64) error {")
	w.Line("\tvar b [8]byte")
	w.Line("\tbinary.LittleEndian.PutUint64(b[:], math.Float64bits(v))")
	w.Line("\t_, err := buf.Write(b[:])")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqF64(a, b float64) bool { return math.Abs(float64(a-b)) < 1e-9 }")
	w.Blank()
	w.Line("type F64List []float64")
	w.Line("func GetF64List(buf *bytes.Buffer) ([]float64, error) { return getList[float64, []float64](buf, GetF64) }")
	w.Line("func SetF64List(buf *bytes.Buffer, v []float64) error { return setList(buf, v, SetF64) }")
	w.Line("func EqF64List(a, b []float64) bool { return slices.Equal(a, b) }")
	w.Blank()
	w.Blank()
	w.Line("// Bin")
	w.Line("type Bin []byte")
	w.Line("func GetBinView(buf *bytes.Buffer) ([]byte, error) {")
	w.Line("\tl, err := GetU32(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\tif uint64(buf.Len()) < uint64(l) { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\treturn buf.Next(int(l)), nil")
	w.Line("}")
	w.Line("func GetBin(buf *bytes.Buffer) ([]byte, error) {")
	w.Line("\tres, err := GetBinView(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\treturn bytes.Clone(res), nil")
	w.Line("}")
	w.Line("func SetBin(buf *bytes.Buffer, v []byte) error {")
	w.Line("\tif uint64(len(v)) > uint64(^uint32(0)) { return fmt.Errorf(\"bin length exceeds uint32 max\") }")
	w.Line("\tif err := SetU32(buf, uint32(len(v))); err != nil { return err }")
	w.Line("\t_, err := buf.Write(v)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqBin(a, b []byte) bool { return bytes.Equal(a, b) }")
	w.Blank()
	w.Line("type BinList [][]byte")
	w.Line("func GetBinList(buf *bytes.Buffer) ([][]byte, error) { return getList[[]byte, [][]byte](buf, GetBin) }")
	w.Line("func SetBinList(buf *bytes.Buffer, v [][]byte) error { return setList(buf, v, SetBin) }")
	w.Line("func EqBinList(a, b [][]byte) bool { return slices.EqualFunc(a, b, bytes.Equal) }")
	w.Blank()
	w.Line("// Text")
	w.Line("type Text string")
	w.Line("func GetText(buf *bytes.Buffer) (string, error) {")
	w.Line("\tl, err := GetU16(buf)")
	w.Line("\tif err != nil { return \"\", err }")
	w.Line("\tif buf.Len() < int(l) { return \"\", fmt.Errorf(\"not enough data\") }")
	w.Line("\treturn string(buf.Next(int(l))), nil")
	w.Line("}")
	w.Line("func SetText(buf *bytes.Buffer, v string) error {")
	w.Line("\tdata := []byte(v)")
	w.Line("\tif len(data) > 65535 { return fmt.Errorf(\"text length exceeds uint16 max\") }")
	w.Line("\tif err := SetU16(buf, uint16(len(data))); err != nil { return err }")
	w.Line("\t_, err := buf.Write(data)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqText(a, b string) bool { return a == b }")
	w.Blank()
	w.Line("type TextList []string")
	w.Line("func GetTextList(buf *bytes.Buffer) ([]string, error) { return getList[string, []string](buf, GetText) }")
	w.Line("func SetTextList(buf *bytes.Buffer, v []string) error { return setList(buf, v, SetText) }")
	w.Line("func EqTextList(a, b []string) bool { return slices.Equal(a, b) }")
	return w.String()
}
