package internal

func (g *GoGenerator) renderStructListBodyHelpers(w *sourceWriter, st TplStruct) {
	structName := PascalCase(st.Name)
	getFunc := g.structGetName(st.Name)
	sizeFunc := g.structSizeName(st.Name)
	setValidatedFunc := g.structSetValidatedName(st.Name)
	w.Linef("func get%sListBody(buf *bytes.Buffer, state uint8) ([]*%s, error) {", structName, structName)
	w.Linef("\treturn get%sListBodyReuse(buf, state, nil)", structName)
	w.Line("}")
	w.Blank()
	w.Linef("func get%sListBodyReuse(buf *bytes.Buffer, state uint8, dst []*%s) ([]*%s, error) {", structName, structName, structName)
	w.Linef("\treturn GetDefaultPtrListInto(buf, state, dst, %s, %s)", g.structDefaultName(structName), getFunc)
	w.Line("}")
	w.Blank()
	w.Linef("func set%sListBody(buf *bytes.Buffer, state uint8, v []*%s) error {", structName, structName)
	w.Line("\treturn SetDefaultPtrList(")
	w.Line("\t\tbuf,")
	w.Line("\t\tstate,")
	w.Line("\t\tv,")
	w.Linef("\t\t%q,", structName)
	w.Linef("\t\t%s,", g.structValidateName(structName))
	w.Linef("\t\t%s,", g.structIsZeroName(structName))
	w.Linef("\t\t%s,", sizeFunc)
	w.Linef("\t\t%s,", setValidatedFunc)
	w.Line("\t)")
	w.Line("}")
	w.Blank()
	w.Linef("func size%sListBody(v []*%s) (int, error) {", structName, structName)
	w.Line("\treturn SizeDefaultPtrList(")
	w.Line("\t\tv,")
	w.Linef("\t\t%q,", structName)
	w.Linef("\t\t%s,", g.structValidateName(structName))
	w.Linef("\t\t%s,", g.structIsZeroName(structName))
	w.Linef("\t\t%s,", sizeFunc)
	w.Line("\t)")
	w.Line("}")
}
