package internal

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGoGeneratorWritesSchemaFile(t *testing.T) {
	tmpDir := t.TempDir()
	g := NewGoGenerator(Config{GoDir: tmpDir, GoTag: "json"})

	schema := &TplSchema{
		Enums: []TplEnum{
			{
				Name: "sim_operator",
				Children: []TplEnumChild{
					{ID: 2, Name: "zz"},
					{ID: 3, Name: "lt"},
				},
			},
		},
		Structs: []TplStruct{
			{
				Name: "sim_info",
				Fields: []TplStructField{
					{Name: "title", Type: TplType{Name: "text", Kind: TplKindBase}},
				},
			},
			{
				Name: "sim",
				Fields: []TplStructField{
					{Name: "id", Type: TplType{Name: "u32", Kind: TplKindBase}, Tag: "_id"},
					{Name: "name", Type: TplType{Name: "text", Kind: TplKindBase}},
					{Name: "operator", Type: TplType{Name: "sim_operator", Kind: TplKindEnum}},
					{Name: "ok", Type: TplType{Name: "bool", Kind: TplKindBase}},
					{Name: "tags", Type: TplType{Name: "u32", Kind: TplKindBase, IsList: true}},
					{Name: "titles", Type: TplType{Name: "text", Kind: TplKindBase, IsList: true}},
					{Name: "infos", Type: TplType{Name: "sim_info", Kind: TplKindStruct, IsList: true}},
				},
			},
		},
		Apis: []TplApi{
			{
				Name: "user.get_count",
				Args: []TplApiArg{
					{Name: "page", Type: TplType{Name: "u8", Kind: TplKindBase}},
				},
				Result: TplType{Name: "u8", Kind: TplKindBase},
			},
		},
	}

	if err := g.Generate(schema); err != nil {
		t.Fatalf("generate go failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(tmpDir, "sb", "schema.gen.go"))
	if err != nil {
		t.Fatalf("read schema.gen.go failed: %v", err)
	}
	text := string(content)

	runtimeContent, err := os.ReadFile(filepath.Join(tmpDir, "sb", "runtime.go"))
	if err != nil {
		t.Fatalf("read runtime.go failed: %v", err)
	}
	runtimeText := string(runtimeContent)

	assertContains(t, text, "package sb")
	assertContains(t, runtimeText, "package sb")
	assertContains(t, runtimeText, "func HeaderSize(bitCount int) int {")
	assertContains(t, text, "// Code generated by sb generator. DO NOT EDIT.")
	assertNotContains(t, text, "// Code generated by simple-bin generator. DO NOT EDIT.")
	assertNotContains(t, text, "rt \"simple-bin/go/sb/rt\"")
	assertNotContains(t, text, "rt \"sb/go/sb/rt\"")
	assertNotContains(t, text, "rt.")
	assertContains(t, text, "func isSimOperator(v SimOperator) bool {")
	assertContains(t, text, "func defaultSimOperator() SimOperator { return SimOperatorZz }")
	assertContains(t, text, "func normalizeSimOperator(v SimOperator) SimOperator {")
	assertContains(t, text, "func isAssignableSimOperator(v SimOperator) bool {")
	assertContains(t, text, "var simOperatorMeta = DefineEnum[SimOperator](")
	assertContains(t, text, "return GetEnumListInto(simOperatorMeta, buf, state, dst)")
	assertContains(t, text, "return SetEnumList(simOperatorMeta, buf, state, v)")
	assertContains(t, text, "return SizeEnumList(simOperatorMeta, v)")
	assertNotContains(t, text, "func sizeSimOperatorListItem(item SimOperator) (int, error) {")
	assertNotContains(t, text, "func getSimOperatorListItem(buf *bytes.Buffer) (SimOperator, error) {")
	assertNotContains(t, text, "func setSimOperatorListItem(buf *bytes.Buffer, item SimOperator) error {")
	assertContains(t, text, "var simMeta = DefineStruct[Sim](")
	assertContains(t, text, "func isZeroSim(s *Sim) bool { return IsZeroStruct(simMeta, s) }")
	assertContains(t, text, "func validateSim(s *Sim) error { return ValidateStruct(simMeta, s) }")
	assertContains(t, text, "func EqSim(a, b *Sim) bool { return EqStruct(simMeta, a, b) }")
	assertContains(t, text, "func SetSim(buf *bytes.Buffer, s *Sim) error {")
	assertContains(t, text, "func GetSim(buf *bytes.Buffer, s *Sim) error {")
	assertContains(t, text, "var simHeaderWidths = [...]uint8{1, 2, 1, 1, 2, 2, 2}")
	assertContains(t, text, "if err := ReadHeader(header, simHeaderWidths[:], headerStates[:], \"Sim header\"); err != nil { return err }")
	assertContains(t, text, "if err := WriteHeader(headerData[:], simHeaderWidths[:], headerStates[:]); err != nil { return fmt.Errorf(\"SetSim write header: %w\", err) }")
	assertContains(t, text, "func isZeroSim(s *Sim) bool {")
	assertContains(t, text, "func getSimInfoListBody(buf *bytes.Buffer, state uint8) ([]*SimInfo, error) {")
	assertContains(t, text, "func getSimInfoListBodyReuse(buf *bytes.Buffer, state uint8, dst []*SimInfo) ([]*SimInfo, error) {")
	assertContains(t, text, "return GetDefaultPtrListInto(buf, state, dst, defaultSimInfo, GetSimInfo)")
	assertContains(t, text, "return SetDefaultPtrList(")
	assertContains(t, text, "\"SimInfo\",")
	assertContains(t, text, "return SizeDefaultPtrList(")
	assertContains(t, text, "fieldSizeTitles, err := SizeTextList(s.Titles)")
	assertContains(t, text, "fieldSizeTags, err := SizeZeroList(s.Tags, 4)")
	assertContains(t, text, "valueTags, err := GetZeroListInto(buf, tagsState, reuseTags, GetU32)")
	assertContains(t, text, "if err := SetZeroList(buf, tagsState, s.Tags, 4, SetU32); err != nil { return fmt.Errorf(\"SetSim Tags: %w\", err) }")
	assertNotContains(t, text, "func IsSimOperator(v SimOperator) bool {")
	assertNotContains(t, text, "func DefaultSimOperator()")
	assertNotContains(t, text, "func ValidateSimInfo(")
	assertContains(t, text, "`json:\"_id\"`")

	apiContent, err := os.ReadFile(filepath.Join(tmpDir, "sb", "api._.go"))
	if err != nil {
		t.Fatalf("read api._.go failed: %v", err)
	}
	apiText := string(apiContent)
	assertNotContains(t, apiText, "rt \"simple-bin/go/sb/rt\"")
	assertNotContains(t, apiText, "rt \"sb/go/sb/rt\"")
	assertNotContains(t, apiText, "rt.")
	assertContains(t, apiText, "// Code generated by sb generator. DO NOT EDIT.")
	assertNotContains(t, apiText, "// Code generated by simple-bin generator. DO NOT EDIT.")
	assertContains(t, apiText, "func UserGetCountHandler(w http.ResponseWriter, r *http.Request) {")
	assertContains(t, apiText, "var page uint8")
	assertContains(t, apiText, "value, err := GetU8(buf)")
	assertContains(t, apiText, "page = value")
	assertContains(t, apiText, "if err := SetU8(&body, result); err != nil { w.WriteHeader(http.StatusInternalServerError); return }")
	assertContains(t, apiText, "func httpStatusFromRPC(status RpcErrCode) int {")
	assertContains(t, apiText, "w.WriteHeader(httpStatusFromRPC(status)); return false")
	assertNotContains(t, apiText, "type ApiUserGetCountReq struct {")
	assertNotContains(t, apiText, "type ApiUserGetCountResp struct {")
	assertNotContains(t, apiText, "readApiUserGetCountReq")
	assertNotContains(t, apiText, "setApiUserGetCountResp")
	assertContains(t, apiText, "var _ = slices.Equal[[]int, int]")

	rpcContent, err := os.ReadFile(filepath.Join(tmpDir, "sb", "rpc.go"))
	if err != nil {
		t.Fatalf("read rpc.go failed: %v", err)
	}
	rpcText := string(rpcContent)
	assertNotContains(t, rpcText, "rt \"simple-bin/go/sb/rt\"")
	assertNotContains(t, rpcText, "rt \"sb/go/sb/rt\"")
	assertNotContains(t, rpcText, "rt.")
	assertContains(t, rpcText, "func CallUserGetCount(c *Client, ctx context.Context, page uint8) (result uint8, errCode RpcErrCode) {")
	assertContains(t, rpcText, "if err := SetU8(&buf, page); err != nil {")
	assertContains(t, rpcText, "value, err := GetU8(respBuf)")
	assertContains(t, rpcText, "closeErr := resp.Body.Close()")
	assertContains(t, rpcText, "if isTimeout(readErr) || isTimeout(closeErr) || reqCtx.Err() == context.DeadlineExceeded || ctx.Err() == context.DeadlineExceeded {")
	assertNotContains(t, rpcText, "resp, err = httpClient.Do(req)\n\t\tcancel()")
	assertNotContains(t, rpcText, "ApiUserGetCountReq")
	assertNotContains(t, rpcText, "readApiUserGetCountResp")

	stubContent, err := os.ReadFile(filepath.Join(tmpDir, "sb", "api.user.get_count.go"))
	if err != nil {
		t.Fatalf("read api.user.get_count.go failed: %v", err)
	}
	stubText := string(stubContent)
	assertContains(t, stubText, "func user_get_count(ctx context.Context, page uint8) (result uint8, errCode RpcErrCode) {")
}
