package internal

func (g *GoGenerator) renderEnum(w *sourceWriter, enum TplEnum) {
	enumName := PascalCase(enum.Name)
	defaultName := enumName + PascalCase(enum.Children[0].Name)
	defaultFunc := g.enumDefaultName(enumName)
	isFunc := g.enumIsName(enumName)
	normalizeFunc := g.enumNormalizeName(enumName)
	isDefaultFunc := g.enumIsDefaultName(enumName)
	isAssignableFunc := g.enumIsAssignableName(enumName)
	eqValueFunc := g.enumEqValueName(enumName)
	eqListFunc := g.enumEqListName(enumName)
	w.WriteLineCommentWithHead("// ", enumName+" ", enum.Note)
	w.Linef("type %s uint8", enumName)
	w.Blank()
	w.Line("const (")
	for _, child := range enum.Children {
		w.WriteLineComment("\t// ", child.Note)
		w.Linef("\t%s%s %s = %d", enumName, PascalCase(child.Name), enumName, child.ID)
	}
	w.Line(")")
	w.Blank()
	w.Linef("var %sMeta = DefineEnum[%s](", CamelCase(enum.Name), enumName)
	w.Linef("\t%s,", defaultName)
	for _, child := range enum.Children {
		w.Linef("\t%s%s,", enumName, PascalCase(child.Name))
	}
	w.Line(")")
	w.Blank()
	w.Linef("func %s() %s { return %s }", defaultFunc, enumName, defaultName)
	w.Linef("func %s(v %s) bool { return IsEnum(%sMeta, v) }", isFunc, enumName, CamelCase(enum.Name))
	w.Linef("func %s(v %s) %s { return NormalizeEnum(%sMeta, v) }", normalizeFunc, enumName, enumName, CamelCase(enum.Name))
	w.Blank()
	w.Linef("func %s(v %s) bool { return IsDefaultEnum(%sMeta, v) }", isDefaultFunc, enumName, CamelCase(enum.Name))
	w.Linef("func %s(v %s) bool { return IsAssignableEnum(%sMeta, v) }", isAssignableFunc, enumName, CamelCase(enum.Name))
	w.Linef("func %s(a, b %s) bool { return EqEnumValue(%sMeta, a, b) }", eqValueFunc, enumName, CamelCase(enum.Name))
	w.Linef("func %s(a, b []%s) bool { return EqEnumList(%sMeta, a, b) }", eqListFunc, enumName, CamelCase(enum.Name))
	w.Blank()
	w.Linef("func get%sListBody(buf *bytes.Buffer, state uint8) ([]%s, error) {", enumName, enumName)
	w.Linef("\treturn get%sListBodyReuse(buf, state, nil)", enumName)
	w.Line("}")
	w.Blank()
	w.Linef("func get%sListBodyReuse(buf *bytes.Buffer, state uint8, dst []%s) ([]%s, error) {", enumName, enumName, enumName)
	w.Linef("\treturn GetEnumListInto(%sMeta, buf, state, dst)", CamelCase(enum.Name))
	w.Line("}")
	w.Blank()
	w.Linef("func set%sListBody(buf *bytes.Buffer, state uint8, v []%s) error {", enumName, enumName)
	w.Linef("\treturn SetEnumList(%sMeta, buf, state, v)", CamelCase(enum.Name))
	w.Line("}")
	w.Blank()
	w.Linef("func size%sListBody(v []%s) (int, error) {", enumName, enumName)
	w.Linef("\treturn SizeEnumList(%sMeta, v)", CamelCase(enum.Name))
	w.Line("}")
}
