package internal

func (g *GoGenerator) renderAPIMiddleware(w *sourceWriter) {
	w.Line("type Middleware func(http.HandlerFunc) http.HandlerFunc")
	w.Blank()
	w.Line("func composeMiddleware(mws ...Middleware) func(http.HandlerFunc) http.HandlerFunc {")
	w.Line("\treturn func(h http.HandlerFunc) http.HandlerFunc {")
	w.Line("\t\tfor i := len(mws) - 1; i >= 0; i-- { h = mws[i](h) }")
	w.Line("\t\treturn h")
	w.Line("\t}")
	w.Line("}")
	w.Blank()
	w.Line("func TimeoutMiddleware(timeout time.Duration) Middleware {")
	w.Line("\treturn func(h http.HandlerFunc) http.HandlerFunc {")
	w.Line("\t\tif timeout <= 0 { return h }")
	w.Line("\t\treturn func(w http.ResponseWriter, r *http.Request) {")
	w.Line("\t\t\tctx, cancel := context.WithTimeout(r.Context(), timeout)")
	w.Line("\t\t\tdefer cancel()")
	w.Line("\t\t\ttw := newTimeoutResponseWriter()")
	w.Line("\t\t\tdone := make(chan struct{})")
	w.Line("\t\t\tgo func() {")
	w.Line("\t\t\t\tdefer close(done)")
	w.Line("\t\t\t\th(tw, r.WithContext(ctx))")
	w.Line("\t\t\t}()")
	w.Line("\t\t\tselect {")
	w.Line("\t\t\tcase <-done:")
	w.Line("\t\t\t\tif ctx.Err() == context.DeadlineExceeded {")
	w.Line("\t\t\t\t\ttw.timeout()")
	w.Line("\t\t\t\t\tw.WriteHeader(http.StatusRequestTimeout)")
	w.Line("\t\t\t\t\treturn")
	w.Line("\t\t\t\t}")
	w.Line("\t\t\t\ttw.writeTo(w)")
	w.Line("\t\t\tcase <-ctx.Done():")
	w.Line("\t\t\t\ttw.timeout()")
	w.Line("\t\t\t\tif ctx.Err() == context.DeadlineExceeded {")
	w.Line("\t\t\t\t\tw.WriteHeader(http.StatusRequestTimeout)")
	w.Line("\t\t\t\t}")
	w.Line("\t\t\t}")
	w.Line("\t\t}")
	w.Line("\t}")
	w.Line("}")
	w.Blank()
	w.Line("type timeoutResponseWriter struct {")
	w.Line("\tmu sync.Mutex")
	w.Line("\theader http.Header")
	w.Line("\tcode int")
	w.Line("\twroteHeader bool")
	w.Line("\tbody bytes.Buffer")
	w.Line("\ttimedOut bool")
	w.Line("}")
	w.Blank()
	w.Line("func newTimeoutResponseWriter() *timeoutResponseWriter {")
	w.Line("\treturn &timeoutResponseWriter{header: make(http.Header)}")
	w.Line("}")
	w.Blank()
	w.Line("func (tw *timeoutResponseWriter) Header() http.Header { return tw.header }")
	w.Blank()
	w.Line("func (tw *timeoutResponseWriter) WriteHeader(statusCode int) {")
	w.Line("\ttw.mu.Lock()")
	w.Line("\tdefer tw.mu.Unlock()")
	w.Line("\tif tw.timedOut || tw.wroteHeader { return }")
	w.Line("\ttw.code = statusCode")
	w.Line("\ttw.wroteHeader = true")
	w.Line("}")
	w.Blank()
	w.Line("func (tw *timeoutResponseWriter) Write(data []byte) (int, error) {")
	w.Line("\ttw.mu.Lock()")
	w.Line("\tdefer tw.mu.Unlock()")
	w.Line("\tif tw.timedOut { return 0, http.ErrHandlerTimeout }")
	w.Line("\tif !tw.wroteHeader {")
	w.Line("\t\ttw.code = http.StatusOK")
	w.Line("\t\ttw.wroteHeader = true")
	w.Line("\t}")
	w.Line("\treturn tw.body.Write(data)")
	w.Line("}")
	w.Blank()
	w.Line("func (tw *timeoutResponseWriter) timeout() {")
	w.Line("\ttw.mu.Lock()")
	w.Line("\ttw.timedOut = true")
	w.Line("\ttw.mu.Unlock()")
	w.Line("}")
	w.Blank()
	w.Line("func (tw *timeoutResponseWriter) writeTo(w http.ResponseWriter) {")
	w.Line("\ttw.mu.Lock()")
	w.Line("\tif tw.timedOut {")
	w.Line("\t\ttw.mu.Unlock()")
	w.Line("\t\treturn")
	w.Line("\t}")
	w.Line("\theader := tw.header.Clone()")
	w.Line("\tcode := tw.code")
	w.Line("\twroteHeader := tw.wroteHeader")
	w.Line("\tbody := append([]byte(nil), tw.body.Bytes()...)")
	w.Line("\ttw.mu.Unlock()")
	w.Line("\tfor k, values := range header {")
	w.Line("\t\tfor _, value := range values {")
	w.Line("\t\t\tw.Header().Add(k, value)")
	w.Line("\t\t}")
	w.Line("\t}")
	w.Line("\tif !wroteHeader { code = http.StatusOK }")
	w.Line("\tw.WriteHeader(code)")
	w.Line("\tif len(body) == 0 { return }")
	w.Line("\t_, _ = w.Write(body)")
	w.Line("}")
}
