package internal

func renderTsRuntimeSource() string {
	var w sourceWriter
	w.Line("const _textEncoder = new TextEncoder();")
	w.Line("const _textDecoder = new TextDecoder();")
	w.Blank()
	w.Line("export const StateZero = 0;")
	w.Line("export const StateU8 = 1;")
	w.Line("export const StateU16 = 2;")
	w.Line("export const StateU24 = 3;")
	w.Blank()
	w.Line("export interface Buffer {")
	w.Line("    ensureCapacity: (needed: number) => void;")
	w.Line("    read: (byteLength: number) => [Uint8Array, Error | null];")
	w.Line("    write: (data: Uint8Array) => Error | null;")
	w.Line("    writeUnsafe: (data: Uint8Array) => void;")
	w.Line("    rewindWrite: (offset: number) => void;")
	w.Line("    readonly bytes: Uint8Array;")
	w.Line("    readonly view: DataView;")
	w.Line("    readonly len: number;")
	w.Line("    readonly readOffset: number;")
	w.Line("    readonly writeOffset: number;")
	w.Line("}")
	w.Blank()
	w.Line("type _BufferState = Buffer & {")
	w.Line("    _bytes: Uint8Array;")
	w.Line("    _view: DataView;")
	w.Line("    _readOffset: number;")
	w.Line("    _writeOffset: number;")
	w.Line("};")
	w.Line("type BufferCtor = new (bytes?: Uint8Array) => Buffer;")
	w.Blank()
	w.Line("function _BufferCtor(this: _BufferState, bytes?: Uint8Array): void {")
	w.Line("    if (bytes) {")
	w.Line("        this._bytes = bytes;")
	w.Line("        this._view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);")
	w.Line("        this._readOffset = 0;")
	w.Line("        this._writeOffset = bytes.byteLength;")
	w.Line("        return;")
	w.Line("    }")
	w.Line("    this._bytes = new Uint8Array(128);")
	w.Line("    this._view = new DataView(this._bytes.buffer);")
	w.Line("    this._readOffset = 0;")
	w.Line("    this._writeOffset = 0;")
	w.Line("}")
	w.Line("const _bufferProto = _BufferCtor.prototype as _BufferState;")
	w.Blank()
	w.Line("_bufferProto.ensureCapacity = function(this: _BufferState, needed: number): void {")
	w.Line("    const required = this._writeOffset + needed;")
	w.Line("    if (required <= this._bytes.length) return;")
	w.Line("    let newCapacity = this._bytes.length === 0 ? 128 : this._bytes.length;")
	w.Line("    while (newCapacity < required) newCapacity *= 2;")
	w.Line("    const next = new Uint8Array(newCapacity);")
	w.Line("    next.set(this._bytes.subarray(0, this._writeOffset));")
	w.Line("    this._bytes = next;")
	w.Line("    this._view = new DataView(next.buffer);")
	w.Line("};")
	w.Blank()
	w.Line("_bufferProto.read = function(this: _BufferState, byteLength: number): [Uint8Array, Error | null] {")
	w.Line("    if (byteLength < 0) return [new Uint8Array(0), new Error(`invalid read length ${byteLength}`)];")
	w.Line("    if (this._readOffset + byteLength > this._writeOffset) return [new Uint8Array(0), new Error(\"not enough data\")];")
	w.Line("    const slice = this._bytes.subarray(this._readOffset, this._readOffset + byteLength);")
	w.Line("    this._readOffset += byteLength;")
	w.Line("    return [slice, null];")
	w.Line("};")
	w.Blank()
	w.Line("_bufferProto.write = function(this: _BufferState, data: Uint8Array): Error | null {")
	w.Line("    this.ensureCapacity(data.byteLength);")
	w.Line("    this.writeUnsafe(data);")
	w.Line("    return null;")
	w.Line("};")
	w.Blank()
	w.Line("_bufferProto.writeUnsafe = function(this: _BufferState, data: Uint8Array): void {")
	w.Line("    this._bytes.set(data, this._writeOffset);")
	w.Line("    this._writeOffset += data.byteLength;")
	w.Line("};")
	w.Blank()
	w.Line("_bufferProto.rewindWrite = function(this: _BufferState, offset: number): void {")
	w.Line("    if (offset < 0) offset = 0;")
	w.Line("    if (offset > this._writeOffset) offset = this._writeOffset;")
	w.Line("    this._writeOffset = offset;")
	w.Line("    if (this._readOffset > this._writeOffset) this._readOffset = this._writeOffset;")
	w.Line("};")
	w.Blank()
	w.Line("Object.defineProperty(_bufferProto, \"bytes\", { get(this: _BufferState): Uint8Array { return this._bytes.subarray(0, this._writeOffset); } });")
	w.Line("Object.defineProperty(_bufferProto, \"view\", { get(this: _BufferState): DataView { return this._view; } });")
	w.Line("Object.defineProperty(_bufferProto, \"len\", { get(this: _BufferState): number { return this._writeOffset - this._readOffset; } });")
	w.Line("Object.defineProperty(_bufferProto, \"readOffset\", { get(this: _BufferState): number { return this._readOffset; } });")
	w.Line("Object.defineProperty(_bufferProto, \"writeOffset\", { get(this: _BufferState): number { return this._writeOffset; } });")
	w.Blank()
	w.Line("export const Buffer = _BufferCtor as unknown as BufferCtor;")
	w.Blank()
	w.Line("export type Err = Error | undefined;")
	w.Line("export const errU = (err: Error | null): Err => err === null ? undefined : err;")
	w.Line("export const resultU = <T>(value: T, err: Error | null): [T, Err] => err === null ? [value, undefined] : [value, err];")
	w.Blank()
	w.Line("export interface Serializable {")
	w.Line("    set: (buf: Buffer) => Err;")
	w.Line("}")
	w.Blank()
	w.Line("export interface Deserializable {")
	w.Line("    get: (buf: Buffer) => Err;")
	w.Line("}")
	w.Blank()
	w.Line("export const headerSize = (bitCount: number): number => bitCount <= 0 ? 0 : Math.floor((bitCount + 7) / 8);")
	w.Line("export const bitmapSize = (count: number): number => count <= 0 ? 0 : Math.floor((count + 7) / 8);")
	w.Line("export const itemHeaderSize = (count: number): number => count <= 0 ? 0 : Math.floor((count * 2 + 7) / 8);")
	w.Blank()
	w.Line("export interface BitWriter {")
	w.Line("    writeBit: (v: boolean) => void;")
	w.Line("    writeBits: (v: number, width: number) => Error | null;")
	w.Line("    readonly bitLen: number;")
	w.Line("    readonly bytes: Uint8Array;")
	w.Line("}")
	w.Blank()
	w.Line("type _BitWriterState = BitWriter & {")
	w.Line("    _data: Uint8Array;")
	w.Line("    _bitOffset: number;")
	w.Line("};")
	w.Line("type BitWriterCtor = new (bitCapacity: number) => BitWriter;")
	w.Blank()
	w.Line("function _BitWriterCtor(this: _BitWriterState, bitCapacity: number): void {")
	w.Line("    this._data = new Uint8Array(headerSize(bitCapacity));")
	w.Line("    this._bitOffset = 0;")
	w.Line("}")
	w.Line("const _bitWriterProto = _BitWriterCtor.prototype as _BitWriterState;")
	w.Blank()
	w.Line("const _bitWriterEnsureBits = function(this: _BitWriterState, width: number): void {")
	w.Line("    const requiredBits = this._bitOffset + width;")
	w.Line("    const requiredBytes = headerSize(requiredBits);")
	w.Line("    if (requiredBytes <= this._data.byteLength) return;")
	w.Line("    const next = new Uint8Array(requiredBytes);")
	w.Line("    next.set(this._data);")
	w.Line("    this._data = next;")
	w.Line("};")
	w.Blank()
	w.Line("_bitWriterProto.writeBit = function(this: _BitWriterState, v: boolean): void {")
	w.Line("    _bitWriterEnsureBits.call(this, 1);")
	w.Line("    const byteIndex = Math.floor(this._bitOffset / 8);")
	w.Line("    const bitIndex = 7 - (this._bitOffset % 8);")
	w.Line("    if (v) this._data[byteIndex] |= 1 << bitIndex;")
	w.Line("    this._bitOffset++;")
	w.Line("};")
	w.Blank()
	w.Line("_bitWriterProto.writeBits = function(this: _BitWriterState, v: number, width: number): Error | null {")
	w.Line("    if (width <= 0 || width > 8) return new Error(`invalid bit width: ${width}`);")
	w.Line("    const maxValue = width === 8 ? 0xff : (1 << width) - 1;")
	w.Line("    if (v < 0 || v > maxValue) return new Error(`value ${v} exceeds ${width}-bit max ${maxValue}`);")
	w.Line("    for (let shift = width - 1; shift >= 0; shift--) this.writeBit(((v >> shift) & 1) === 1);")
	w.Line("    return null;")
	w.Line("};")
	w.Blank()
	w.Line("Object.defineProperty(_bitWriterProto, \"bitLen\", { get(this: _BitWriterState): number { return this._bitOffset; } });")
	w.Line("Object.defineProperty(_bitWriterProto, \"bytes\", { get(this: _BitWriterState): Uint8Array { return this._data.slice(); } });")
	w.Blank()
	w.Line("export const BitWriter = _BitWriterCtor as unknown as BitWriterCtor;")
	w.Blank()
	w.Line("export interface BitReader {")
	w.Line("    readBit: () => [boolean, Error | null];")
	w.Line("    readBits: (width: number) => [number, Error | null];")
	w.Line("    readonly bitOffset: number;")
	w.Line("}")
	w.Blank()
	w.Line("type _BitReaderState = BitReader & {")
	w.Line("    _data: Uint8Array;")
	w.Line("    _bitLimit: number;")
	w.Line("    _bitOffset: number;")
	w.Line("};")
	w.Line("type BitReaderCtor = new (data: Uint8Array, bitLimit: number) => BitReader;")
	w.Blank()
	w.Line("function _BitReaderCtor(this: _BitReaderState, data: Uint8Array, bitLimit: number): void {")
	w.Line("    const maxBits = data.byteLength * 8;")
	w.Line("    this._data = data;")
	w.Line("    this._bitLimit = bitLimit < 0 || bitLimit > maxBits ? maxBits : bitLimit;")
	w.Line("    this._bitOffset = 0;")
	w.Line("}")
	w.Line("const _bitReaderProto = _BitReaderCtor.prototype as _BitReaderState;")
	w.Blank()
	w.Line("_bitReaderProto.readBit = function(this: _BitReaderState): [boolean, Error | null] {")
	w.Line("    if (this._bitOffset >= this._bitLimit) return [false, new Error(\"not enough bits\")];")
	w.Line("    const byteIndex = Math.floor(this._bitOffset / 8);")
	w.Line("    const bitIndex = 7 - (this._bitOffset % 8);")
	w.Line("    this._bitOffset++;")
	w.Line("    return [((this._data[byteIndex] & (1 << bitIndex)) !== 0), null];")
	w.Line("};")
	w.Blank()
	w.Line("_bitReaderProto.readBits = function(this: _BitReaderState, width: number): [number, Error | null] {")
	w.Line("    if (width <= 0 || width > 8) return [0, new Error(`invalid bit width: ${width}`)];")
	w.Line("    let v = 0;")
	w.Line("    for (let i = 0; i < width; i++) {")
	w.Line("        const [bit, err] = this.readBit();")
	w.Line("        if (err !== null) return [0, err];")
	w.Line("        v <<= 1;")
	w.Line("        if (bit) v |= 1;")
	w.Line("    }")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Blank()
	w.Line("Object.defineProperty(_bitReaderProto, \"bitOffset\", { get(this: _BitReaderState): number { return this._bitOffset; } });")
	w.Blank()
	w.Line("export const BitReader = _BitReaderCtor as unknown as BitReaderCtor;")
	w.Blank()
	w.Line("export const eqList = <T>(a: T[], b: T[], eq: (left: T, right: T) => boolean): boolean => {")
	w.Line("    if (a === b) return true;")
	w.Line("    if (a.length !== b.length) return false;")
	w.Line("    for (let i = 0; i < a.length; i++) if (!eq(a[i], b[i])) return false;")
	w.Line("    return true;")
	w.Line("};")
	w.Blank()
	w.Line("export const eqBool = (a: boolean, b: boolean): boolean => a === b;")
	w.Line("export const eqU8 = (a: number, b: number): boolean => a === b;")
	w.Line("export const eqI8 = (a: number, b: number): boolean => a === b;")
	w.Line("export const eqU16 = (a: number, b: number): boolean => a === b;")
	w.Line("export const eqI16 = (a: number, b: number): boolean => a === b;")
	w.Line("export const eqU32 = (a: number, b: number): boolean => a === b;")
	w.Line("export const eqI32 = (a: number, b: number): boolean => a === b;")
	w.Line("export const eqU64 = (a: bigint, b: bigint): boolean => a === b;")
	w.Line("export const eqI64 = (a: bigint, b: bigint): boolean => a === b;")
	w.Line("export const eqText = (a: string, b: string): boolean => a === b;")
	w.Line("export const eqF32 = (a: number, b: number): boolean => Math.abs(a - b) < 1e-6;")
	w.Line("export const eqF64 = (a: number, b: number): boolean => Math.abs(a - b) < 1e-9;")
	w.Line("export const eqBin = (a: Uint8Array, b: Uint8Array): boolean => {")
	w.Line("    if (a === b) return true;")
	w.Line("    if (a.byteLength !== b.byteLength) return false;")
	w.Line("    for (let i = 0; i < a.byteLength; i++) if (a[i] !== b[i]) return false;")
	w.Line("    return true;")
	w.Line("};")
	w.Line("export const eqBinList = (a: Uint8Array[], b: Uint8Array[]): boolean => eqList(a, b, eqBin);")
	w.Blank()
	w.Line("const _checkRead = (buf: Buffer, len: number): Error | null => buf.len < len ? new Error(\"not enough data\") : null;")
	w.Line("const _setNum = (buf: Buffer, byteLength: number, setter: (view: DataView, offset: number) => void): void => {")
	w.Line("    buf.ensureCapacity(byteLength);")
	w.Line("    setter(buf.view, buf.writeOffset);")
	w.Line("    (buf as any)._writeOffset += byteLength;")
	w.Line("};")
	w.Blank()
	w.Line("export const getU8 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 1);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getUint8(buf.readOffset);")
	w.Line("    (buf as any)._readOffset += 1;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setU8 = (buf: Buffer, v: number): Error | null => { _setNum(buf, 1, (view, offset) => view.setUint8(offset, v)); return null; };")
	w.Line("export const getI8 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 1);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getInt8(buf.readOffset);")
	w.Line("    (buf as any)._readOffset += 1;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setI8 = (buf: Buffer, v: number): Error | null => { _setNum(buf, 1, (view, offset) => view.setInt8(offset, v)); return null; };")
	w.Line("export const getU16 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 2);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getUint16(buf.readOffset, true);")
	w.Line("    (buf as any)._readOffset += 2;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setU16 = (buf: Buffer, v: number): Error | null => { _setNum(buf, 2, (view, offset) => view.setUint16(offset, v, true)); return null; };")
	w.Line("export const getI16 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 2);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getInt16(buf.readOffset, true);")
	w.Line("    (buf as any)._readOffset += 2;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setI16 = (buf: Buffer, v: number): Error | null => { _setNum(buf, 2, (view, offset) => view.setInt16(offset, v, true)); return null; };")
	w.Line("export const getU24 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const [bytes, err] = buf.read(3);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    return [bytes[0] | (bytes[1] << 8) | (bytes[2] << 16), null];")
	w.Line("};")
	w.Line("export const setU24 = (buf: Buffer, v: number): Error | null => {")
	w.Line("    if (v < 0 || v > 0xFFFFFF) return new Error(`u24 out of range: ${v}`);")
	w.Line("    buf.ensureCapacity(3);")
	w.Line("    const bytes = buf.bytes;")
	w.Line("    (buf as any)._bytes[buf.writeOffset] = v & 0xff;")
	w.Line("    (buf as any)._bytes[buf.writeOffset + 1] = (v >>> 8) & 0xff;")
	w.Line("    (buf as any)._bytes[buf.writeOffset + 2] = (v >>> 16) & 0xff;")
	w.Line("    (buf as any)._writeOffset += 3;")
	w.Line("    void bytes;")
	w.Line("    return null;")
	w.Line("};")
	w.Line("export const getU32 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 4);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getUint32(buf.readOffset, true);")
	w.Line("    (buf as any)._readOffset += 4;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setU32 = (buf: Buffer, v: number): Error | null => { _setNum(buf, 4, (view, offset) => view.setUint32(offset, v, true)); return null; };")
	w.Line("export const getI32 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 4);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getInt32(buf.readOffset, true);")
	w.Line("    (buf as any)._readOffset += 4;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setI32 = (buf: Buffer, v: number): Error | null => { _setNum(buf, 4, (view, offset) => view.setInt32(offset, v, true)); return null; };")
	w.Line("export const getU64 = (buf: Buffer): [bigint, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 8);")
	w.Line("    if (err !== null) return [0n, err];")
	w.Line("    const v = buf.view.getBigUint64(buf.readOffset, true);")
	w.Line("    (buf as any)._readOffset += 8;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setU64 = (buf: Buffer, v: bigint): Error | null => { _setNum(buf, 8, (view, offset) => view.setBigUint64(offset, v, true)); return null; };")
	w.Line("export const getI64 = (buf: Buffer): [bigint, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 8);")
	w.Line("    if (err !== null) return [0n, err];")
	w.Line("    const v = buf.view.getBigInt64(buf.readOffset, true);")
	w.Line("    (buf as any)._readOffset += 8;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setI64 = (buf: Buffer, v: bigint): Error | null => { _setNum(buf, 8, (view, offset) => view.setBigInt64(offset, v, true)); return null; };")
	w.Line("export const getF32 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 4);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getFloat32(buf.readOffset, true);")
	w.Line("    (buf as any)._readOffset += 4;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setF32 = (buf: Buffer, v: number): Error | null => { _setNum(buf, 4, (view, offset) => view.setFloat32(offset, v, true)); return null; };")
	w.Line("export const getF64 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 8);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getFloat64(buf.readOffset, true);")
	w.Line("    (buf as any)._readOffset += 8;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setF64 = (buf: Buffer, v: number): Error | null => { _setNum(buf, 8, (view, offset) => view.setFloat64(offset, v, true)); return null; };")
	w.Blank()
	w.Line("export const encodeBitmap = (bits: boolean[]): Uint8Array => {")
	w.Line("    const writer = new BitWriter(bits.length);")
	w.Line("    for (const bit of bits) writer.writeBit(bit);")
	w.Line("    return writer.bytes;")
	w.Line("};")
	w.Line("export const decodeBitmap = (data: Uint8Array, count: number): [boolean[], Error | null] => {")
	w.Line("    const reader = new BitReader(data, count);")
	w.Line("    const bits: boolean[] = new Array(count);")
	w.Line("    for (let i = 0; i < count; i++) {")
	w.Line("        const [bit, err] = reader.readBit();")
	w.Line("        if (err !== null) return [[], err];")
	w.Line("        bits[i] = bit;")
	w.Line("    }")
	w.Line("    const err = validatePaddingZero(data, count, \"bitmap\");")
	w.Line("    if (err !== null) return [[], err];")
	w.Line("    return [bits, null];")
	w.Line("};")
	w.Line("export const encodeStateBlock = (states: number[]): [Uint8Array, Error | null] => {")
	w.Line("    const writer = new BitWriter(states.length * 2);")
	w.Line("    for (let i = 0; i < states.length; i++) {")
	w.Line("        const err = writer.writeBits(states[i], 2);")
	w.Line("        if (err !== null) return [new Uint8Array(0), new Error(`state[${i}]: ${err.message}`)];")
	w.Line("    }")
	w.Line("    return [writer.bytes, null];")
	w.Line("};")
	w.Line("export const decodeStateBlock = (data: Uint8Array, count: number): [number[], Error | null] => {")
	w.Line("    const reader = new BitReader(data, count * 2);")
	w.Line("    const states = new Array<number>(count);")
	w.Line("    for (let i = 0; i < count; i++) {")
	w.Line("        const [state, err] = reader.readBits(2);")
	w.Line("        if (err !== null) return [[], err];")
	w.Line("        states[i] = state;")
	w.Line("    }")
	w.Line("    const err = validatePaddingZero(data, count * 2, \"state block\");")
	w.Line("    if (err !== null) return [[], err];")
	w.Line("    return [states, null];")
	w.Line("};")
	w.Blank()
	w.Line("export const validatePaddingZero = (data: Uint8Array, usedBits: number, kind: string): Error | null => {")
	w.Line("    for (let bitOffset = usedBits; bitOffset < data.byteLength * 8; bitOffset++) {")
	w.Line("        const byteIndex = Math.floor(bitOffset / 8);")
	w.Line("        const bitIndex = 7 - (bitOffset % 8);")
	w.Line("        if ((data[byteIndex] & (1 << bitIndex)) !== 0) return new Error(`${kind} padding bit ${bitOffset - usedBits} is not zero`);")
	w.Line("    }")
	w.Line("    return null;")
	w.Line("};")
	w.Blank()
	w.Line("const _headerBitCount = (widths: readonly number[]): [number, Error | null] => {")
	w.Line("    let total = 0;")
	w.Line("    for (let i = 0; i < widths.length; i++) {")
	w.Line("        const width = widths[i];")
	w.Line("        if (width !== 1 && width !== 2) return [0, new Error(`header width[${i}] is invalid: ${width}`)];")
	w.Line("        total += width;")
	w.Line("    }")
	w.Line("    return [total, null];")
	w.Line("};")
	w.Line("export const readHeader = (data: Uint8Array, widths: readonly number[], kind: string): [number[], Err] => {")
	w.Line("    const [usedBits, err] = _headerBitCount(widths);")
	w.Line("    if (err !== null) return [[], new Error(`${kind}: ${err.message}`)];")
	w.Line("    const expectBytes = headerSize(usedBits);")
	w.Line("    if (data.byteLength !== expectBytes) return [[], new Error(`${kind}: size mismatch ${data.byteLength} !== ${expectBytes}`)];")
	w.Line("    const errPadding = validatePaddingZero(data, usedBits, kind);")
	w.Line("    if (errPadding !== null) return [[], errPadding];")
	w.Line("    const reader = new BitReader(data, usedBits);")
	w.Line("    const states = new Array<number>(widths.length);")
	w.Line("    for (let i = 0; i < widths.length; i++) {")
	w.Line("        const [state, errState] = reader.readBits(widths[i]);")
	w.Line("        if (errState !== null) return [[], new Error(`${kind}[${i}]: ${errState.message}`)];")
	w.Line("        states[i] = state;")
	w.Line("    }")
	w.Line("    return [states, undefined];")
	w.Line("};")
	w.Line("export const writeHeader = (widths: readonly number[], values: readonly number[]): [Uint8Array, Err] => {")
	w.Line("    if (widths.length !== values.length) return [new Uint8Array(0), new Error(`header widths/values length mismatch: ${widths.length} !== ${values.length}`)];")
	w.Line("    const [usedBits, err] = _headerBitCount(widths);")
	w.Line("    if (err !== null) return [new Uint8Array(0), err];")
	w.Line("    const writer = new BitWriter(usedBits);")
	w.Line("    for (let i = 0; i < widths.length; i++) {")
	w.Line("        const errState = writer.writeBits(values[i], widths[i]);")
	w.Line("        if (errState !== null) return [new Uint8Array(0), new Error(`header[${i}]: ${errState.message}`)];")
	w.Line("    }")
	w.Line("    return [writer.bytes, undefined];")
	w.Line("};")
	w.Blank()
	w.Line("const _textBytes = (v: string): Uint8Array => _textEncoder.encode(v);")
	w.Line("const _textLengthState = (length: number): [number, Error | null] => {")
	w.Line("    if (length < 0) return [0, new Error(`negative text length: ${length}`)];")
	w.Line("    if (length === 0) return [StateZero, null];")
	w.Line("    if (length <= 0xFF) return [StateU8, null];")
	w.Line("    if (length <= 0xFFFF) return [StateU16, null];")
	w.Line("    return [0, new Error(`text length exceeds u16 max: ${length}`)];")
	w.Line("};")
	w.Line("export const textState = (v: string): [number, Error | null] => _textLengthState(_textBytes(v).byteLength);")
	w.Line("export const binState = (length: number): [number, Error | null] => {")
	w.Line("    if (length < 0) return [0, new Error(`negative bin length: ${length}`)];")
	w.Line("    if (length === 0) return [StateZero, null];")
	w.Line("    if (length <= 0xFF) return [StateU8, null];")
	w.Line("    if (length <= 0xFFFF) return [StateU16, null];")
	w.Line("    if (length <= 0xFFFFFF) return [StateU24, null];")
	w.Line("    return [0, new Error(`bin length exceeds u24 max: ${length}`)];")
	w.Line("};")
	w.Line("export const listCountState = (count: number): [number, Error | null] => {")
	w.Line("    if (count < 0) return [0, new Error(`negative list count: ${count}`)];")
	w.Line("    if (count === 0) return [StateZero, null];")
	w.Line("    if (count <= 0xFF) return [StateU8, null];")
	w.Line("    return [0, new Error(`list count exceeds u8 max: ${count}`)];")
	w.Line("};")
	w.Blank()
	w.Line("const _getCompactLength = (buf: Buffer, state: number, max: number, kind: string): [number, Error | null] => {")
	w.Line("    switch (state) {")
	w.Line("    case StateZero:")
	w.Line("        return [0, null];")
	w.Line("    case StateU8: {")
	w.Line("        const [v, err] = getU8(buf);")
	w.Line("        if (err !== null) return [0, err];")
	w.Line("        if (v === 0) return [0, new Error(`${kind} state ${state} encoded zero length`)];")
	w.Line("        return [v, null];")
	w.Line("    }")
	w.Line("    case StateU16: {")
	w.Line("        const [v, err] = getU16(buf);")
	w.Line("        if (err !== null) return [0, err];")
	w.Line("        if (v === 0) return [0, new Error(`${kind} state ${state} encoded zero length`)];")
	w.Line("        if (v <= 0xFF) return [0, new Error(`${kind} state ${state} is not canonical for length ${v}`)];")
	w.Line("        return [v, null];")
	w.Line("    }")
	w.Line("    case StateU24: {")
	w.Line("        if (max < 0x10000) return [0, new Error(`${kind} state ${state} is illegal`)];")
	w.Line("        const [v, err] = getU24(buf);")
	w.Line("        if (err !== null) return [0, err];")
	w.Line("        if (v === 0) return [0, new Error(`${kind} state ${state} encoded zero length`)];")
	w.Line("        if (v <= 0xFFFF) return [0, new Error(`${kind} state ${state} is not canonical for length ${v}`)];")
	w.Line("        return [v, null];")
	w.Line("    }")
	w.Line("    default:")
	w.Line("        return [0, new Error(`invalid ${kind} state: ${state}`)];")
	w.Line("    }")
	w.Line("};")
	w.Blank()
	w.Line("export const getText = (buf: Buffer, state: number): [string, Error | null] => {")
	w.Line("    const [length, err] = _getCompactLength(buf, state, 0xFFFF, \"text\");")
	w.Line("    if (err !== null) return [\"\", err];")
	w.Line("    if (length === 0) return [\"\", null];")
	w.Line("    const [data, err2] = buf.read(length);")
	w.Line("    if (err2 !== null) return [\"\", new Error(`text body not enough data: ${buf.len} - ${length}`)];")
	w.Line("    return [_textDecoder.decode(data), null];")
	w.Line("};")
	w.Line("export const setText = (buf: Buffer, state: number, v: string): Error | null => {")
	w.Line("    const bytes = _textBytes(v);")
	w.Line("    const [canonical, err] = _textLengthState(bytes.byteLength);")
	w.Line("    if (err !== null) return err;")
	w.Line("    if (state !== canonical) return new Error(`text state ${state} is not canonical for length ${bytes.byteLength}`);")
	w.Line("    switch (state) {")
	w.Line("    case StateZero:")
	w.Line("        return null;")
	w.Line("    case StateU8: {")
	w.Line("        const err2 = setU8(buf, bytes.byteLength);")
	w.Line("        if (err2 !== null) return err2;")
	w.Line("        return buf.write(bytes);")
	w.Line("    }")
	w.Line("    case StateU16: {")
	w.Line("        const err2 = setU16(buf, bytes.byteLength);")
	w.Line("        if (err2 !== null) return err2;")
	w.Line("        return buf.write(bytes);")
	w.Line("    }")
	w.Line("    default:")
	w.Line("        return new Error(`invalid text state: ${state}`);")
	w.Line("    }")
	w.Line("};")
	w.Blank()
	w.Line("export const getBin = (buf: Buffer, state: number): [Uint8Array, Error | null] => {")
	w.Line("    const [length, err] = _getCompactLength(buf, state, 0xFFFFFF, \"bin\");")
	w.Line("    if (err !== null) return [new Uint8Array(0), err];")
	w.Line("    if (length === 0) return [new Uint8Array(0), null];")
	w.Line("    const [data, err2] = buf.read(length);")
	w.Line("    if (err2 !== null) return [new Uint8Array(0), new Error(`bin body not enough data: ${buf.len} - ${length}`)];")
	w.Line("    return [new Uint8Array(data), null];")
	w.Line("};")
	w.Line("export const setBin = (buf: Buffer, state: number, v: Uint8Array): Error | null => {")
	w.Line("    const [canonical, err] = binState(v.byteLength);")
	w.Line("    if (err !== null) return err;")
	w.Line("    if (state !== canonical) return new Error(`bin state ${state} is not canonical for length ${v.byteLength}`);")
	w.Line("    switch (state) {")
	w.Line("    case StateZero:")
	w.Line("        return null;")
	w.Line("    case StateU8: {")
	w.Line("        const err2 = setU8(buf, v.byteLength);")
	w.Line("        if (err2 !== null) return err2;")
	w.Line("        return buf.write(v);")
	w.Line("    }")
	w.Line("    case StateU16: {")
	w.Line("        const err2 = setU16(buf, v.byteLength);")
	w.Line("        if (err2 !== null) return err2;")
	w.Line("        return buf.write(v);")
	w.Line("    }")
	w.Line("    case StateU24: {")
	w.Line("        const err2 = setU24(buf, v.byteLength);")
	w.Line("        if (err2 !== null) return err2;")
	w.Line("        return buf.write(v);")
	w.Line("    }")
	w.Line("    default:")
	w.Line("        return new Error(`invalid bin state: ${state}`);")
	w.Line("    }")
	w.Line("};")
	w.Blank()
	w.Line("export const getListCount = (buf: Buffer, state: number): [number, Error | null] => {")
	w.Line("    switch (state) {")
	w.Line("    case StateZero:")
	w.Line("        return [0, null];")
	w.Line("    case StateU8: {")
	w.Line("        const [v, err] = getU8(buf);")
	w.Line("        if (err !== null) return [0, err];")
	w.Line("        if (v === 0) return [0, new Error(`list count state ${state} encoded zero length`)];")
	w.Line("        return [v, null];")
	w.Line("    }")
	w.Line("    case StateU16:")
	w.Line("    case StateU24:")
	w.Line("        return [0, new Error(`list count state ${state} is illegal`)];")
	w.Line("    default:")
	w.Line("        return [0, new Error(`invalid list count state: ${state}`)];")
	w.Line("    }")
	w.Line("};")
	w.Line("export const setListCount = (buf: Buffer, state: number, count: number): Error | null => {")
	w.Line("    const [canonical, err] = listCountState(count);")
	w.Line("    if (err !== null) return err;")
	w.Line("    if (state !== canonical) return new Error(`list count state ${state} is not canonical for count ${count}`);")
	w.Line("    switch (state) {")
	w.Line("    case StateZero:")
	w.Line("        return null;")
	w.Line("    case StateU8:")
	w.Line("        return setU8(buf, count);")
	w.Line("    default:")
	w.Line("        return new Error(`invalid list count state: ${state}`);")
	w.Line("    }")
	w.Line("};")
	w.Blank()
	w.Line("export const getBoolList = (buf: Buffer, state: number): [boolean[], Error | null] => {")
	w.Line("    const [count, err] = getListCount(buf, state);")
	w.Line("    if (err !== null) return [[], err];")
	w.Line("    const size = bitmapSize(count);")
	w.Line("    const [data, err2] = buf.read(size);")
	w.Line("    if (err2 !== null) return [[], new Error(`bool list bitmap not enough data: ${buf.len} - ${size}`)];")
	w.Line("    return decodeBitmap(data, count);")
	w.Line("};")
	w.Line("export const setBoolList = (buf: Buffer, state: number, v: boolean[]): Error | null => {")
	w.Line("    const [canonical, err] = listCountState(v.length);")
	w.Line("    if (err !== null) return err;")
	w.Line("    if (state !== canonical) return new Error(`bool list state ${state} is not canonical for count ${v.length}`);")
	w.Line("    const err2 = setListCount(buf, state, v.length);")
	w.Line("    if (err2 !== null || v.length === 0) return err2;")
	w.Line("    return buf.write(encodeBitmap(v));")
	w.Line("};")
	w.Blank()
	w.Line("export const getDefaultList = <T>(")
	w.Line("    buf: Buffer,")
	w.Line("    state: number,")
	w.Line("    defaultItem: () => T,")
	w.Line("    getItem: (buf: Buffer) => [T, Err | null],")
	w.Line("): [T[], Err] => {")
	w.Line("    const [count, err] = getListCount(buf, state);")
	w.Line("    if (err !== null) return [[], err];")
	w.Line("    const size = bitmapSize(count);")
	w.Line("    const [bitmap, err2] = buf.read(size);")
	w.Line("    if (err2 !== null) return [[], new Error(`bitmap list not enough data: ${buf.len} - ${size}`)];")
	w.Line("    const [bits, err3] = decodeBitmap(bitmap, count);")
	w.Line("    if (err3 !== null) return [[], err3];")
	w.Line("    const list = new Array<T>(count);")
	w.Line("    for (let i = 0; i < count; i++) {")
	w.Line("        if (!bits[i]) {")
	w.Line("            list[i] = defaultItem();")
	w.Line("            continue;")
	w.Line("        }")
	w.Line("        const [item, err4] = getItem(buf);")
	w.Line("        if (err4 !== undefined && err4 !== null) return [[], new Error(`bitmap list[${i}]: ${err4.message}`)];")
	w.Line("        list[i] = item;")
	w.Line("    }")
	w.Line("    return [list, undefined];")
	w.Line("};")
	w.Line("export const getZeroList = <T>(")
	w.Line("    buf: Buffer,")
	w.Line("    state: number,")
	w.Line("    zeroValue: T,")
	w.Line("    getItem: (buf: Buffer) => [T, Error | null],")
	w.Line("): [T[], Err] => getDefaultList(buf, state, () => zeroValue, (next) => resultU(...getItem(next)));")
	w.Line("export const setDefaultList = <T>(")
	w.Line("    buf: Buffer,")
	w.Line("    state: number,")
	w.Line("    v: T[],")
	w.Line("    isDefault: (item: T) => boolean,")
	w.Line("    setItem: (buf: Buffer, item: T) => Err | null,")
	w.Line("): Err => {")
	w.Line("    const [canonical, err] = listCountState(v.length);")
	w.Line("    if (err !== null) return err;")
	w.Line("    if (state !== canonical) return new Error(`bitmap list state ${state} is not canonical for count ${v.length}`);")
	w.Line("    const err2 = setListCount(buf, state, v.length);")
	w.Line("    if (err2 !== null) return err2;")
	w.Line("    if (v.length === 0) return undefined;")
	w.Line("    const bits = v.map(item => !isDefault(item));")
	w.Line("    const err3 = buf.write(encodeBitmap(bits));")
	w.Line("    if (err3 !== null) return err3;")
	w.Line("    for (let i = 0; i < v.length; i++) {")
	w.Line("        if (!bits[i]) continue;")
	w.Line("        const err4 = setItem(buf, v[i]);")
	w.Line("        if (err4 !== undefined && err4 !== null) return new Error(`bitmap list[${i}]: ${err4.message}`);")
	w.Line("    }")
	w.Line("    return undefined;")
	w.Line("};")
	w.Line("export const setZeroList = <T>(")
	w.Line("    buf: Buffer,")
	w.Line("    state: number,")
	w.Line("    v: T[],")
	w.Line("    zeroValue: T,")
	w.Line("    setItem: (buf: Buffer, item: T) => Error | null,")
	w.Line("): Err => setDefaultList(buf, state, v, (item) => item === zeroValue, (next, item) => errU(setItem(next, item)));")
	w.Blank()
	w.Line("export const getTextList = (buf: Buffer, state: number): [string[], Error | null] => {")
	w.Line("    const [count, err] = getListCount(buf, state);")
	w.Line("    if (err !== null) return [[], err];")
	w.Line("    const size = itemHeaderSize(count);")
	w.Line("    const [header, err2] = buf.read(size);")
	w.Line("    if (err2 !== null) return [[], new Error(`text list state block not enough data: ${buf.len} - ${size}`)];")
	w.Line("    const [states, err3] = decodeStateBlock(header, count);")
	w.Line("    if (err3 !== null) return [[], err3];")
	w.Line("    const list = new Array<string>(count);")
	w.Line("    for (let i = 0; i < count; i++) {")
	w.Line("        const [item, err4] = getText(buf, states[i]);")
	w.Line("        if (err4 !== null) return [[], new Error(`text list[${i}]: ${err4.message}`)];")
	w.Line("        list[i] = item;")
	w.Line("    }")
	w.Line("    return [list, null];")
	w.Line("};")
	w.Line("export const setTextList = (buf: Buffer, state: number, v: string[]): Error | null => {")
	w.Line("    const [canonical, err] = listCountState(v.length);")
	w.Line("    if (err !== null) return err;")
	w.Line("    if (state !== canonical) return new Error(`text list state ${state} is not canonical for count ${v.length}`);")
	w.Line("    const err2 = setListCount(buf, state, v.length);")
	w.Line("    if (err2 !== null) return err2;")
	w.Line("    if (v.length === 0) return null;")
	w.Line("    const states = new Array<number>(v.length);")
	w.Line("    for (let i = 0; i < v.length; i++) {")
	w.Line("        const [itemState, err3] = textState(v[i]);")
	w.Line("        if (err3 !== null) return new Error(`text list[${i}]: ${err3.message}`);")
	w.Line("        states[i] = itemState;")
	w.Line("    }")
	w.Line("    const [header, err4] = encodeStateBlock(states);")
	w.Line("    if (err4 !== null) return err4;")
	w.Line("    const err5 = buf.write(header);")
	w.Line("    if (err5 !== null) return err5;")
	w.Line("    for (let i = 0; i < v.length; i++) {")
	w.Line("        const err6 = setText(buf, states[i], v[i]);")
	w.Line("        if (err6 !== null) return new Error(`text list[${i}]: ${err6.message}`);")
	w.Line("    }")
	w.Line("    return null;")
	w.Line("};")
	w.Blank()
	w.Line("export const getBinList = (buf: Buffer, state: number): [Uint8Array[], Error | null] => {")
	w.Line("    const [count, err] = getListCount(buf, state);")
	w.Line("    if (err !== null) return [[], err];")
	w.Line("    const size = itemHeaderSize(count);")
	w.Line("    const [header, err2] = buf.read(size);")
	w.Line("    if (err2 !== null) return [[], new Error(`bin list state block not enough data: ${buf.len} - ${size}`)];")
	w.Line("    const [states, err3] = decodeStateBlock(header, count);")
	w.Line("    if (err3 !== null) return [[], err3];")
	w.Line("    const list = new Array<Uint8Array>(count);")
	w.Line("    for (let i = 0; i < count; i++) {")
	w.Line("        const [item, err4] = getBin(buf, states[i]);")
	w.Line("        if (err4 !== null) return [[], new Error(`bin list[${i}]: ${err4.message}`)];")
	w.Line("        list[i] = item;")
	w.Line("    }")
	w.Line("    return [list, null];")
	w.Line("};")
	w.Line("export const setBinList = (buf: Buffer, state: number, v: Uint8Array[]): Error | null => {")
	w.Line("    const [canonical, err] = listCountState(v.length);")
	w.Line("    if (err !== null) return err;")
	w.Line("    if (state !== canonical) return new Error(`bin list state ${state} is not canonical for count ${v.length}`);")
	w.Line("    const err2 = setListCount(buf, state, v.length);")
	w.Line("    if (err2 !== null) return err2;")
	w.Line("    if (v.length === 0) return null;")
	w.Line("    const states = new Array<number>(v.length);")
	w.Line("    for (let i = 0; i < v.length; i++) {")
	w.Line("        const [itemState, err3] = binState(v[i].byteLength);")
	w.Line("        if (err3 !== null) return new Error(`bin list[${i}]: ${err3.message}`);")
	w.Line("        states[i] = itemState;")
	w.Line("    }")
	w.Line("    const [header, err4] = encodeStateBlock(states);")
	w.Line("    if (err4 !== null) return err4;")
	w.Line("    const err5 = buf.write(header);")
	w.Line("    if (err5 !== null) return err5;")
	w.Line("    for (let i = 0; i < v.length; i++) {")
	w.Line("        const err6 = setBin(buf, states[i], v[i]);")
	w.Line("        if (err6 !== null) return new Error(`bin list[${i}]: ${err6.message}`);")
	w.Line("    }")
	w.Line("    return null;")
	w.Line("};")
	return w.String()
}
