package internal

import (
	"fmt"
	"strings"
)

func (g *TsGenerator) renderRPCFile(apis []TplApi) string {
	var w sourceWriter
	w.Line("import * as rt from \"./runtime_core\"")
	for _, line := range g.tsRpcImportLines(apis) {
		w.Line(line)
	}
	w.Blank()
	w.Line("const defaultMaxRespBytes = 4 * 1024 * 1024;")
	w.Line("const maxSafeRespBytes = Number.MAX_SAFE_INTEGER;")
	w.Line("const maxTimeoutMs = 2147483647;")
	w.Blank()
	w.Line("export enum RpcErrCode {")
	w.Line("    Ok = 200,")
	w.Line("    NoConn = 0,")
	w.Line("    Timeout = 408,")
	w.Line("    ReqErr = 400,")
	w.Line("    RespErr = 500,")
	w.Line("    NotAuth = 401,")
	w.Line("    NotExist = 404,")
	w.Line("}")
	w.Blank()
	w.Line("export type RpcStatus = RpcErrCode | number;")
	w.Blank()
	w.Line("export interface RpcConfig {")
	w.Line("    host: string;")
	w.Line("    headers?: Record<string, string>;")
	w.Line("    timeout?: number;")
	w.Line("    retries?: number;")
	w.Line("    enableRetries?: boolean;")
	w.Line("    maxRespBytes?: number;")
	w.Line("}")
	w.Blank()
	w.Line("export interface RpcClient {")
	w.Line("    setHeader: (key: string, value: string) => void;")
	w.Line("    getHeader: (key: string) => string | undefined;")
	w.Line("    removeHeader: (key: string) => void;")
	w.Line("    setAuthorization: (token: string) => void;")
	w.Line("    getAuthorization: () => string | undefined;")
	w.Line("    removeAuthorization: () => void;")
	w.Line("    isAuthorized: () => boolean;")
	for _, api := range apis {
		methodName := CamelCase(api.Name)
		promiseType := strings.ReplaceAll(g.rpcPromiseType(api.Result), "RpcErrCode", "RpcStatus")
		w.Linef("    %s: (%s) => Promise<%s>;", methodName, g.rpcArgList(api.Args), promiseType)
	}
	w.Line("}")
	w.Blank()
	w.Line("type _RpcClientState = RpcClient & {")
	w.Line("    config: RpcConfig;")
	w.Line("    headers: Record<string, string>;")
	w.Line("    timeout: number;")
	w.Line("    retries: number;")
	w.Line("    enableRetries: boolean;")
	w.Line("    maxRespBytes: number;")
	w.Line("    _fetch: (path: string, body: Uint8Array) => Promise<[Uint8Array | null, RpcStatus]>;")
	w.Line("};")
	w.Line("type RpcClientCtor = new (config: RpcConfig) => RpcClient;")
	w.Blank()
	w.Line("function _RpcClientCtor(this: _RpcClientState, config: RpcConfig): void {")
	w.Line("    this.config = { ...config, host: config.host.replace(/\\/+$/, \"\") };")
	w.Line("    this.headers = config.headers ? { ...config.headers } : {};")
	w.Line("    const cfgTimeout = config.timeout;")
	w.Line("    this.timeout = cfgTimeout !== undefined && Number.isFinite(cfgTimeout) && cfgTimeout >= 0 ? Math.min(Math.floor(cfgTimeout), maxTimeoutMs) : 5000;")
	w.Line("    const cfgRetries = config.retries;")
	w.Line("    this.retries = cfgRetries !== undefined && Number.isFinite(cfgRetries) && cfgRetries >= 0 ? Math.floor(cfgRetries) : 3;")
	w.Line("    this.enableRetries = config.enableRetries === true;")
	w.Line("    const cfgMaxRespBytes = config.maxRespBytes;")
	w.Line("    this.maxRespBytes = cfgMaxRespBytes !== undefined && Number.isFinite(cfgMaxRespBytes) && cfgMaxRespBytes > 0 ? Math.min(Math.floor(cfgMaxRespBytes), maxSafeRespBytes) : defaultMaxRespBytes;")
	w.Line("}")
	w.Line("const _rpcClientProto = _RpcClientCtor.prototype as _RpcClientState;")
	w.Blank()
	w.Line("_rpcClientProto.setHeader = function(this: _RpcClientState, key: string, value: string): void { this.headers[key] = value; };")
	w.Line("_rpcClientProto.getHeader = function(this: _RpcClientState, key: string): string | undefined { return this.headers[key]; };")
	w.Line("_rpcClientProto.removeHeader = function(this: _RpcClientState, key: string): void { delete this.headers[key]; };")
	w.Blank()
	w.Line("_rpcClientProto.setAuthorization = function(this: _RpcClientState, token: string): void { this.setHeader(\"Authorization\", `Bearer ${token}`); };")
	w.Line("_rpcClientProto.getAuthorization = function(this: _RpcClientState): string | undefined { return this.getHeader(\"Authorization\"); };")
	w.Line("_rpcClientProto.removeAuthorization = function(this: _RpcClientState): void { this.removeHeader(\"Authorization\"); };")
	w.Line("_rpcClientProto.isAuthorized = function(this: _RpcClientState): boolean { return !!this.getAuthorization(); };")
	w.Blank()
	w.Line("async function readResponseBytes(res: Response, maxRespBytes: number): Promise<[Uint8Array | null, RpcErrCode | null]> {")
	w.Line("    const contentLength = res.headers.get(\"content-length\");")
	w.Line("    if (contentLength !== null) {")
	w.Line("        const size = Number(contentLength);")
	w.Line("        if (Number.isFinite(size) && size > maxRespBytes) return [null, RpcErrCode.RespErr];")
	w.Line("    }")
	w.Blank()
	w.Line("    if (res.body !== null) {")
	w.Line("        const reader = res.body.getReader();")
	w.Line("        const chunks: Uint8Array[] = [];")
	w.Line("        let total = 0;")
	w.Line("        while (true) {")
	w.Line("            const { done, value } = await reader.read();")
	w.Line("            if (done) break;")
	w.Line("            if (value === undefined) continue;")
	w.Line("            total += value.byteLength;")
	w.Line("            if (total > maxRespBytes) {")
	w.Line("                try {")
	w.Line("                    await reader.cancel();")
	w.Line("                } catch {")
	w.Line("                }")
	w.Line("                return [null, RpcErrCode.RespErr];")
	w.Line("            }")
	w.Line("            chunks.push(value);")
	w.Line("        }")
	w.Blank()
	w.Line("        const bytes = new Uint8Array(total);")
	w.Line("        let offset = 0;")
	w.Line("        for (const chunk of chunks) {")
	w.Line("            bytes.set(chunk, offset);")
	w.Line("            offset += chunk.byteLength;")
	w.Line("        }")
	w.Line("        return [bytes, null];")
	w.Line("    }")
	w.Blank()
	w.Line("    const bytes = new Uint8Array(await res.arrayBuffer());")
	w.Line("    if (bytes.byteLength > maxRespBytes) return [null, RpcErrCode.RespErr];")
	w.Line("    return [bytes, null];")
	w.Line("}")
	w.Blank()
	w.Line("_rpcClientProto._fetch = async function(this: _RpcClientState, path: string, body: Uint8Array): Promise<[Uint8Array | null, RpcStatus]> {")
	w.Line("    const maxRetries = this.enableRetries ? this.retries : 0;")
	w.Line("    let lastStatus = RpcErrCode.NoConn;")
	w.Line("    for (let i = 0; i <= maxRetries; i++) {")
	w.Line("        if (i > 0) await new Promise((res) => setTimeout(res, i * 1000));")
	w.Line("        const controller = new AbortController();")
	w.Line("        let timeoutId: ReturnType<typeof setTimeout> | null = null;")
	w.Line("        if (this.timeout > 0) timeoutId = setTimeout(() => controller.abort(), this.timeout);")
	w.Line("        try {")
	w.Line("            const res = await fetch(`${this.config.host}/${path}`, {")
	w.Line("                method: \"POST\",")
	w.Line("                headers: { \"Content-Type\": \"application/octet-stream\", ...this.headers },")
	w.Line("                body: body as any,")
	w.Line("                signal: controller.signal,")
	w.Line("            });")
	w.Line("            if (res.ok) {")
	w.Line("                const [bytes, readErr] = await readResponseBytes(res, this.maxRespBytes);")
	w.Line("                if (readErr !== null) return [null, readErr];")
	w.Line("                return [bytes, RpcErrCode.Ok];")
	w.Line("            }")
	w.Line("            lastStatus = res.status;")
	w.Line("            if (res.status === 408 && i < maxRetries) continue;")
	w.Line("            return [null, res.status];")
	w.Line("        } catch (e: any) {")
	w.Line("            lastStatus = e && e.name === \"AbortError\" ? RpcErrCode.Timeout : RpcErrCode.NoConn;")
	w.Line("            if (i < maxRetries) continue;")
	w.Line("        } finally {")
	w.Line("            if (timeoutId !== null) clearTimeout(timeoutId);")
	w.Line("        }")
	w.Line("    }")
	w.Line("    return [null, lastStatus];")
	w.Line("};")
	for _, api := range apis {
		methodName := CamelCase(api.Name)
		defaultVal := g.rpcDefaultValue(api.Result)
		promiseType := strings.ReplaceAll(g.rpcPromiseType(api.Result), "RpcErrCode", "RpcStatus")
		w.Blank()
		w.WriteLineComment("// ", api.Note)
		w.Linef("_rpcClientProto.%s = async function(this: _RpcClientState, %s): Promise<%s> {", methodName, g.rpcArgList(api.Args), promiseType)
		w.Line("    const buf = new rt.Buffer();")
		for _, arg := range api.Args {
			g.tsDirectWrite(&w, arg.Type, CamelCase(arg.Name), "buf", g.rpcReqErrReturn(api.Result, defaultVal))
		}
		w.Linef("    const [bytes, status] = await this._fetch(\"%s\", buf.bytes);", api.Name)
		w.Linef("    if (status !== RpcErrCode.Ok || bytes === null) return %s;", g.rpcStatusReturn(api.Result, defaultVal))
		if api.Result.Name == "nil" {
			w.Line("    if (bytes.byteLength !== 0) return RpcErrCode.RespErr;")
			w.Line("    return RpcErrCode.Ok;")
			w.Line("};")
			continue
		}
		w.Line("    const respBuf = new rt.Buffer(bytes);")
		w.Linef("    let result = %s as any;", defaultVal)
		g.tsDirectRead(&w, api.Result, "result", "respBuf", fmt.Sprintf("[%s, RpcErrCode.RespErr]", defaultVal))
		w.Linef("    if (respBuf.len !== 0) return [%s, RpcErrCode.RespErr];", defaultVal)
		w.Line("    return [result as any, RpcErrCode.Ok];")
		w.Line("};")
	}
	w.Blank()
	w.Line("export const RpcClient = _RpcClientCtor as unknown as RpcClientCtor;")
	return w.String()
}

func (g *TsGenerator) renderSmokeTest(apis []TplApi) string {
	var w sourceWriter
	w.Line("import { describe, expect, test } from \"bun:test\";")
	w.Blank()
	w.Line("import * as _ from \"./_\";")
	w.Line("import { RpcClient, RpcErrCode } from \"./rpc\";")
	w.Blank()
	w.Line("const baseUrl = process.env.SB_BASE_URL || \"http://127.0.0.1:18080\";")
	w.Blank()
	w.Line("describe(\"rpc smoke\", () => {")
	w.Line("    test(\"client construction\", () => {")
	w.Line("        const client = new RpcClient({ host: baseUrl });")
	w.Line("        expect(client).toBeDefined();")
	w.Line("        expect(typeof RpcErrCode.Ok).toBe(\"number\");")
	w.Line("        expect(typeof _).toBe(\"object\");")
	w.Line("    });")
	for _, api := range apis {
		w.Linef("    test(\"method %s exists\", () => {", CamelCase(api.Name))
		w.Line("        const client = new RpcClient({ host: baseUrl });")
		w.Linef("        expect(typeof (client as any).%s).toBe(\"function\");", CamelCase(api.Name))
		w.Line("    });")
	}
	w.Line("});")
	return w.String()
}
