package internal

func (g *GoGenerator) renderAPIHTTPHelpers(w *sourceWriter) {
	w.Line("// --- 内部辅助函数 ---")
	w.Blank()
	w.Line("const defaultMaxReqBytes int64 = 4 * 1024 * 1024")
	w.Blank()
	w.Line("func normalizeHandlerStatus(ctx context.Context, status RpcErrCode) RpcErrCode {")
	w.Line("\tif status != RpcOk || ctx == nil { return status }")
	w.Line("\tif ctx.Err() == context.DeadlineExceeded { return RpcTimeout }")
	w.Line("\treturn status")
	w.Line("}")
	w.Blank()
	w.Line("func httpStatusFromRPC(status RpcErrCode) int {")
	w.Line("\tswitch status {")
	w.Line("\tcase RpcOk:")
	w.Line("\t\treturn http.StatusOK")
	w.Line("\tcase RpcReqErr:")
	w.Line("\t\treturn http.StatusBadRequest")
	w.Line("\tcase RpcNotAuth:")
	w.Line("\t\treturn http.StatusUnauthorized")
	w.Line("\tcase RpcNotExist:")
	w.Line("\t\treturn http.StatusNotFound")
	w.Line("\tcase RpcTimeout:")
	w.Line("\t\treturn http.StatusRequestTimeout")
	w.Line("\tdefault:")
	w.Line("\t\treturn http.StatusInternalServerError")
	w.Line("\t}")
	w.Line("}")
	w.Blank()
	w.Line("func checkStatus(w http.ResponseWriter, status RpcErrCode) bool {")
	w.Line("\tif status == RpcOk { return true }")
	w.Line("\tw.WriteHeader(httpStatusFromRPC(status)); return false")
	w.Line("}")
	w.Blank()
	w.Line("func parseEmptyRequest(w http.ResponseWriter, r *http.Request) bool {")
	w.Line("\tbody, err := io.ReadAll(io.LimitReader(r.Body, 1)); if err != nil { w.WriteHeader(http.StatusBadRequest); return false }")
	w.Line("\tif len(body) != 0 { w.WriteHeader(http.StatusBadRequest); return false }")
	w.Line("\treturn true")
	w.Line("}")
	w.Blank()
	w.Line("func parseRequest(w http.ResponseWriter, r *http.Request) (*bytes.Buffer, bool) {")
	w.Line("\treadLimit := defaultMaxReqBytes + 1")
	w.Line("\tbody, err := io.ReadAll(io.LimitReader(r.Body, readLimit)); if err != nil { w.WriteHeader(http.StatusBadRequest); return nil, false }")
	w.Line("\tif int64(len(body)) > defaultMaxReqBytes { w.WriteHeader(http.StatusRequestEntityTooLarge); return nil, false }")
	w.Line("\treturn bytes.NewBuffer(body), true")
	w.Line("}")
	w.Blank()
	w.Line("func sendResponse(w http.ResponseWriter, body []byte) {")
	w.Line("\tif w.Header().Get(\"Content-Type\") == \"\" {")
	w.Line("\t\tw.Header().Set(\"Content-Type\", \"application/octet-stream\")")
	w.Line("\t}")
	w.Line("\tif _, err := w.Write(body); err != nil { w.WriteHeader(http.StatusInternalServerError); return }")
	w.Line("}")
}
