package internal

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func (g *GoGenerator) Generate(schema *TplSchema) error {
	targetDir := filepath.Join(g.Config.GoDir, "sb")
	dir, err := newGeneratedDir(targetDir)
	if err != nil {
		return err
	}
	if err := removeLegacyGoLayoutFiles(targetDir); err != nil {
		return err
	}
	if err := dir.Write("runtime.go", []byte(renderGoRuntimeSource()), 0644); err != nil {
		return err
	}
	if err := dir.Write("schema.gen.go", []byte(g.renderSchemaFile(schema)), 0644); err != nil {
		return err
	}
	if len(schema.Apis) == 0 {
		return nil
	}
	for _, api := range schema.Apis {
		filename := "api." + api.Name + ".go"
		if err := dir.SyncFingerprint(filename, g.renderAPIStub(api), 0644); err != nil {
			return err
		}
	}
	return dir.WriteAll(
		generatedFile{RelativePath: "api._.go", Data: []byte(g.renderAPIFile(schema.Apis)), Perm: 0644},
		generatedFile{RelativePath: "rpc.go", Data: []byte(g.renderRPCFile(schema.Apis)), Perm: 0644},
	)
}

func removeLegacyGoLayoutFiles(targetDir string) error {
	if err := os.RemoveAll(filepath.Join(targetDir, "rt")); err != nil {
		return err
	}
	patterns := []string{
		filepath.Join(targetDir, "type.go"),
		filepath.Join(targetDir, "enum.go"),
		filepath.Join(targetDir, "struct_*.go"),
	}
	for _, pattern := range patterns {
		matches, err := filepath.Glob(pattern)
		if err != nil {
			return err
		}
		for _, match := range matches {
			if err := os.Remove(match); err != nil && !os.IsNotExist(err) {
				return err
			}
		}
	}
	return nil
}

func (g *GoGenerator) renderSchemaFile(schema *TplSchema) string {
	var w sourceWriter
	w.Line("package sb")
	w.Blank()
	w.Line("import (")
	w.Line("\t\"bytes\"")
	w.Line("\t\"fmt\"")
	w.Line("\t\"math\"")
	w.Line("\t\"slices\"")
	w.Line("")
	w.Line(")")
	w.Blank()
	w.Line("// Code generated by sb generator. DO NOT EDIT.")
	w.Line("var _ = slices.Equal[[]int, int]")
	w.Line("var _ = HeaderSize")
	w.Blank()
	g.renderSharedHelpers(&w)
	for _, enum := range schema.Enums {
		w.Blank()
		g.renderEnum(&w, enum)
	}
	for _, st := range schema.Structs {
		w.Blank()
		g.renderStruct(&w, st)
	}
	return w.String()
}

func (g *GoGenerator) renderAPIStub(api TplApi) []byte {
	apiName := SnakeCase(api.Name)
	var w sourceWriter
	w.Line("package sb")
	w.Blank()
	w.Line("import (")
	w.Line("\t\"context\"")
	w.Line(")")
	w.Blank()
	if api.Result.Name == "nil" {
		w.Linef("func %s(ctx context.Context%s) (errCode RpcErrCode) {", apiName, g.stubArgs(api.Args))
		w.Line("\treturn RpcRespErr")
		w.Line("}")
		return []byte(w.String())
	}
	w.Linef("func %s(ctx context.Context%s) (result %s, errCode RpcErrCode) {", apiName, g.stubArgs(api.Args), g.logicType(api.Result))
	w.Linef("\treturn %s, RpcRespErr", g.defaultReturn(api.Result))
	w.Line("}")
	return []byte(w.String())
}

func (g *GoGenerator) renderAPIFile(apis []TplApi) string {
	var w sourceWriter
	w.Line("package sb")
	w.Blank()
	w.Line("import (")
	w.Line("\t\"bytes\"")
	w.Line("\t\"context\"")
	w.Line("\t\"io\"")
	w.Line("\t\"net/http\"")
	w.Line("\t\"slices\"")
	w.Line("\t\"sync\"")
	w.Line("\t\"time\"")
	w.Line("")
	w.Line(")")
	w.Blank()
	w.Line("// Code generated by sb generator. DO NOT EDIT.")
	w.Line("var _ = slices.Equal[[]int, int]")
	w.Line("var _ = HeaderSize")
	w.Blank()
	w.Line("// --- API Handlers ---")
	for _, api := range apis {
		callName := PascalCase(api.Name)
		w.Blank()
		w.Linef("func %sHandler(w http.ResponseWriter, r *http.Request) {", callName)
		for _, arg := range api.Args {
			w.Linef("\tvar %s %s", CamelCase(arg.Name), g.logicType(arg.Type))
		}
		if len(api.Args) > 0 {
			w.Blank()
		}
		if len(api.Args) == 0 {
			w.Line("\tif !parseEmptyRequest(w, r) { return }")
		} else {
			w.Line("\tbuf, ok := parseRequest(w, r)")
			w.Line("\tif !ok { return }")
			for _, arg := range api.Args {
				g.directRead(&w, arg.Type, CamelCase(arg.Name), "buf", "w.WriteHeader(http.StatusBadRequest); return")
			}
			w.Line("\tif buf.Len() != 0 { w.WriteHeader(http.StatusBadRequest); return }")
			w.Blank()
		}
		if api.Result.Name == "nil" {
			w.Linef("\tstatus := %s(r.Context()%s)", SnakeCase(api.Name), g.callArgNames(api.Args))
			w.Line("\tstatus = normalizeHandlerStatus(r.Context(), status)")
			w.Line("\tif !checkStatus(w, status) { return }")
			w.Line("\tw.WriteHeader(http.StatusOK)")
			w.Line("}")
			continue
		}
		w.Linef("\tresult, status := %s(r.Context()%s)", SnakeCase(api.Name), g.callArgNames(api.Args))
		w.Line("\tstatus = normalizeHandlerStatus(r.Context(), status)")
		w.Line("\tif !checkStatus(w, status) { return }")
		w.Line("\tvar body bytes.Buffer")
		g.directWrite(&w, api.Result, "result", "&body", "w.WriteHeader(http.StatusInternalServerError); return")
		w.Line("\tsendResponse(w, body.Bytes())")
		w.Line("}")
	}
	w.Blank()
	g.renderAPIRoutesAndHelpers(&w, apis)
	return w.String()
}

func (g *GoGenerator) renderAPIRoutesAndHelpers(w *sourceWriter, apis []TplApi) {
	groups := groupAPIs(apis)
	w.Line("// --- 路由注册 ---")
	w.Blank()
	w.Line("type Middleware func(http.HandlerFunc) http.HandlerFunc")
	w.Blank()
	w.Line("func composeMiddleware(mws ...Middleware) func(http.HandlerFunc) http.HandlerFunc {")
	w.Line("\treturn func(h http.HandlerFunc) http.HandlerFunc {")
	w.Line("\t\tfor i := len(mws) - 1; i >= 0; i-- { h = mws[i](h) }")
	w.Line("\t\treturn h")
	w.Line("\t}")
	w.Line("}")
	w.Blank()
	w.Line("func TimeoutMiddleware(timeout time.Duration) Middleware {")
	w.Line("\treturn func(h http.HandlerFunc) http.HandlerFunc {")
	w.Line("\t\tif timeout <= 0 { return h }")
	w.Line("\t\treturn func(w http.ResponseWriter, r *http.Request) {")
	w.Line("\t\t\tctx, cancel := context.WithTimeout(r.Context(), timeout)")
	w.Line("\t\t\tdefer cancel()")
	w.Line("\t\t\ttw := newTimeoutResponseWriter()")
	w.Line("\t\t\tdone := make(chan struct{})")
	w.Line("\t\t\tgo func() {")
	w.Line("\t\t\t\tdefer close(done)")
	w.Line("\t\t\t\th(tw, r.WithContext(ctx))")
	w.Line("\t\t\t}()")
	w.Line("\t\t\tselect {")
	w.Line("\t\t\tcase <-done:")
	w.Line("\t\t\t\tif ctx.Err() == context.DeadlineExceeded {")
	w.Line("\t\t\t\t\ttw.timeout()")
	w.Line("\t\t\t\t\tw.WriteHeader(http.StatusRequestTimeout)")
	w.Line("\t\t\t\t\treturn")
	w.Line("\t\t\t\t}")
	w.Line("\t\t\t\ttw.writeTo(w)")
	w.Line("\t\t\tcase <-ctx.Done():")
	w.Line("\t\t\t\ttw.timeout()")
	w.Line("\t\t\t\tif ctx.Err() == context.DeadlineExceeded {")
	w.Line("\t\t\t\t\tw.WriteHeader(http.StatusRequestTimeout)")
	w.Line("\t\t\t\t}")
	w.Line("\t\t\t}")
	w.Line("\t\t}")
	w.Line("\t}")
	w.Line("}")
	w.Blank()
	w.Line("type timeoutResponseWriter struct {")
	w.Line("\tmu sync.Mutex")
	w.Line("\theader http.Header")
	w.Line("\tcode int")
	w.Line("\twroteHeader bool")
	w.Line("\tbody bytes.Buffer")
	w.Line("\ttimedOut bool")
	w.Line("}")
	w.Blank()
	w.Line("func newTimeoutResponseWriter() *timeoutResponseWriter {")
	w.Line("\treturn &timeoutResponseWriter{header: make(http.Header)}")
	w.Line("}")
	w.Blank()
	w.Line("func (tw *timeoutResponseWriter) Header() http.Header { return tw.header }")
	w.Blank()
	w.Line("func (tw *timeoutResponseWriter) WriteHeader(statusCode int) {")
	w.Line("\ttw.mu.Lock()")
	w.Line("\tdefer tw.mu.Unlock()")
	w.Line("\tif tw.timedOut || tw.wroteHeader { return }")
	w.Line("\ttw.code = statusCode")
	w.Line("\ttw.wroteHeader = true")
	w.Line("}")
	w.Blank()
	w.Line("func (tw *timeoutResponseWriter) Write(data []byte) (int, error) {")
	w.Line("\ttw.mu.Lock()")
	w.Line("\tdefer tw.mu.Unlock()")
	w.Line("\tif tw.timedOut { return 0, http.ErrHandlerTimeout }")
	w.Line("\tif !tw.wroteHeader {")
	w.Line("\t\ttw.code = http.StatusOK")
	w.Line("\t\ttw.wroteHeader = true")
	w.Line("\t}")
	w.Line("\treturn tw.body.Write(data)")
	w.Line("}")
	w.Blank()
	w.Line("func (tw *timeoutResponseWriter) timeout() {")
	w.Line("\ttw.mu.Lock()")
	w.Line("\ttw.timedOut = true")
	w.Line("\ttw.mu.Unlock()")
	w.Line("}")
	w.Blank()
	w.Line("func (tw *timeoutResponseWriter) writeTo(w http.ResponseWriter) {")
	w.Line("\ttw.mu.Lock()")
	w.Line("\tif tw.timedOut {")
	w.Line("\t\ttw.mu.Unlock()")
	w.Line("\t\treturn")
	w.Line("\t}")
	w.Line("\theader := tw.header.Clone()")
	w.Line("\tcode := tw.code")
	w.Line("\twroteHeader := tw.wroteHeader")
	w.Line("\tbody := append([]byte(nil), tw.body.Bytes()...)")
	w.Line("\ttw.mu.Unlock()")
	w.Line("\tfor k, values := range header {")
	w.Line("\t\tfor _, value := range values {")
	w.Line("\t\t\tw.Header().Add(k, value)")
	w.Line("\t\t}")
	w.Line("\t}")
	w.Line("\tif !wroteHeader { code = http.StatusOK }")
	w.Line("\tw.WriteHeader(code)")
	w.Line("\tif len(body) == 0 { return }")
	w.Line("\t_, _ = w.Write(body)")
	w.Line("}")
	modules := orderedGroupKeys(groups)
	for _, module := range modules {
		funcName := "Register" + PascalCase(module) + "Api"
		if PascalCase(module) == "Api" {
			funcName = "RegisterApi"
		}
		w.Blank()
		w.Linef("func %s(mux *http.ServeMux, mws ...Middleware) {", funcName)
		w.Line("\tmw := composeMiddleware(mws...)")
		for _, api := range groups[module] {
			w.Linef("\tmux.HandleFunc(\"POST /%s\", mw(%sHandler))", api.Name, PascalCase(api.Name))
		}
		w.Line("}")
	}
	w.Blank()
	w.Line("// --- 内部辅助函数 ---")
	w.Blank()
	w.Line("const defaultMaxReqBytes int64 = 4 * 1024 * 1024")
	w.Blank()
	w.Line("func normalizeHandlerStatus(ctx context.Context, status RpcErrCode) RpcErrCode {")
	w.Line("\tif status != RpcOk || ctx == nil { return status }")
	w.Line("\tif ctx.Err() == context.DeadlineExceeded { return RpcTimeout }")
	w.Line("\treturn status")
	w.Line("}")
	w.Blank()
	w.Line("func httpStatusFromRPC(status RpcErrCode) int {")
	w.Line("\tswitch status {")
	w.Line("\tcase RpcOk:")
	w.Line("\t\treturn http.StatusOK")
	w.Line("\tcase RpcReqErr:")
	w.Line("\t\treturn http.StatusBadRequest")
	w.Line("\tcase RpcNotAuth:")
	w.Line("\t\treturn http.StatusUnauthorized")
	w.Line("\tcase RpcNotExist:")
	w.Line("\t\treturn http.StatusNotFound")
	w.Line("\tcase RpcTimeout:")
	w.Line("\t\treturn http.StatusRequestTimeout")
	w.Line("\tdefault:")
	w.Line("\t\treturn http.StatusInternalServerError")
	w.Line("\t}")
	w.Line("}")
	w.Blank()
	w.Line("func checkStatus(w http.ResponseWriter, status RpcErrCode) bool {")
	w.Line("\tif status == RpcOk { return true }")
	w.Line("\tw.WriteHeader(httpStatusFromRPC(status)); return false")
	w.Line("}")
	w.Blank()
	w.Line("func parseEmptyRequest(w http.ResponseWriter, r *http.Request) bool {")
	w.Line("\tbody, err := io.ReadAll(io.LimitReader(r.Body, 1)); if err != nil { w.WriteHeader(http.StatusBadRequest); return false }")
	w.Line("\tif len(body) != 0 { w.WriteHeader(http.StatusBadRequest); return false }")
	w.Line("\treturn true")
	w.Line("}")
	w.Blank()
	w.Line("func parseRequest(w http.ResponseWriter, r *http.Request) (*bytes.Buffer, bool) {")
	w.Line("\treadLimit := defaultMaxReqBytes + 1")
	w.Line("\tbody, err := io.ReadAll(io.LimitReader(r.Body, readLimit)); if err != nil { w.WriteHeader(http.StatusBadRequest); return nil, false }")
	w.Line("\tif int64(len(body)) > defaultMaxReqBytes { w.WriteHeader(http.StatusRequestEntityTooLarge); return nil, false }")
	w.Line("\treturn bytes.NewBuffer(body), true")
	w.Line("}")
	w.Blank()
	w.Line("func sendResponse(w http.ResponseWriter, body []byte) {")
	w.Line("\tif w.Header().Get(\"Content-Type\") == \"\" {")
	w.Line("\t\tw.Header().Set(\"Content-Type\", \"application/octet-stream\")")
	w.Line("\t}")
	w.Line("\tif _, err := w.Write(body); err != nil { w.WriteHeader(http.StatusInternalServerError); return }")
	w.Line("}")
}

func (g *GoGenerator) renderRPCFile(apis []TplApi) string {
	var w sourceWriter
	w.Line("package sb")
	w.Blank()
	w.Line("import (")
	w.Line("\t\"bytes\"")
	w.Line("\t\"context\"")
	w.Line("\t\"io\"")
	w.Line("\t\"net/http\"")
	w.Line("\t\"strings\"")
	w.Line("\t\"sync\"")
	w.Line("\t\"time\"")
	w.Line("")
	w.Line(")")
	w.Blank()
	w.Line("type RpcErrCode int")
	w.Blank()
	w.Line("const (")
	w.Line("\tRpcOk        RpcErrCode = 200")
	w.Line("\tRpcNoConn    RpcErrCode = 0")
	w.Line("\tRpcTimeout   RpcErrCode = 408")
	w.Line("\tRpcReqErr    RpcErrCode = 400")
	w.Line("\tRpcRespErr   RpcErrCode = 500")
	w.Line("\tRpcNotAuth   RpcErrCode = 401")
	w.Line("\tRpcNotExist  RpcErrCode = 404")
	w.Line("\tdefaultMaxRespBytes int64 = 4 * 1024 * 1024")
	w.Line(")")
	w.Blank()
	w.Line("type Client struct {")
	w.Line("\tBaseURL string")
	w.Line("\tHTTP    *http.Client")
	w.Line("\tTimeout time.Duration")
	w.Line("\tRetries int")
	w.Line("\tEnableRetries bool")
	w.Line("\tMaxRespBytes int64")
	w.Line("\theaders map[string]string")
	w.Line("\theadersMu sync.RWMutex")
	w.Line("}")
	w.Blank()
	w.Line("func NewClient(baseURL string) *Client {")
	w.Line("\tbaseURL = strings.TrimRight(baseURL, \"/\")")
	w.Line("\treturn &Client{")
	w.Line("\t\tBaseURL: baseURL,")
	w.Line("\t\tHTTP:    &http.Client{},")
	w.Line("\t\tTimeout: 5 * time.Second,")
	w.Line("\t\tRetries: 3,")
	w.Line("\t\tMaxRespBytes: defaultMaxRespBytes,")
	w.Line("\t\theaders: make(map[string]string),")
	w.Line("\t}")
	w.Line("}")
	w.Blank()
	w.Line("func SetClientHeader(c *Client, key, value string) {")
	w.Line("\tif c == nil { return }")
	w.Line("\tc.headersMu.Lock()")
	w.Line("\tdefer c.headersMu.Unlock()")
	w.Line("\tif c.headers == nil { c.headers = make(map[string]string) }")
	w.Line("\tc.headers[key] = value")
	w.Line("}")
	w.Line("func GetClientHeader(c *Client, key string) string {")
	w.Line("\tif c == nil { return \"\" }")
	w.Line("\tc.headersMu.RLock()")
	w.Line("\tdefer c.headersMu.RUnlock()")
	w.Line("\treturn c.headers[key]")
	w.Line("}")
	w.Line("func RemoveClientHeader(c *Client, key string) {")
	w.Line("\tif c == nil { return }")
	w.Line("\tc.headersMu.Lock()")
	w.Line("\tdefer c.headersMu.Unlock()")
	w.Line("\tdelete(c.headers, key)")
	w.Line("}")
	w.Blank()
	w.Line("func SetClientAuthorization(c *Client, token string) { SetClientHeader(c, \"Authorization\", \"Bearer \"+token) }")
	w.Line("func GetClientAuthorization(c *Client) string        { return GetClientHeader(c, \"Authorization\") }")
	w.Line("func RemoveClientAuthorization(c *Client)            { RemoveClientHeader(c, \"Authorization\") }")
	w.Line("func IsClientAuthorized(c *Client) bool              { return GetClientAuthorization(c) != \"\" }")
	w.Blank()
	w.Line("func isTimeout(err error) bool {")
	w.Line("\tif err == nil { return false }")
	w.Line("\tif err == context.DeadlineExceeded { return true }")
	w.Line("\tif netErr, ok := err.(interface{ Timeout() bool }); ok && netErr.Timeout() { return true }")
	w.Line("\treturn false")
	w.Line("}")
	w.Blank()
	w.Line("func doClient(c *Client, ctx context.Context, path string, body []byte) ([]byte, RpcErrCode) {")
	w.Line("\tif c == nil { return nil, RpcNoConn }")
	w.Line("\tif ctx == nil { ctx = context.Background() }")
	w.Line("\thttpClient := c.HTTP")
	w.Line("\tif httpClient == nil { httpClient = &http.Client{} }")
	w.Line("\tmaxRetries := 0")
	w.Line("\tif c.EnableRetries {")
	w.Line("\t\tmaxRetries = c.Retries")
	w.Line("\t\tif maxRetries < 0 { maxRetries = 0 }")
	w.Line("\t}")
	w.Line("\tmaxRespBytes := c.MaxRespBytes")
	w.Line("\tif maxRespBytes <= 0 { maxRespBytes = defaultMaxRespBytes }")
	w.Blank()
	w.Line("\tfor i := 0; i <= maxRetries; i++ {")
	w.Line("\t\tif i > 0 {")
	w.Line("\t\t\ttimer := time.NewTimer(time.Duration(i) * time.Second)")
	w.Line("\t\t\tselect {")
	w.Line("\t\t\tcase <-ctx.Done():")
	w.Line("\t\t\t\ttimer.Stop()")
	w.Line("\t\t\t\treturn nil, RpcTimeout")
	w.Line("\t\t\tcase <-timer.C:")
	w.Line("\t\t\t}")
	w.Line("\t\t}")
	w.Line("\t\treqCtx := ctx")
	w.Line("\t\tcancel := func() {}")
	w.Line("\t\tif c.Timeout > 0 {")
	w.Line("\t\t\treqCtx, cancel = context.WithTimeout(ctx, c.Timeout)")
	w.Line("\t\t}")
	w.Line("\t\treq, reqErr := http.NewRequestWithContext(reqCtx, \"POST\", c.BaseURL+path, bytes.NewReader(body))")
	w.Line("\t\tif reqErr != nil {")
	w.Line("\t\t\tcancel()")
	w.Line("\t\t\treturn nil, RpcNoConn")
	w.Line("\t\t}")
	w.Line("\t\tc.headersMu.RLock()")
	w.Line("\t\tfor k, v := range c.headers {")
	w.Line("\t\t\treq.Header.Set(k, v)")
	w.Line("\t\t}")
	w.Line("\t\tc.headersMu.RUnlock()")
	w.Line("\t\tif req.Header.Get(\"Content-Type\") == \"\" {")
	w.Line("\t\t\treq.Header.Set(\"Content-Type\", \"application/octet-stream\")")
	w.Line("\t\t}")
	w.Line("\t\tresp, err := httpClient.Do(req)")
	w.Line("\t\tif err != nil {")
	w.Line("\t\t\tcancel()")
	w.Line("\t\t\tif isTimeout(err) && i < maxRetries { continue }")
	w.Line("\t\t\tif isTimeout(err) { return nil, RpcTimeout }")
	w.Line("\t\t\treturn nil, RpcNoConn")
	w.Line("\t\t}")
	w.Line("\t\tif resp.StatusCode == http.StatusRequestTimeout && i < maxRetries {")
	w.Line("\t\t\tresp.Body.Close()")
	w.Line("\t\t\tcancel()")
	w.Line("\t\t\tcontinue")
	w.Line("\t\t}")
	w.Line("\t\tif resp.StatusCode != http.StatusOK {")
	w.Line("\t\t\tresp.Body.Close()")
	w.Line("\t\t\tcancel()")
	w.Line("\t\t\treturn nil, RpcErrCode(resp.StatusCode)")
	w.Line("\t\t}")
	w.Line("\t\treadLimit := maxRespBytes")
	w.Line("\t\tif readLimit < (1<<63 - 1) { readLimit++ }")
	w.Line("\t\tb, readErr := io.ReadAll(io.LimitReader(resp.Body, readLimit))")
	w.Line("\t\tcloseErr := resp.Body.Close()")
	w.Line("\t\tif readErr != nil || closeErr != nil {")
	w.Line("\t\t\tcancel()")
	w.Line("\t\t\tif isTimeout(readErr) || isTimeout(closeErr) || reqCtx.Err() == context.DeadlineExceeded || ctx.Err() == context.DeadlineExceeded {")
	w.Line("\t\t\t\tif i < maxRetries { continue }")
	w.Line("\t\t\t\treturn nil, RpcTimeout")
	w.Line("\t\t\t}")
	w.Line("\t\t\treturn nil, RpcRespErr")
	w.Line("\t\t}")
	w.Line("\t\tcancel()")
	w.Line("\t\tif readLimit > maxRespBytes && int64(len(b)) > maxRespBytes { return nil, RpcRespErr }")
	w.Line("\t\treturn b, RpcOk")
	w.Line("\t}")
	w.Line("\tif ctx.Err() == context.DeadlineExceeded { return nil, RpcTimeout }")
	w.Line("\treturn nil, RpcNoConn")
	w.Line("}")
	for _, api := range apis {
		callName := PascalCase(api.Name)
		w.Blank()
		w.WriteLineCommentWithHead("// ", "Call"+callName+" ", api.Note)
		w.Linef("func Call%s(c *Client, ctx context.Context%s) (%s) {", callName, g.rpcArgs(api.Args), g.rpcReturn(api.Result))
		w.Line("\tvar buf bytes.Buffer")
		for _, arg := range api.Args {
			g.directWrite(&w, arg.Type, CamelCase(arg.Name), "&buf", fmt.Sprintf("return %s", g.rpcReqErrReturn(api.Result)))
		}
		w.Blank()
		w.Linef("\tbody, status := doClient(c, ctx, \"/%s\", buf.Bytes())", api.Name)
		w.Line("\tif status != RpcOk {")
		w.Linef("\t\treturn %s", g.rpcStatusReturn(api.Result))
		w.Line("\t}")
		if api.Result.Name == "nil" {
			w.Line("\tif len(body) != 0 { return RpcRespErr }")
			w.Line("\treturn status")
			w.Line("}")
			continue
		}
		w.Line("\trespBuf := bytes.NewBuffer(body)")
		g.directRead(&w, api.Result, "result", "respBuf", "return result, RpcRespErr")
		w.Line("\tif respBuf.Len() != 0 { return result, RpcRespErr }")
		w.Line("\treturn result, status")
		w.Line("}")
	}
	return w.String()
}

func (g *GoGenerator) renderSharedHelpers(w *sourceWriter) {
	w.Line("func eqBin(a, b []byte) bool { return bytes.Equal(a, b) }")
	w.Line("func eqBinList(a, b [][]byte) bool { return slices.EqualFunc(a, b, bytes.Equal) }")
	w.Line("func eqF32(a, b float32) bool {")
	w.Line("\tif a == b { return true }")
	w.Line("\tif math.IsNaN(float64(a)) && math.IsNaN(float64(b)) { return true }")
	w.Line("\treturn math.Abs(float64(a-b)) < 1e-6")
	w.Line("}")
	w.Line("func eqF64(a, b float64) bool {")
	w.Line("\tif a == b { return true }")
	w.Line("\tif math.IsNaN(a) && math.IsNaN(b) { return true }")
	w.Line("\treturn math.Abs(a-b) < 1e-9")
	w.Line("}")
}

func (g *GoGenerator) renderEnum(w *sourceWriter, enum TplEnum) {
	enumName := PascalCase(enum.Name)
	defaultName := enumName + PascalCase(enum.Children[0].Name)
	defaultFunc := g.enumDefaultName(enumName)
	isFunc := g.enumIsName(enumName)
	normalizeFunc := g.enumNormalizeName(enumName)
	isDefaultFunc := g.enumIsDefaultName(enumName)
	isAssignableFunc := g.enumIsAssignableName(enumName)
	eqValueFunc := g.enumEqValueName(enumName)
	eqListFunc := g.enumEqListName(enumName)
	w.WriteLineCommentWithHead("// ", enumName+" ", enum.Note)
	w.Linef("type %s uint8", enumName)
	w.Blank()
	w.Line("const (")
	for _, child := range enum.Children {
		w.WriteLineComment("\t// ", child.Note)
		w.Linef("\t%s%s %s = %d", enumName, PascalCase(child.Name), enumName, child.ID)
	}
	w.Line(")")
	w.Blank()
	w.Linef("var %sMeta = DefineEnum[%s](", CamelCase(enum.Name), enumName)
	w.Linef("\t%s,", defaultName)
	for _, child := range enum.Children {
		w.Linef("\t%s%s,", enumName, PascalCase(child.Name))
	}
	w.Line(")")
	w.Blank()
	w.Linef("func %s() %s { return %s }", defaultFunc, enumName, defaultName)
	w.Linef("func %s(v %s) bool { return IsEnum(%sMeta, v) }", isFunc, enumName, CamelCase(enum.Name))
	w.Linef("func %s(v %s) %s { return NormalizeEnum(%sMeta, v) }", normalizeFunc, enumName, enumName, CamelCase(enum.Name))
	w.Blank()
	w.Linef("func %s(v %s) bool { return IsDefaultEnum(%sMeta, v) }", isDefaultFunc, enumName, CamelCase(enum.Name))
	w.Linef("func %s(v %s) bool { return IsAssignableEnum(%sMeta, v) }", isAssignableFunc, enumName, CamelCase(enum.Name))
	w.Linef("func %s(a, b %s) bool { return EqEnumValue(%sMeta, a, b) }", eqValueFunc, enumName, CamelCase(enum.Name))
	w.Linef("func %s(a, b []%s) bool { return EqEnumList(%sMeta, a, b) }", eqListFunc, enumName, CamelCase(enum.Name))
	w.Blank()
	w.Linef("func get%sListBody(buf *bytes.Buffer, state uint8) ([]%s, error) {", enumName, enumName)
	w.Linef("\treturn get%sListBodyReuse(buf, state, nil)", enumName)
	w.Line("}")
	w.Blank()
	w.Linef("func get%sListBodyReuse(buf *bytes.Buffer, state uint8, dst []%s) ([]%s, error) {", enumName, enumName, enumName)
	w.Linef("\treturn GetEnumListInto(%sMeta, buf, state, dst)", CamelCase(enum.Name))
	w.Line("}")
	w.Blank()
	w.Linef("func set%sListBody(buf *bytes.Buffer, state uint8, v []%s) error {", enumName, enumName)
	w.Linef("\treturn SetEnumList(%sMeta, buf, state, v)", CamelCase(enum.Name))
	w.Line("}")
	w.Blank()
	w.Linef("func size%sListBody(v []%s) (int, error) {", enumName, enumName)
	w.Linef("\treturn SizeEnumList(%sMeta, v)", CamelCase(enum.Name))
	w.Line("}")
}

func (g *GoGenerator) renderStruct(w *sourceWriter, st TplStruct) {
	structName := PascalCase(st.Name)
	resetFunc := g.structResetName(structName)
	defaultFunc := g.structDefaultName(structName)
	isZeroFunc := g.structIsZeroName(structName)
	validateFunc := g.structValidateName(structName)
	sizeFunc := g.structSizeName(st.Name)
	getFunc := g.structGetName(st.Name)
	setFunc := g.structSetName(st.Name)
	readFunc := g.structReadName(st.Name)
	eqFunc := g.structEqName(st.Name)
	sizeValidatedFunc := g.structSizeValidatedName(st.Name)
	setValidatedFunc := g.structSetValidatedName(st.Name)
	headerBits := g.headerBits(st)
	headerSize := (headerBits + 7) / 8
	headerWidthsName := g.structHeaderWidthsName(structName)
	headerFieldCount := len(st.Fields)

	w.WriteLineCommentWithHead("// ", structName+" ", st.Note)
	w.Linef("type %s struct {", structName)
	for _, field := range st.Fields {
		fieldName := PascalCase(field.Name)
		tag := g.getGoTag(field)
		fieldType := g.getGoLogicType(field.Type)
		w.WriteLineComment("\t// ", field.Note)
		if tag == "" {
			w.Linef("\t%s %s", fieldName, fieldType)
			continue
		}
		w.Linef("\t%s %s %s", fieldName, fieldType, tag)
	}
	w.Line("}")
	w.Blank()
	w.Linef("func %s(s *%s) {", resetFunc, structName)
	w.Line("\tif s == nil { return }")
	w.Linef("\t*s = %s{}", structName)
	for _, field := range st.Fields {
		if field.Type.Kind == TplKindEnum && !field.Type.IsList {
			fieldName := PascalCase(field.Name)
			enumName := PascalCase(field.Type.Name)
			w.Linef("\ts.%s = %s()", fieldName, g.enumDefaultName(enumName))
		}
	}
	w.Line("}")
	w.Blank()
	w.Linef("func %s() *%s {", defaultFunc, structName)
	w.Linef("\ts := &%s{}", structName)
	w.Linef("\t%s(s)", resetFunc)
	w.Line("\treturn s")
	w.Line("}")
	w.Blank()
	w.Linef("var %s = [...]uint8{%s}", headerWidthsName, g.structHeaderWidthsLiteral(st))
	w.Blank()
	w.Linef("var %s = DefineStruct[%s](", CamelCase(st.Name)+"Meta", structName)
	for _, field := range st.Fields {
		w.Linef("\t%s,", g.goStructFieldMetaExpr(structName, field))
	}
	w.Line(")")
	w.Blank()
	w.Linef("func %s(s *%s) bool { return IsZeroStruct(%sMeta, s) }", isZeroFunc, structName, CamelCase(st.Name))
	w.Blank()
	w.Linef("func %s(s *%s) error { return ValidateStruct(%sMeta, s) }", validateFunc, structName, CamelCase(st.Name))
	w.Blank()
	w.Linef("func %s(s *%s) (int, error) {", sizeValidatedFunc, structName)
	w.Linef("\tif s == nil { return 0, fmt.Errorf(\"Size%s: nil value\") }", structName)
	w.Linef("\tsize := HeaderSize(%d)", headerBits)
	for _, field := range st.Fields {
		fieldName := PascalCase(field.Name)
		ref := "s." + fieldName
		sizeVar := "fieldSize" + fieldName
		switch {
		case field.Type.Name == "bool":
		case field.Type.Kind == TplKindBase && !field.Type.IsList && field.Type.Name == "text":
			w.Linef("\t%s, err := SizeText(%s)", sizeVar, ref)
			w.Linef("\tif err != nil { return 0, fmt.Errorf(\"Size%s %s: %%w\", err) }", structName, fieldName)
			w.Linef("\tsize += %s", sizeVar)
		case field.Type.Kind == TplKindBase && !field.Type.IsList && field.Type.Name == "bin":
			w.Linef("\t%s, err := SizeBin(%s)", sizeVar, ref)
			w.Linef("\tif err != nil { return 0, fmt.Errorf(\"Size%s %s: %%w\", err) }", structName, fieldName)
			w.Linef("\tsize += %s", sizeVar)
		case field.Type.Kind == TplKindBase && field.Type.IsList:
			w.Linef("\t%s, err := %s", sizeVar, g.listSizeExpr(field.Type, ref))
			w.Linef("\tif err != nil { return 0, fmt.Errorf(\"Size%s %s: %%w\", err) }", structName, fieldName)
			w.Linef("\tsize += %s", sizeVar)
		case field.Type.Kind == TplKindStruct && field.Type.IsList:
			typeName := PascalCase(field.Type.Name)
			w.Linef("\t%s, err := size%sListBody(%s)", sizeVar, typeName, ref)
			w.Linef("\tif err != nil { return 0, fmt.Errorf(\"Size%s %s: %%w\", err) }", structName, fieldName)
			w.Linef("\tsize += %s", sizeVar)
		case field.Type.Kind == TplKindEnum && field.Type.IsList:
			typeName := PascalCase(field.Type.Name)
			w.Linef("\t%s, err := size%sListBody(%s)", sizeVar, typeName, ref)
			w.Linef("\tif err != nil { return 0, fmt.Errorf(\"Size%s %s: %%w\", err) }", structName, fieldName)
			w.Linef("\tsize += %s", sizeVar)
		case field.Type.Kind == TplKindStruct:
			typeName := PascalCase(field.Type.Name)
			w.Linef("\tif !%s(%s) {", g.structIsZeroName(typeName), ref)
			w.Linef("\t\t%s, err := %s(%s)", sizeVar, g.structSizeName(field.Type.Name), ref)
			w.Linef("\t\tif err != nil { return 0, fmt.Errorf(\"Size%s %s: %%w\", err) }", structName, fieldName)
			w.Linef("\t\tsize += %s", sizeVar)
			w.Line("\t}")
		case field.Type.Kind == TplKindEnum:
			enumName := PascalCase(field.Type.Name)
			w.Linef("\tif !%s(%s) { size += 1 }", g.enumIsDefaultName(enumName), ref)
		default:
			if width, ok := goBaseEncodedWidth(field.Type.Name); ok {
				w.Linef("\tif %s { size += %d }", g.nonDefaultExpr(field.Type, ref), width)
			}
		}
	}
	w.Line("\treturn size, nil")
	w.Line("}")
	w.Blank()
	w.Linef("func %s(s *%s) (int, error) {", sizeFunc, structName)
	w.Linef("\tif err := %s(s); err != nil { return 0, fmt.Errorf(\"Validate%s: %%w\", err) }", validateFunc, structName)
	w.Linef("\treturn %s(s)", sizeValidatedFunc)
	w.Line("}")
	w.Blank()
	w.Linef("func %s(buf *bytes.Buffer, s *%s) error {", getFunc, structName)
	w.Linef("\tif s == nil { return fmt.Errorf(\"Get%s: nil value\") }", structName)
	for _, field := range st.Fields {
		fieldName := PascalCase(field.Name)
		ref := "s." + fieldName
		switch {
		case field.Type.Kind == TplKindStruct && !field.Type.IsList:
			w.Linef("\treuse%s := %s", fieldName, ref)
		case field.Type.Kind == TplKindBase && !field.Type.IsList && field.Type.Name == "bin":
			w.Linef("\treuse%s := %s", fieldName, ref)
		case field.Type.IsList:
			w.Linef("\treuse%s := %s", fieldName, ref)
		}
	}
	w.Linef("\t%s(s)", resetFunc)
	w.Linef("\tconst headerBits = %d", headerBits)
	w.Line("\theaderSize := HeaderSize(headerBits)")
	w.Linef("\tif buf.Len() < headerSize { return fmt.Errorf(\"Get%s header: %%d - %%d\", buf.Len(), headerSize) }", structName)
	w.Line("\theader := buf.Next(headerSize)")
	w.Linef("\tvar headerStates [%d]uint8", headerFieldCount)
	w.Linef("\tif err := ReadHeader(header, %s[:], headerStates[:], \"%s header\"); err != nil { return err }", headerWidthsName, structName)
	for i, field := range st.Fields {
		fieldName := PascalCase(field.Name)
		switch g.tagWidth(field.Type) {
		case 1:
			if field.Type.Name == "bool" {
				w.Linef("\t%sState := headerStates[%d] != 0", CamelCase(fieldName), i)
			} else {
				w.Linef("\t%sPresent := headerStates[%d] != 0", CamelCase(fieldName), i)
			}
		case 2:
			w.Linef("\t%sState := headerStates[%d]", CamelCase(fieldName), i)
		}
	}
	for _, field := range st.Fields {
		fieldName := PascalCase(field.Name)
		ref := "s." + fieldName
		switch {
		case field.Type.Name == "bool":
			w.Linef("\t%s = %sState", ref, CamelCase(fieldName))
		case field.Type.Kind == TplKindBase && !field.Type.IsList && field.Type.Name == "text":
			w.Linef("\tvalue%s, err := GetText(buf, %sState)", fieldName, CamelCase(fieldName))
			w.Linef("\tif err != nil { return fmt.Errorf(\"Get%s %s: %%w\", err) }", structName, fieldName)
			w.Linef("\t%s = value%s", ref, fieldName)
		case field.Type.Kind == TplKindBase && !field.Type.IsList && field.Type.Name == "bin":
			w.Linef("\tvalue%s, err := GetBinInto(buf, %sState, reuse%s)", fieldName, CamelCase(fieldName), fieldName)
			w.Linef("\tif err != nil { return fmt.Errorf(\"Get%s %s: %%w\", err) }", structName, fieldName)
			w.Linef("\t%s = value%s", ref, fieldName)
		case field.Type.Kind == TplKindBase && field.Type.IsList:
			w.Linef("\tvalue%s, err := %s", fieldName, g.listGetReuseExpr(field.Type, CamelCase(fieldName)+"State", "reuse"+fieldName))
			w.Linef("\tif err != nil { return fmt.Errorf(\"Get%s %s: %%w\", err) }", structName, fieldName)
			w.Linef("\t%s = value%s", ref, fieldName)
		case field.Type.Kind == TplKindStruct && field.Type.IsList:
			typeName := PascalCase(field.Type.Name)
			w.Linef("\tvalue%s, err := get%sListBodyReuse(buf, %sState, reuse%s)", fieldName, typeName, CamelCase(fieldName), fieldName)
			w.Linef("\tif err != nil { return fmt.Errorf(\"Get%s %s: %%w\", err) }", structName, fieldName)
			w.Linef("\t%s = value%s", ref, fieldName)
		case field.Type.Kind == TplKindEnum && field.Type.IsList:
			typeName := PascalCase(field.Type.Name)
			w.Linef("\tvalue%s, err := get%sListBodyReuse(buf, %sState, reuse%s)", fieldName, typeName, CamelCase(fieldName), fieldName)
			w.Linef("\tif err != nil { return fmt.Errorf(\"Get%s %s: %%w\", err) }", structName, fieldName)
			w.Linef("\t%s = value%s", ref, fieldName)
		case field.Type.Kind == TplKindStruct:
			typeName := PascalCase(field.Type.Name)
			w.Linef("\tif %sPresent {", CamelCase(fieldName))
			w.Linef("\t\tvalue%s := reuse%s", fieldName, fieldName)
			w.Linef("\t\tif value%s == nil { value%s = %s() }", fieldName, fieldName, g.structDefaultName(typeName))
			w.Linef("\t\tif err := %s(buf, value%s); err != nil { return fmt.Errorf(\"Get%s %s: %%w\", err) }", g.structGetName(field.Type.Name), fieldName, structName, fieldName)
			w.Linef("\t\t%s = value%s", ref, fieldName)
			w.Line("\t}")
		case field.Type.Kind == TplKindEnum:
			typeName := PascalCase(field.Type.Name)
			w.Linef("\tif %sPresent {", CamelCase(fieldName))
			w.Line("\t\tvalue, err := GetU8(buf)")
			w.Linef("\t\tif err != nil { return fmt.Errorf(\"Get%s %s: %%w\", err) }", structName, fieldName)
			w.Linef("\t\titem := %s(value)", typeName)
			w.Linef("\t\tif !%s(item) { return fmt.Errorf(\"Get%s %s: 非法枚举值: %%d\", item) }", g.enumIsName(typeName), structName, fieldName)
			w.Linef("\t\t%s = item", ref)
			w.Line("\t}")
		default:
			if width, getter := g.primitiveGetter(field.Type.Name); width > 0 {
				w.Linef("\tif %sPresent {", CamelCase(fieldName))
				w.Linef("\t\tvalue, err := %s(buf)", getter)
				w.Linef("\t\tif err != nil { return fmt.Errorf(\"Get%s %s: %%w\", err) }", structName, fieldName)
				w.Linef("\t\t%s = value", ref)
				w.Line("\t}")
			}
		}
	}
	w.Line("\treturn nil")
	w.Line("}")
	w.Blank()
	w.Linef("func %s(buf *bytes.Buffer, s *%s) error {", setValidatedFunc, structName)
	w.Linef("\tif s == nil { return fmt.Errorf(\"Set%s: nil value\") }", structName)
	for _, field := range st.Fields {
		if g.tagWidth(field.Type) == 2 {
			w.Linef("\t%s", g.stateInitLine(field, "return err"))
		}
	}
	w.Linef("\tsize, err := %s(s)", sizeValidatedFunc)
	w.Line("\tif err != nil { return err }")
	w.Linef("\tvar headerData [%d]byte", headerSize)
	w.Linef("\tvar headerStates [%d]uint8", headerFieldCount)
	for i, field := range st.Fields {
		fieldName := PascalCase(field.Name)
		ref := "s." + fieldName
		switch {
		case field.Type.Name == "bool":
			w.Linef("\tif %s { headerStates[%d] = 1 }", ref, i)
		case g.tagWidth(field.Type) == 1:
			w.Linef("\tif %s { headerStates[%d] = 1 }", g.nonDefaultExpr(field.Type, ref), i)
		case g.tagWidth(field.Type) == 2:
			stateVar := CamelCase(fieldName) + "State"
			w.Linef("\theaderStates[%d] = %s", i, stateVar)
		}
	}
	w.Line("\tbuf.Grow(size)")
	w.Linef("\tif err := WriteHeader(headerData[:], %s[:], headerStates[:]); err != nil { return fmt.Errorf(\"Set%s write header: %%w\", err) }", headerWidthsName, structName)
	w.Linef("\tif _, err := buf.Write(headerData[:]); err != nil { return fmt.Errorf(\"Set%s write header: %%w\", err) }", structName)
	for _, field := range st.Fields {
		fieldName := PascalCase(field.Name)
		ref := "s." + fieldName
		switch {
		case field.Type.Name == "bool":
		case field.Type.Kind == TplKindBase && !field.Type.IsList && field.Type.Name == "text":
			w.Linef("\tif err := SetText(buf, %sState, %s); err != nil { return fmt.Errorf(\"Set%s %s: %%w\", err) }", CamelCase(fieldName), ref, structName, fieldName)
		case field.Type.Kind == TplKindBase && !field.Type.IsList && field.Type.Name == "bin":
			w.Linef("\tif err := SetBin(buf, %sState, %s); err != nil { return fmt.Errorf(\"Set%s %s: %%w\", err) }", CamelCase(fieldName), ref, structName, fieldName)
		case field.Type.Kind == TplKindBase && field.Type.IsList:
			w.Linef("\tif err := %s; err != nil { return fmt.Errorf(\"Set%s %s: %%w\", err) }", g.listSetCall(field.Type, ref, CamelCase(fieldName)+"State"), structName, fieldName)
		case field.Type.Kind == TplKindStruct && field.Type.IsList:
			typeName := PascalCase(field.Type.Name)
			w.Linef("\tif err := set%sListBody(buf, %sState, %s); err != nil { return fmt.Errorf(\"Set%s %s: %%w\", err) }", typeName, CamelCase(fieldName), ref, structName, fieldName)
		case field.Type.Kind == TplKindEnum && field.Type.IsList:
			typeName := PascalCase(field.Type.Name)
			w.Linef("\tif err := set%sListBody(buf, %sState, %s); err != nil { return fmt.Errorf(\"Set%s %s: %%w\", err) }", typeName, CamelCase(fieldName), ref, structName, fieldName)
		case field.Type.Kind == TplKindStruct:
			typeName := PascalCase(field.Type.Name)
			w.Linef("\tif !%s(%s) {", g.structIsZeroName(typeName), ref)
			w.Linef("\t\tif err := %s(buf, %s); err != nil { return fmt.Errorf(\"Set%s %s: %%w\", err) }", g.structSetName(field.Type.Name), ref, structName, fieldName)
			w.Line("\t}")
		case field.Type.Kind == TplKindEnum:
			typeName := PascalCase(field.Type.Name)
			w.Linef("\tif !%s(%s) {", g.enumIsDefaultName(typeName), ref)
			w.Linef("\t\tif err := SetU8(buf, uint8(%s(%s))); err != nil { return fmt.Errorf(\"Set%s %s: %%w\", err) }", g.enumNormalizeName(typeName), ref, structName, fieldName)
			w.Line("\t}")
		default:
			if _, setter := g.primitiveGetter(field.Type.Name); setter != "" {
				w.Linef("\tif %s {", g.nonDefaultExpr(field.Type, ref))
				w.Linef("\t\tif err := %s(buf, %s); err != nil { return fmt.Errorf(\"Set%s %s: %%w\", err) }", g.primitiveSetter(field.Type.Name), ref, structName, fieldName)
				w.Line("\t}")
			}
		}
	}
	w.Line("\treturn nil")
	w.Line("}")
	w.Blank()
	w.Linef("func %s(buf *bytes.Buffer, s *%s) error {", setFunc, structName)
	w.Linef("\tif s == nil { return fmt.Errorf(\"Set%s: nil value\") }", structName)
	w.Linef("\tif err := %s(s); err != nil { return fmt.Errorf(\"Validate%s: %%w\", err) }", validateFunc, structName)
	w.Linef("\treturn %s(buf, s)", setValidatedFunc)
	w.Line("}")
	w.Blank()
	w.Linef("func %s(buf *bytes.Buffer) (*%s, error) {", readFunc, structName)
	w.Linef("\ts := %s()", defaultFunc)
	w.Linef("\treturn s, %s(buf, s)", getFunc)
	w.Line("}")
	w.Blank()
	w.Linef("func %s(a, b *%s) bool { return EqStruct(%sMeta, a, b) }", eqFunc, structName, CamelCase(st.Name))
	w.Blank()
	g.renderStructListBodyHelpers(w, st)
}

func (g *GoGenerator) renderStructListBodyHelpers(w *sourceWriter, st TplStruct) {
	structName := PascalCase(st.Name)
	getFunc := g.structGetName(st.Name)
	sizeFunc := g.structSizeName(st.Name)
	setValidatedFunc := g.structSetValidatedName(st.Name)
	w.Linef("func get%sListBody(buf *bytes.Buffer, state uint8) ([]*%s, error) {", structName, structName)
	w.Linef("\treturn get%sListBodyReuse(buf, state, nil)", structName)
	w.Line("}")
	w.Blank()
	w.Linef("func get%sListBodyReuse(buf *bytes.Buffer, state uint8, dst []*%s) ([]*%s, error) {", structName, structName, structName)
	w.Linef("\treturn GetDefaultPtrListInto(buf, state, dst, %s, %s)", g.structDefaultName(structName), getFunc)
	w.Line("}")
	w.Blank()
	w.Linef("func set%sListBody(buf *bytes.Buffer, state uint8, v []*%s) error {", structName, structName)
	w.Line("\treturn SetDefaultPtrList(")
	w.Line("\t\tbuf,")
	w.Line("\t\tstate,")
	w.Line("\t\tv,")
	w.Linef("\t\t%q,", structName)
	w.Linef("\t\t%s,", g.structValidateName(structName))
	w.Linef("\t\t%s,", g.structIsZeroName(structName))
	w.Linef("\t\t%s,", sizeFunc)
	w.Linef("\t\t%s,", setValidatedFunc)
	w.Line("\t)")
	w.Line("}")
	w.Blank()
	w.Linef("func size%sListBody(v []*%s) (int, error) {", structName, structName)
	w.Line("\treturn SizeDefaultPtrList(")
	w.Line("\t\tv,")
	w.Linef("\t\t%q,", structName)
	w.Linef("\t\t%s,", g.structValidateName(structName))
	w.Linef("\t\t%s,", g.structIsZeroName(structName))
	w.Linef("\t\t%s,", sizeFunc)
	w.Line("\t)")
	w.Line("}")
}

func (g *GoGenerator) enumDefaultName(typeName string) string { return "default" + typeName }
func (g *GoGenerator) enumIsName(typeName string) string      { return "is" + typeName }
func (g *GoGenerator) enumNormalizeName(typeName string) string {
	return "normalize" + typeName
}
func (g *GoGenerator) enumIsDefaultName(typeName string) string { return "isDefault" + typeName }
func (g *GoGenerator) enumIsAssignableName(typeName string) string {
	return "isAssignable" + typeName
}
func (g *GoGenerator) enumEqValueName(typeName string) string    { return "eq" + typeName + "Value" }
func (g *GoGenerator) enumEqListName(typeName string) string     { return "eq" + typeName + "List" }
func (g *GoGenerator) structResetName(typeName string) string    { return "reset" + typeName }
func (g *GoGenerator) structDefaultName(typeName string) string  { return "default" + typeName }
func (g *GoGenerator) structIsZeroName(typeName string) string   { return "isZero" + typeName }
func (g *GoGenerator) structValidateName(typeName string) string { return "validate" + typeName }
func (g *GoGenerator) structSizeName(rawName string) string {
	suffix := PascalCase(rawName)
	if g.isAPIWrapper(rawName) {
		return "size" + suffix
	}
	return "Size" + suffix
}
func (g *GoGenerator) structGetName(rawName string) string {
	suffix := PascalCase(rawName)
	if g.isAPIWrapper(rawName) {
		return "get" + suffix
	}
	return "Get" + suffix
}
func (g *GoGenerator) structSetName(rawName string) string {
	suffix := PascalCase(rawName)
	if g.isAPIWrapper(rawName) {
		return "set" + suffix
	}
	return "Set" + suffix
}
func (g *GoGenerator) structReadName(rawName string) string {
	suffix := PascalCase(rawName)
	if g.isAPIWrapper(rawName) {
		return "read" + suffix
	}
	return "Read" + suffix
}
func (g *GoGenerator) structEqName(rawName string) string {
	suffix := PascalCase(rawName)
	if g.isAPIWrapper(rawName) {
		return "eq" + suffix
	}
	return "Eq" + suffix
}
func (g *GoGenerator) structSizeValidatedName(rawName string) string {
	return "size" + PascalCase(rawName) + "Validated"
}
func (g *GoGenerator) structSetValidatedName(rawName string) string {
	return "set" + PascalCase(rawName) + "Validated"
}
func (g *GoGenerator) structHeaderWidthsName(typeName string) string {
	return CamelCase(typeName) + "HeaderWidths"
}
func (g *GoGenerator) structHeaderWidthsLiteral(st TplStruct) string {
	widths := make([]string, 0, len(st.Fields))
	for _, field := range st.Fields {
		widths = append(widths, fmt.Sprintf("%d", g.tagWidth(field.Type)))
	}
	return strings.Join(widths, ", ")
}
func (g *GoGenerator) isAPIWrapper(rawName string) bool {
	return len(rawName) > 4 && rawName[:4] == "api_"
}

func (g *GoGenerator) headerBits(st TplStruct) int {
	total := 0
	for _, field := range st.Fields {
		total += g.tagWidth(field.Type)
	}
	return total
}

func (g *GoGenerator) tagWidth(t TplType) int {
	if t.Name == "bool" && !t.IsList {
		return 1
	}
	if t.Kind == TplKindBase && (t.Name == "text" || t.Name == "bin" || t.IsList) {
		return 2
	}
	if t.IsList {
		return 2
	}
	return 1
}

func (g *GoGenerator) nonDefaultExpr(t TplType, ref string) string {
	switch {
	case t.IsList:
		return fmt.Sprintf("len(%s) != 0", ref)
	case t.Kind == TplKindStruct:
		return fmt.Sprintf("!%s(%s)", g.structIsZeroName(PascalCase(t.Name)), ref)
	case t.Kind == TplKindEnum:
		return fmt.Sprintf("!%s(%s)", g.enumIsDefaultName(PascalCase(t.Name)), ref)
	case t.Name == "text":
		return fmt.Sprintf("%s != \"\"", ref)
	case t.Name == "bin":
		return fmt.Sprintf("len(%s) != 0", ref)
	case t.Name == "bool":
		return ref
	default:
		return fmt.Sprintf("%s != 0", ref)
	}
}

func (g *GoGenerator) stateInitLine(field TplStructField, onErr string) string {
	fieldName := PascalCase(field.Name)
	ref := "s." + fieldName
	switch {
	case field.Type.Kind == TplKindBase && !field.Type.IsList && field.Type.Name == "text":
		return fmt.Sprintf("%sState, err := TextState(len(%s)); if err != nil { %s }", CamelCase(fieldName), ref, onErr)
	case field.Type.Kind == TplKindBase && !field.Type.IsList && field.Type.Name == "bin":
		return fmt.Sprintf("%sState, err := BinState(len(%s)); if err != nil { %s }", CamelCase(fieldName), ref, onErr)
	default:
		return fmt.Sprintf("%sState, err := ListCountState(len(%s)); if err != nil { %s }", CamelCase(fieldName), ref, onErr)
	}
}

func (g *GoGenerator) primitiveGetter(name string) (int, string) {
	switch name {
	case "i8":
		return 1, "GetI8"
	case "u8":
		return 1, "GetU8"
	case "i16":
		return 2, "GetI16"
	case "u16":
		return 2, "GetU16"
	case "i32":
		return 4, "GetI32"
	case "u32":
		return 4, "GetU32"
	case "i64":
		return 8, "GetI64"
	case "u64":
		return 8, "GetU64"
	case "f32":
		return 4, "GetF32"
	case "f64":
		return 8, "GetF64"
	default:
		return 0, ""
	}
}

func (g *GoGenerator) primitiveSetter(name string) string {
	switch name {
	case "i8":
		return "SetI8"
	case "u8":
		return "SetU8"
	case "i16":
		return "SetI16"
	case "u16":
		return "SetU16"
	case "i32":
		return "SetI32"
	case "u32":
		return "SetU32"
	case "i64":
		return "SetI64"
	case "u64":
		return "SetU64"
	case "f32":
		return "SetF32"
	case "f64":
		return "SetF64"
	default:
		return ""
	}
}

func (g *GoGenerator) listSizeExpr(t TplType, ref string) string {
	switch t.Name {
	case "bool":
		return fmt.Sprintf("SizeBoolList(%s)", ref)
	case "text":
		return fmt.Sprintf("SizeTextList(%s)", ref)
	case "bin":
		return fmt.Sprintf("SizeBinList(%s)", ref)
	default:
		if t.Kind == TplKindBase {
			width, _ := goBaseEncodedWidth(t.Name)
			return fmt.Sprintf("SizeZeroList(%s, %d)", ref, width)
		}
		defaultFactory, callbacks := g.bitmapListCallbacks(t)
		_ = defaultFactory
		return fmt.Sprintf("SizeDefaultList(%s, %s, %s)", ref, callbacks[0], callbacks[1])
	}
}

func (g *GoGenerator) listGetExpr(t TplType, stateVar string) string {
	return g.listGetReuseExpr(t, stateVar, "nil")
}

func (g *GoGenerator) listGetReuseExpr(t TplType, stateVar, dstVar string) string {
	switch t.Name {
	case "bool":
		return fmt.Sprintf("GetBoolListInto(buf, %s, %s)", stateVar, dstVar)
	case "text":
		return fmt.Sprintf("GetTextListInto(buf, %s, %s)", stateVar, dstVar)
	case "bin":
		return fmt.Sprintf("GetBinListInto(buf, %s, %s)", stateVar, dstVar)
	default:
		if t.Kind == TplKindBase {
			_, getter := g.primitiveGetter(t.Name)
			return fmt.Sprintf("GetZeroListInto(buf, %s, %s, %s)", stateVar, dstVar, getter)
		}
		defaultFactory, callbacks := g.bitmapListCallbacks(t)
		return fmt.Sprintf("GetDefaultListInto(buf, %s, %s, %s, %s)", stateVar, dstVar, defaultFactory, callbacks[2])
	}
}

func (g *GoGenerator) listSetCall(t TplType, ref, stateVar string) string {
	switch t.Name {
	case "bool":
		return fmt.Sprintf("SetBoolList(buf, %s, %s)", stateVar, ref)
	case "text":
		return fmt.Sprintf("SetTextList(buf, %s, %s)", stateVar, ref)
	case "bin":
		return fmt.Sprintf("SetBinList(buf, %s, %s)", stateVar, ref)
	default:
		if t.Kind == TplKindBase {
			width, _ := goBaseEncodedWidth(t.Name)
			return fmt.Sprintf("SetZeroList(buf, %s, %s, %d, %s)", stateVar, ref, width, g.primitiveSetter(t.Name))
		}
		_, callbacks := g.bitmapListCallbacks(t)
		return fmt.Sprintf("SetDefaultList(buf, %s, %s, %s, %s, %s)", stateVar, ref, callbacks[0], callbacks[1], callbacks[3])
	}
}

func (g *GoGenerator) bitmapListCallbacks(t TplType) (string, [4]string) {
	elemType := g.getGoType(TplType{Name: t.Name, Kind: t.Kind, IsList: false})
	switch t.Kind {
	case TplKindEnum:
		enumName := PascalCase(t.Name)
		return fmt.Sprintf("func() %s { return %s() }", elemType, g.enumDefaultName(enumName)), [4]string{
			fmt.Sprintf("func(item %s) bool { return %s(item) }", elemType, g.enumIsDefaultName(enumName)),
			fmt.Sprintf("func(item %s) (int, error) { if !%s(item) { return 0, fmt.Errorf(\"非法枚举值: %%d\", item) }; return 1, nil }", elemType, g.enumIsAssignableName(enumName)),
			fmt.Sprintf("func(buf *bytes.Buffer) (%s, error) { value, err := GetU8(buf); if err != nil { return 0, err }; item := %s(value); if !Is%s(item) { return 0, fmt.Errorf(\"非法枚举值: %%d\", item) }; return item, nil }", elemType, elemType, enumName),
			fmt.Sprintf("func(buf *bytes.Buffer, item %s) error { if !Is%s(item) { return fmt.Errorf(\"非法枚举值: %%d\", item) }; return SetU8(buf, uint8(item)) }", elemType, enumName),
		}
	case TplKindStruct:
		typeName := PascalCase(t.Name)
		return "nil", [4]string{
			fmt.Sprintf("func(item %s) bool { return %s(item) }", elemType, g.structIsZeroName(typeName)),
			fmt.Sprintf("func(item %s) (int, error) { return %s(item) }", elemType, g.structSizeName(t.Name)),
			fmt.Sprintf("func(buf *bytes.Buffer) (%s, error) { return %s(buf) }", elemType, g.structReadName(t.Name)),
			fmt.Sprintf("func(buf *bytes.Buffer, item %s) error { return %s(buf, item) }", elemType, g.structSetName(t.Name)),
		}
	default:
		defaultValue := g.getGoValue(t.Name)
		_, getter := g.primitiveGetter(t.Name)
		setter := g.primitiveSetter(t.Name)
		width, _ := goBaseEncodedWidth(t.Name)
		if t.Name == "f32" || t.Name == "f64" {
			defaultValue = "0"
		}
		return fmt.Sprintf("func() %s { return %s }", elemType, defaultValue), [4]string{
			fmt.Sprintf("func(item %s) bool { return item == 0 }", elemType),
			fmt.Sprintf("func(item %s) (int, error) { return %d, nil }", elemType, width),
			fmt.Sprintf("func(buf *bytes.Buffer) (%s, error) { return %s(buf) }", elemType, getter),
			fmt.Sprintf("func(buf *bytes.Buffer, item %s) error { return %s(buf, item) }", elemType, setter),
		}
	}
}

func (g *GoGenerator) eqExpr(t TplType, left, right string) string {
	switch {
	case t.Kind == TplKindStruct && t.IsList:
		return fmt.Sprintf("(slices.EqualFunc(%s, %s, Eq%s))", left, right, PascalCase(t.Name))
	case t.Kind == TplKindStruct:
		return fmt.Sprintf("(Eq%s(%s, %s))", PascalCase(t.Name), left, right)
	case t.Kind == TplKindEnum && t.IsList:
		return fmt.Sprintf("(%s(%s, %s))", g.enumEqListName(PascalCase(t.Name)), left, right)
	case t.Kind == TplKindEnum:
		return fmt.Sprintf("(%s(%s, %s))", g.enumEqValueName(PascalCase(t.Name)), left, right)
	case t.Kind == TplKindBase && t.IsList && t.Name == "bin":
		return fmt.Sprintf("(eqBinList(%s, %s))", left, right)
	case t.Kind == TplKindBase && t.IsList && t.Name == "f32":
		return fmt.Sprintf("(slices.EqualFunc(%s, %s, eqF32))", left, right)
	case t.Kind == TplKindBase && t.IsList && t.Name == "f64":
		return fmt.Sprintf("(slices.EqualFunc(%s, %s, eqF64))", left, right)
	case t.Kind == TplKindBase && t.IsList:
		return fmt.Sprintf("(slices.Equal(%s, %s))", left, right)
	case t.Name == "bin":
		return fmt.Sprintf("(eqBin(%s, %s))", left, right)
	case t.Name == "f32":
		return fmt.Sprintf("(eqF32(%s, %s))", left, right)
	case t.Name == "f64":
		return fmt.Sprintf("(eqF64(%s, %s))", left, right)
	default:
		return fmt.Sprintf("(%s == %s)", left, right)
	}
}

func (g *GoGenerator) goStructFieldMetaExpr(structName string, field TplStructField) string {
	fieldName := PascalCase(field.Name)
	label := fieldName
	ref := fmt.Sprintf("func(s *%s) %s { return s.%s }", structName, g.getGoLogicType(field.Type), fieldName)

	switch {
	case field.Type.Name == "text" && !field.Type.IsList:
		return fmt.Sprintf("TextField[%s](%q, %s)", structName, label, ref)
	case field.Type.Name == "bin" && !field.Type.IsList:
		return fmt.Sprintf("BinField[%s](%q, %s)", structName, label, ref)
	case field.Type.Kind == TplKindEnum && !field.Type.IsList:
		typeName := PascalCase(field.Type.Name)
		return fmt.Sprintf("EnumField[%s, %s](%q, %s, %s, %s, %s)", structName, g.getGoLogicType(field.Type), label, ref, g.enumIsAssignableName(typeName), g.enumIsDefaultName(typeName), g.enumEqValueName(typeName))
	case field.Type.Kind == TplKindStruct && !field.Type.IsList:
		typeName := PascalCase(field.Type.Name)
		return fmt.Sprintf("PtrField[%s, %s](%q, func(s *%s) *%s { return s.%s }, %s, %s, %s)", structName, typeName, label, structName, typeName, fieldName, g.structValidateName(typeName), g.structIsZeroName(typeName), g.structEqName(field.Type.Name))
	case field.Type.IsList:
		return fmt.Sprintf("SliceField[%s, %s](%q, func(s *%s) %s { return s.%s }, %s, %s)", structName, g.goListElemType(field.Type), label, structName, g.getGoLogicType(field.Type), fieldName, g.goListValidateExpr(field.Type), g.goListEqExpr(field.Type))
	default:
		return fmt.Sprintf("ScalarField[%s, %s](%q, %s)", structName, g.getGoLogicType(field.Type), label, ref)
	}
}

func (g *GoGenerator) goListElemType(t TplType) string {
	switch {
	case t.Kind == TplKindStruct:
		return "*" + PascalCase(t.Name)
	case t.Kind == TplKindEnum:
		return PascalCase(t.Name)
	default:
		return g.getGoType(TplType{Name: t.Name, Kind: t.Kind})
	}
}

func (g *GoGenerator) goListValidateExpr(t TplType) string {
	switch {
	case t.Kind == TplKindStruct:
		typeName := PascalCase(t.Name)
		return fmt.Sprintf("func(values []*%s) error { _, err := size%sListBody(values); return err }", typeName, typeName)
	case t.Kind == TplKindEnum:
		typeName := PascalCase(t.Name)
		return fmt.Sprintf("func(values []%s) error { _, err := size%sListBody(values); return err }", typeName, typeName)
	case t.Name == "bool":
		return "func(values []bool) error { _, err := SizeBoolList(values); return err }"
	case t.Name == "text":
		return "func(values []string) error { _, err := SizeTextList(values); return err }"
	case t.Name == "bin":
		return "func(values [][]byte) error { _, err := SizeBinList(values); return err }"
	default:
		width, _ := goBaseEncodedWidth(t.Name)
		return fmt.Sprintf("func(values %s) error { _, err := SizeZeroList(values, %d); return err }", g.getGoLogicType(t), width)
	}
}

func (g *GoGenerator) goListEqExpr(t TplType) string {
	switch {
	case t.Kind == TplKindStruct:
		typeName := PascalCase(t.Name)
		return fmt.Sprintf("func(a, b []*%s) bool { return slices.EqualFunc(a, b, %s) }", typeName, g.structEqName(t.Name))
	case t.Kind == TplKindEnum:
		return g.enumEqListName(PascalCase(t.Name))
	case t.Name == "bin":
		return "eqBinList"
	case t.Name == "f32":
		return "func(a, b []float32) bool { return slices.EqualFunc(a, b, eqF32) }"
	case t.Name == "f64":
		return "func(a, b []float64) bool { return slices.EqualFunc(a, b, eqF64) }"
	default:
		return fmt.Sprintf("func(a, b %s) bool { return slices.Equal(a, b) }", g.getGoLogicType(t))
	}
}

func (g *GoGenerator) logicType(t TplType) string {
	return g.getGoLogicType(t)
}

func (g *GoGenerator) defaultReturn(t TplType) string {
	if t.Kind == TplKindStruct || t.IsList {
		return "nil"
	}
	return g.getGoValue(t.Name)
}

func (g *GoGenerator) stubArgs(args []TplApiArg) string {
	if len(args) == 0 {
		return ""
	}
	parts := make([]string, 0, len(args))
	for _, arg := range args {
		parts = append(parts, fmt.Sprintf("%s %s", arg.Name, g.logicType(arg.Type)))
	}
	return ", " + joinWithComma(parts)
}

func (g *GoGenerator) rpcArgs(args []TplApiArg) string {
	if len(args) == 0 {
		return ""
	}
	parts := make([]string, 0, len(args))
	for _, arg := range args {
		parts = append(parts, fmt.Sprintf("%s %s", CamelCase(arg.Name), g.logicType(arg.Type)))
	}
	return ", " + joinWithComma(parts)
}

func (g *GoGenerator) rpcReturn(result TplType) string {
	if result.Name == "nil" {
		return "errCode RpcErrCode"
	}
	return fmt.Sprintf("result %s, errCode RpcErrCode", g.logicType(result))
}

func (g *GoGenerator) rpcReqErrReturn(result TplType) string {
	if result.Name == "nil" {
		return "RpcReqErr"
	}
	return "result, RpcReqErr"
}

func (g *GoGenerator) rpcStatusReturn(result TplType) string {
	if result.Name == "nil" {
		return "status"
	}
	return "result, status"
}

func (g *GoGenerator) apiReqStruct(api TplApi) (TplStruct, bool) {
	if len(api.Args) == 0 {
		return TplStruct{}, false
	}
	fields := make([]TplStructField, 0, len(api.Args))
	for _, arg := range api.Args {
		fields = append(fields, TplStructField{
			Name: arg.Name,
			Type: arg.Type,
		})
	}
	return TplStruct{
		Name:   "api_" + SnakeCase(api.Name) + "_req",
		Fields: fields,
	}, true
}

func (g *GoGenerator) apiRespStruct(api TplApi) (TplStruct, bool) {
	if api.Result.Name == "nil" {
		return TplStruct{}, false
	}
	return TplStruct{
		Name: "api_" + SnakeCase(api.Name) + "_resp",
		Fields: []TplStructField{
			{Name: "result", Type: api.Result},
		},
	}, true
}

func (g *GoGenerator) apiReqTypeName(api TplApi) (string, bool) {
	req, ok := g.apiReqStruct(api)
	if !ok {
		return "", false
	}
	return PascalCase(req.Name), true
}

func (g *GoGenerator) apiRespTypeName(api TplApi) (string, bool) {
	resp, ok := g.apiRespStruct(api)
	if !ok {
		return "", false
	}
	return PascalCase(resp.Name), true
}

func (g *GoGenerator) apiReqCodecInfo(api TplApi) (typeName string, readName string, setName string, ok bool) {
	req, ok := g.apiReqStruct(api)
	if !ok {
		return "", "", "", false
	}
	return PascalCase(req.Name), g.structReadName(req.Name), g.structSetName(req.Name), true
}

func (g *GoGenerator) apiRespCodecInfo(api TplApi) (typeName string, readName string, setName string, ok bool) {
	resp, ok := g.apiRespStruct(api)
	if !ok {
		return "", "", "", false
	}
	return PascalCase(resp.Name), g.structReadName(resp.Name), g.structSetName(resp.Name), true
}

func (g *GoGenerator) handlerCallArgs(args []TplApiArg, reqVar string) string {
	if len(args) == 0 {
		return ""
	}
	parts := make([]string, 0, len(args))
	for _, arg := range args {
		parts = append(parts, reqVar+"."+PascalCase(arg.Name))
	}
	return ", " + joinWithComma(parts)
}

func (g *GoGenerator) callArgNames(args []TplApiArg) string {
	if len(args) == 0 {
		return ""
	}
	parts := make([]string, 0, len(args))
	for _, arg := range args {
		parts = append(parts, CamelCase(arg.Name))
	}
	return ", " + joinWithComma(parts)
}

func (g *GoGenerator) directRead(w *sourceWriter, t TplType, target, bufVar, onErr string) {
	w.Line("\t{")
	switch {
	case t.Name == "bool" && !t.IsList:
		w.Linef("\t\tvalue, err := GetU8(%s)", bufVar)
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\tif value > 1 { %s }", onErr)
		w.Linef("\t\t%s = value != 0", target)
	case t.Kind == TplKindBase && !t.IsList && t.Name == "text":
		w.Linef("\t\tstate, err := GetU8(%s)", bufVar)
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\tvalue, err := GetText(%s, state)", bufVar)
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\t%s = value", target)
	case t.Kind == TplKindBase && !t.IsList && t.Name == "bin":
		w.Linef("\t\tstate, err := GetU8(%s)", bufVar)
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\tvalue, err := GetBinInto(%s, state, nil)", bufVar)
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\t%s = value", target)
	case t.IsList:
		w.Linef("\t\tstate, err := GetU8(%s)", bufVar)
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\tvalue, err := %s", g.directListGetExpr(t, "state", bufVar))
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\t%s = value", target)
	case t.Kind == TplKindStruct:
		w.Linef("\t\tvalue, err := %s(%s)", g.structReadName(t.Name), bufVar)
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\t%s = value", target)
	case t.Kind == TplKindEnum:
		typeName := PascalCase(t.Name)
		w.Linef("\t\tvalue, err := GetU8(%s)", bufVar)
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\titem := %s(value)", typeName)
		w.Linef("\t\tif !%s(item) { %s }", g.enumIsName(typeName), onErr)
		w.Linef("\t\t%s = item", target)
	default:
		_, getter := g.primitiveGetter(t.Name)
		w.Linef("\t\tvalue, err := %s(%s)", getter, bufVar)
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\t%s = value", target)
	}
	w.Line("\t}")
}

func (g *GoGenerator) directWrite(w *sourceWriter, t TplType, ref, bufVar, onErr string) {
	w.Line("\t{")
	switch {
	case t.Name == "bool" && !t.IsList:
		w.Line("\t\tvar value uint8")
		w.Linef("\t\tif %s { value = 1 }", ref)
		w.Linef("\t\tif err := SetU8(%s, value); err != nil { %s }", bufVar, onErr)
	case t.Kind == TplKindBase && !t.IsList && t.Name == "text":
		w.Linef("\t\tstate, err := TextState(len(%s))", ref)
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\tif err := SetU8(%s, state); err != nil { %s }", bufVar, onErr)
		w.Linef("\t\tif err := SetText(%s, state, %s); err != nil { %s }", bufVar, ref, onErr)
	case t.Kind == TplKindBase && !t.IsList && t.Name == "bin":
		w.Linef("\t\tstate, err := BinState(len(%s))", ref)
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\tif err := SetU8(%s, state); err != nil { %s }", bufVar, onErr)
		w.Linef("\t\tif err := SetBin(%s, state, %s); err != nil { %s }", bufVar, ref, onErr)
	case t.IsList:
		w.Linef("\t\tstate, err := ListCountState(len(%s))", ref)
		w.Linef("\t\tif err != nil { %s }", onErr)
		w.Linef("\t\tif err := SetU8(%s, state); err != nil { %s }", bufVar, onErr)
		w.Linef("\t\tif err := %s; err != nil { %s }", g.directListSetExpr(t, ref, "state", bufVar), onErr)
	case t.Kind == TplKindStruct:
		w.Linef("\t\tif err := %s(%s, %s); err != nil { %s }", g.structSetName(t.Name), bufVar, ref, onErr)
	case t.Kind == TplKindEnum:
		typeName := PascalCase(t.Name)
		w.Linef("\t\tif !%s(%s) { %s }", g.enumIsAssignableName(typeName), ref, onErr)
		w.Linef("\t\tif err := SetU8(%s, uint8(%s(%s))); err != nil { %s }", bufVar, g.enumNormalizeName(typeName), ref, onErr)
	default:
		w.Linef("\t\tif err := %s(%s, %s); err != nil { %s }", g.primitiveSetter(t.Name), bufVar, ref, onErr)
	}
	w.Line("\t}")
}

func (g *GoGenerator) directListGetExpr(t TplType, stateVar, bufVar string) string {
	switch {
	case t.Name == "bool":
		return fmt.Sprintf("GetBoolListInto(%s, %s, nil)", bufVar, stateVar)
	case t.Name == "text":
		return fmt.Sprintf("GetTextListInto(%s, %s, nil)", bufVar, stateVar)
	case t.Name == "bin":
		return fmt.Sprintf("GetBinListInto(%s, %s, nil)", bufVar, stateVar)
	case t.Kind == TplKindBase:
		_, getter := g.primitiveGetter(t.Name)
		return fmt.Sprintf("GetZeroListInto(%s, %s, nil, %s)", bufVar, stateVar, getter)
	case t.Kind == TplKindEnum:
		return fmt.Sprintf("get%sListBody(%s, %s)", PascalCase(t.Name), bufVar, stateVar)
	default:
		return fmt.Sprintf("get%sListBody(%s, %s)", PascalCase(t.Name), bufVar, stateVar)
	}
}

func (g *GoGenerator) directListSetExpr(t TplType, ref, stateVar, bufVar string) string {
	switch {
	case t.Name == "bool":
		return fmt.Sprintf("SetBoolList(%s, %s, %s)", bufVar, stateVar, ref)
	case t.Name == "text":
		return fmt.Sprintf("SetTextList(%s, %s, %s)", bufVar, stateVar, ref)
	case t.Name == "bin":
		return fmt.Sprintf("SetBinList(%s, %s, %s)", bufVar, stateVar, ref)
	case t.Kind == TplKindBase:
		width, _ := goBaseEncodedWidth(t.Name)
		return fmt.Sprintf("SetZeroList(%s, %s, %s, %d, %s)", bufVar, stateVar, ref, width, g.primitiveSetter(t.Name))
	case t.Kind == TplKindEnum:
		return fmt.Sprintf("set%sListBody(%s, %s, %s)", PascalCase(t.Name), bufVar, stateVar, ref)
	default:
		return fmt.Sprintf("set%sListBody(%s, %s, %s)", PascalCase(t.Name), bufVar, stateVar, ref)
	}
}
