package internal

func renderTsRuntimeSource() string {
	var w sourceWriter
	w.Line("export class Buffer {")
	w.Line("    private _bytes: Uint8Array;")
	w.Line("    private _view: DataView;")
	w.Line("    private _read_offset: number;")
	w.Line("    private _write_offset: number;")
	w.Blank()
	w.Line("    constructor(bytes?: Uint8Array) {")
	w.Line("        if (bytes) {")
	w.Line("            this._bytes = bytes;")
	w.Line("            this._view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);")
	w.Line("            this._read_offset = 0;")
	w.Line("            this._write_offset = bytes.length;")
	w.Line("        } else {")
	w.Line("            const initialCapacity = 128;")
	w.Line("            this._bytes = new Uint8Array(initialCapacity);")
	w.Line("            this._view = new DataView(this._bytes.buffer);")
	w.Line("            this._read_offset = 0;")
	w.Line("            this._write_offset = 0;")
	w.Line("        }")
	w.Line("    }")
	w.Blank()
	w.Line("    public ensureCapacity = (needed: number): void => {")
	w.Line("        const required = this._write_offset + needed;")
	w.Line("        if (required > this._bytes.length) {")
	w.Line("            let newCapacity = this._bytes.length;")
	w.Line("            if (newCapacity === 0) newCapacity = 128;")
	w.Line("            while (newCapacity < required) {")
	w.Line("                newCapacity *= 2;")
	w.Line("            }")
	w.Line("            const newBytes = new Uint8Array(newCapacity);")
	w.Line("            newBytes.set(this._bytes);")
	w.Line("            this._bytes = newBytes;")
	w.Line("            this._view = new DataView(newBytes.buffer);")
	w.Line("        }")
	w.Line("    };")
	w.Blank()
	w.Line("    public read = (byteLength: number): [Uint8Array, Error | null] => {")
	w.Line("        if (this._read_offset + byteLength > this._write_offset) {")
	w.Line("            return [new Uint8Array(0), new Error(\"not enough data\")];")
	w.Line("        }")
	w.Line("        const slice = this._bytes.subarray(this._read_offset, this._read_offset + byteLength);")
	w.Line("        this._read_offset += byteLength;")
	w.Line("        return [slice, null];")
	w.Line("    }")
	w.Blank()
	w.Line("    public write = (data: Uint8Array): Error | null => {")
	w.Line("        this.ensureCapacity(data.length);")
	w.Line("        this._bytes.set(data, this._write_offset);")
	w.Line("        this._write_offset += data.length;")
	w.Line("        return null;")
	w.Line("    }")
	w.Blank()
	w.Line("    get read_offset(): number { return this._read_offset; }")
	w.Line("    get write_offset(): number { return this._write_offset; }")
	w.Line("    get view(): DataView { return this._view; }")
	w.Line("    get bytes(): Uint8Array { return this._bytes.subarray(0, this._write_offset); }")
	w.Line("    get len(): number { return this._write_offset - this._read_offset; }")
	w.Line("}")
	w.Blank()
	w.Line("export interface Serializable {")
	w.Line("    set: (buf: Buffer) => Error | null;")
	w.Line("}")
	w.Blank()
	w.Line("export interface Deserializable {")
	w.Line("    get: (buf: Buffer) => Error | null;")
	w.Line("}")
	w.Blank()
	w.Line("// Bit Operations")
	w.Line("export const GetBit = (bits: Uint8Array, i: number): boolean => {")
	w.Line("    const byteIndex = Math.floor(i / 8);")
	w.Line("    if (byteIndex >= bits.length) return false;")
	w.Line("    const bitIndex = i % 8;")
	w.Line("    return (bits[byteIndex] & (1 << bitIndex)) !== 0;")
	w.Line("};")
	w.Blank()
	w.Line("export const SetBit = (bits: Uint8Array, i: number, value: boolean): void => {")
	w.Line("    const byteIndex = Math.floor(i / 8);")
	w.Line("    if (byteIndex >= bits.length) return;")
	w.Line("    const bitIndex = i % 8;")
	w.Line("    if (value) {")
	w.Line("        bits[byteIndex] |= (1 << bitIndex);")
	w.Line("    } else {")
	w.Line("        bits[byteIndex] &= ~(1 << bitIndex);")
	w.Line("    }")
	w.Line("};")
	w.Blank()
	w.Line("const _setNum = (buf: Buffer, byteLength: number, value: number | bigint, setter: string): void => {")
	w.Line("    buf.ensureCapacity(byteLength);")
	w.Line("    (buf.view as any)[setter](buf.write_offset, value, true);")
	w.Line("    (buf as any)._write_offset += byteLength;")
	w.Line("};")
	w.Blank()
	w.Line("const _checkRead = (buf: Buffer, len: number): Error | null => {")
	w.Line("    if (buf.len < len) return new Error(\"not enough data\");")
	w.Line("    return null;")
	w.Line("};")
	w.Blank()
	w.Line("// List Helpers")
	w.Line("export const getList = <T>(buf: Buffer, getter: (buf: Buffer) => [T, Error | null]): [T[], Error | null] => {")
	w.Line("    const [count, err] = getU16(buf);")
	w.Line("    if (err !== null) return [[], err];")
	w.Line("    const list: T[] = new Array(count);")
	w.Line("    for (let i = 0; i < count; i++) {")
	w.Line("        const [item, err2] = getter(buf);")
	w.Line("        if (err2 !== null) return [[], err2];")
	w.Line("        list[i] = item;")
	w.Line("    }")
	w.Line("    return [list, null];")
	w.Line("};")
	w.Blank()
	w.Line("export const setList = <T>(buf: Buffer, list: T[], setter: (buf: Buffer, val: T) => Error | null): Error | null => {")
	w.Line("    if (list.length > 65535) return new Error(`list length ${list.length} exceeds u16 max`);")
	w.Line("    const err = setU16(buf, list.length);")
	w.Line("    if (err !== null) return err;")
	w.Line("    for (const item of list) {")
	w.Line("        const err2 = setter(buf, item);")
	w.Line("        if (err2 !== null) return err2;")
	w.Line("    }")
	w.Line("    return null;")
	w.Line("};")
	w.Blank()
	w.Line("export const eqList = <T>(a: T[], b: T[], eq: (a: T, b: T) => boolean): boolean => {")
	w.Line("    if (a === b) return true;")
	w.Line("    if (a === null || b === null) return false;")
	w.Line("    if (a.length !== b.length) return false;")
	w.Line("    for (let i = 0; i < a.length; i++) {")
	w.Line("        if (!eq(a[i], b[i])) return false;")
	w.Line("    }")
	w.Line("    return true;")
	w.Line("};")
	w.Blank()
	w.Line("// Primitives")
	w.Line("export const getU8 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 1);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getUint8(buf.read_offset);")
	w.Line("    (buf as any)._read_offset += 1;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setU8 = (buf: Buffer, v: number): Error | null => {")
	w.Line("    _setNum(buf, 1, v, 'setUint8');")
	w.Line("    return null;")
	w.Line("};")
	w.Line("export const eqU8 = (a: number, b: number): boolean => a === b;")
	w.Blank()
	w.Line("export const getU16 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 2);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getUint16(buf.read_offset, true);")
	w.Line("    (buf as any)._read_offset += 2;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setU16 = (buf: Buffer, v: number): Error | null => {")
	w.Line("    _setNum(buf, 2, v, 'setUint16');")
	w.Line("    return null;")
	w.Line("};")
	w.Line("export const eqU16 = (a: number, b: number): boolean => a === b;")
	w.Blank()
	w.Line("export const getU32 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 4);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getUint32(buf.read_offset, true);")
	w.Line("    (buf as any)._read_offset += 4;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setU32 = (buf: Buffer, v: number): Error | null => {")
	w.Line("    _setNum(buf, 4, v, 'setUint32');")
	w.Line("    return null;")
	w.Line("};")
	w.Line("export const eqU32 = (a: number, b: number): boolean => a === b;")
	w.Blank()
	w.Line("export const getI8 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 1);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getInt8(buf.read_offset);")
	w.Line("    (buf as any)._read_offset += 1;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setI8 = (buf: Buffer, v: number): Error | null => {")
	w.Line("    _setNum(buf, 1, v, 'setInt8');")
	w.Line("    return null;")
	w.Line("};")
	w.Line("export const eqI8 = (a: number, b: number): boolean => a === b;")
	w.Blank()
	w.Line("export const getI16 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 2);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getInt16(buf.read_offset, true);")
	w.Line("    (buf as any)._read_offset += 2;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setI16 = (buf: Buffer, v: number): Error | null => {")
	w.Line("    _setNum(buf, 2, v, 'setInt16');")
	w.Line("    return null;")
	w.Line("};")
	w.Line("export const eqI16 = (a: number, b: number): boolean => a === b;")
	w.Blank()
	w.Line("export const getI32 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 4);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getInt32(buf.read_offset, true);")
	w.Line("    (buf as any)._read_offset += 4;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setI32 = (buf: Buffer, v: number): Error | null => {")
	w.Line("    _setNum(buf, 4, v, 'setInt32');")
	w.Line("    return null;")
	w.Line("};")
	w.Line("export const eqI32 = (a: number, b: number): boolean => a === b;")
	w.Blank()
	w.Line("export const getI64 = (buf: Buffer): [bigint, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 8);")
	w.Line("    if (err !== null) return [0n, err];")
	w.Line("    const v = buf.view.getBigInt64(buf.read_offset, true);")
	w.Line("    (buf as any)._read_offset += 8;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setI64 = (buf: Buffer, v: bigint): Error | null => {")
	w.Line("    _setNum(buf, 8, v, 'setBigInt64');")
	w.Line("    return null;")
	w.Line("};")
	w.Line("export const eqI64 = (a: bigint, b: bigint): boolean => a === b;")
	w.Blank()
	w.Line("export const getU64 = (buf: Buffer): [bigint, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 8);")
	w.Line("    if (err !== null) return [0n, err];")
	w.Line("    const v = buf.view.getBigUint64(buf.read_offset, true);")
	w.Line("    (buf as any)._read_offset += 8;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setU64 = (buf: Buffer, v: bigint): Error | null => {")
	w.Line("    _setNum(buf, 8, v, 'setBigUint64');")
	w.Line("    return null;")
	w.Line("};")
	w.Line("export const eqU64 = (a: bigint, b: bigint): boolean => a === b;")
	w.Blank()
	w.Line("export const getF32 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 4);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getFloat32(buf.read_offset, true);")
	w.Line("    (buf as any)._read_offset += 4;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setF32 = (buf: Buffer, v: number): Error | null => {")
	w.Line("    _setNum(buf, 4, v, 'setFloat32');")
	w.Line("    return null;")
	w.Line("};")
	w.Line("export const eqF32 = (a: number, b: number): boolean => Math.abs(a - b) < 1e-6;")
	w.Blank()
	w.Line("export const getF64 = (buf: Buffer): [number, Error | null] => {")
	w.Line("    const err = _checkRead(buf, 8);")
	w.Line("    if (err !== null) return [0, err];")
	w.Line("    const v = buf.view.getFloat64(buf.read_offset, true);")
	w.Line("    (buf as any)._read_offset += 8;")
	w.Line("    return [v, null];")
	w.Line("};")
	w.Line("export const setF64 = (buf: Buffer, v: number): Error | null => {")
	w.Line("    _setNum(buf, 8, v, 'setFloat64');")
	w.Line("    return null;")
	w.Line("};")
	w.Line("export const eqF64 = (a: number, b: number): boolean => Math.abs(a - b) < 1e-9;")
	w.Blank()
	w.Line("export const getBool = (buf: Buffer): [boolean, Error | null] => {")
	w.Line("    const [v, err] = getU8(buf);")
	w.Line("    if (err !== null) return [false, err];")
	w.Line("    return [v === 1, null];")
	w.Line("};")
	w.Line("export const setBool = (buf: Buffer, value: boolean): Error | null => setU8(buf, value ? 1 : 0);")
	w.Line("export const eqBool = (a: boolean, b: boolean): boolean => a === b;")
	w.Blank()
	w.Line("export const getBin = (buf: Buffer): [Uint8Array, Error | null] => {")
	w.Line("    const [len, err] = getU32(buf);")
	w.Line("    if (err !== null) return [new Uint8Array(0), err];")
	w.Line("    return buf.read(Number(len));")
	w.Line("};")
	w.Line("export const setBin = (buf: Buffer, value: Uint8Array): Error | null => {")
	w.Line("    if (value.length > 4294967295) return new Error(`bin length ${value.length} exceeds u32 max`);")
	w.Line("    const err = setU32(buf, value.length);")
	w.Line("    if (err !== null) return err;")
	w.Line("    return buf.write(value);")
	w.Line("};")
	w.Line("export const eqBin = (a: Uint8Array, b: Uint8Array): boolean => {")
	w.Line("    if (a === b) return true;")
	w.Line("    if (a === null || b === null) return false;")
	w.Line("    if (a.length !== b.length) return false;")
	w.Line("    for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;")
	w.Line("    return true;")
	w.Line("};")
	w.Blank()
	w.Line("export const getText = (buf: Buffer): [string, Error | null] => {")
	w.Line("    const [len, err] = getU16(buf);")
	w.Line("    if (err !== null) return [\"\", err];")
	w.Line("    const [data, err2] = buf.read(len);")
	w.Line("    if (err2 !== null) return [\"\", err2];")
	w.Line("    return [new TextDecoder().decode(data), null];")
	w.Line("};")
	w.Line("export const setText = (buf: Buffer, value: string): Error | null => {")
	w.Line("    const data = new TextEncoder().encode(value);")
	w.Line("    if (data.length > 65535) return new Error(`text length ${data.length} exceeds u16 max`);")
	w.Line("    const err = setU16(buf, data.length);")
	w.Line("    if (err !== null) return err;")
	w.Line("    return buf.write(data);")
	w.Line("};")
	w.Line("export const eqText = (a: string, b: string): boolean => a === b;")
	w.Blank()
	w.Line("export const getBoolList = (buf: Buffer): [boolean[], Error | null] => {")
	w.Line("    const [count, err] = getU16(buf);")
	w.Line("    if (err !== null) return [[], err];")
	w.Line("    const [bits, errBits] = buf.read(Math.ceil(count / 8));")
	w.Line("    if (errBits !== null) return [[], errBits];")
	w.Line("    const list: boolean[] = new Array(count);")
	w.Line("    for (let i = 0; i < count; i++) list[i] = GetBit(bits, i);")
	w.Line("    return [list, null];")
	w.Line("};")
	w.Line("export const setBoolList = (buf: Buffer, v: boolean[]): Error | null => {")
	w.Line("    if (v.length > 65535) return new Error(`list length ${v.length} exceeds u16 max`);")
	w.Line("    const err = setU16(buf, v.length);")
	w.Line("    if (err !== null) return err;")
	w.Line("    const bits = new Uint8Array(Math.ceil(v.length / 8));")
	w.Line("    for (let i = 0; i < v.length; i++) SetBit(bits, i, v[i]);")
	w.Line("    return buf.write(bits);")
	w.Line("};")
	w.Line("export const eqBoolList = (a: boolean[], b: boolean[]): boolean => eqList(a, b, eqBool);")
	w.Blank()
	w.Line("export const getI8List = (buf: Buffer): [number[], Error | null] => getList(buf, getI8);")
	w.Line("export const setI8List = (buf: Buffer, v: number[]): Error | null => setList(buf, v, setI8);")
	w.Line("export const eqI8List = (a: number[], b: number[]): boolean => eqList(a, b, eqI8);")
	w.Blank()
	w.Line("export const getU8List = (buf: Buffer): [number[], Error | null] => getList(buf, getU8);")
	w.Line("export const setU8List = (buf: Buffer, v: number[]): Error | null => setList(buf, v, setU8);")
	w.Line("export const eqU8List = (a: number[], b: number[]): boolean => eqList(a, b, eqU8);")
	w.Blank()
	w.Line("export const getI16List = (buf: Buffer): [number[], Error | null] => getList(buf, getI16);")
	w.Line("export const setI16List = (buf: Buffer, v: number[]): Error | null => setList(buf, v, setI16);")
	w.Line("export const eqI16List = (a: number[], b: number[]): boolean => eqList(a, b, eqI16);")
	w.Blank()
	w.Line("export const getU16List = (buf: Buffer): [number[], Error | null] => getList(buf, getU16);")
	w.Line("export const setU16List = (buf: Buffer, v: number[]): Error | null => setList(buf, v, setU16);")
	w.Line("export const eqU16List = (a: number[], b: number[]): boolean => eqList(a, b, eqU16);")
	w.Blank()
	w.Line("export const getI32List = (buf: Buffer): [number[], Error | null] => getList(buf, getI32);")
	w.Line("export const setI32List = (buf: Buffer, v: number[]): Error | null => setList(buf, v, setI32);")
	w.Line("export const eqI32List = (a: number[], b: number[]): boolean => eqList(a, b, eqI32);")
	w.Blank()
	w.Line("export const getU32List = (buf: Buffer): [number[], Error | null] => getList(buf, getU32);")
	w.Line("export const setU32List = (buf: Buffer, v: number[]): Error | null => setList(buf, v, setU32);")
	w.Line("export const eqU32List = (a: number[], b: number[]): boolean => eqList(a, b, eqU32);")
	w.Blank()
	w.Line("export const getI64List = (buf: Buffer): [bigint[], Error | null] => getList(buf, getI64);")
	w.Line("export const setI64List = (buf: Buffer, v: bigint[]): Error | null => setList(buf, v, setI64);")
	w.Line("export const eqI64List = (a: bigint[], b: bigint[]): boolean => eqList(a, b, eqI64);")
	w.Blank()
	w.Line("export const getU64List = (buf: Buffer): [bigint[], Error | null] => getList(buf, getU64);")
	w.Line("export const setU64List = (buf: Buffer, v: bigint[]): Error | null => setList(buf, v, setU64);")
	w.Line("export const eqU64List = (a: bigint[], b: bigint[]): boolean => eqList(a, b, eqU64);")
	w.Blank()
	w.Line("export const getF32List = (buf: Buffer): [number[], Error | null] => getList(buf, getF32);")
	w.Line("export const setF32List = (buf: Buffer, v: number[]): Error | null => setList(buf, v, setF32);")
	w.Line("export const eqF32List = (a: number[], b: number[]): boolean => eqList(a, b, eqF32);")
	w.Blank()
	w.Line("export const getF64List = (buf: Buffer): [number[], Error | null] => getList(buf, getF64);")
	w.Line("export const setF64List = (buf: Buffer, v: number[]): Error | null => setList(buf, v, setF64);")
	w.Line("export const eqF64List = (a: number[], b: number[]): boolean => eqList(a, b, eqF64);")
	w.Blank()
	w.Line("export const getBinList = (buf: Buffer): [Uint8Array[], Error | null] => getList(buf, getBin);")
	w.Line("export const setBinList = (buf: Buffer, v: Uint8Array[]): Error | null => setList(buf, v, setBin);")
	w.Line("export const eqBinList = (a: Uint8Array[], b: Uint8Array[]): boolean => eqList(a, b, eqBin);")
	w.Blank()
	w.Line("export const getTextList = (buf: Buffer): [string[], Error | null] => getList(buf, getText);")
	w.Line("export const setTextList = (buf: Buffer, v: string[]): Error | null => setList(buf, v, setText);")
	w.Line("export const eqTextList = (a: string[], b: string[]): boolean => eqList(a, b, eqText);")
	w.Blank()
	w.Line("// SetAll performs batch set operations. Supports values or functions.")
	w.Line("export const setAll = (buf: Buffer, ...args: any[]): Error | null => {")
	w.Line("    for (const arg of args) {")
	w.Line("        let err: Error | null = null;")
	w.Line("        if (typeof arg === 'function') {")
	w.Line("            err = arg(buf);")
	w.Line("        } else if (arg && typeof arg === 'object' && 'set' in arg && typeof arg.set === 'function') {")
	w.Line("            err = arg.set(buf);")
	w.Line("        } else if (typeof arg === 'string') {")
	w.Line("            err = setText(buf, arg);")
	w.Line("        } else if (typeof arg === 'boolean') {")
	w.Line("            err = setBool(buf, arg);")
	w.Line("        } else if (typeof arg === 'bigint') {")
	w.Line("            err = setI64(buf, arg);")
	w.Line("        } else if (arg instanceof Uint8Array) {")
	w.Line("            err = setBin(buf, arg);")
	w.Line("        } else {")
	w.Line("            return new Error(`setAll: unsupported type ${typeof arg}. Use wrappers for numbers.`);")
	w.Line("        }")
	w.Line("        if (err !== null) return err;")
	w.Line("    }")
	w.Line("    return null;")
	w.Line("};")
	w.Blank()
	w.Line("// GetAll performs batch get operations. Supports functions or objects with get().")
	w.Line("export const getAll = (buf: Buffer, ...args: (any)[]): Error | null => {")
	w.Line("    for (const arg of args) {")
	w.Line("        let err: Error | null = null;")
	w.Line("        if (typeof arg === 'function') {")
	w.Line("            err = arg(buf);")
	w.Line("        } else if (arg && typeof arg === 'object' && 'get' in arg && typeof arg.get === 'function') {")
	w.Line("            err = arg.get(buf);")
	w.Line("        } else {")
	w.Line("            return new Error(\"getAll: argument must be a function or have a get() method\");")
	w.Line("        }")
	w.Line("        if (err !== null) return err;")
	w.Line("    }")
	w.Line("    return null;")
	w.Line("};")
	w.Blank()
	w.Line("// Helpers to match Go's GetAny logic for primitives via closure update")
	w.Line("export const into = <T>(target: { value: T }, getter: (buf: Buffer) => [T, Error | null]) => (buf: Buffer) => {")
	w.Line("    const [v, e] = getter(buf);")
	w.Line("    if (e === null) target.value = v;")
	w.Line("    return e;")
	w.Line("};")
	w.Blank()
	w.Line("// Convenience wrappers for TS numbers")
	w.Line("export const u8 = (v: number) => (buf: Buffer) => setU8(buf, v);")
	w.Line("export const u8List = (v: number[]) => (buf: Buffer) => setU8List(buf, v);")
	w.Line("export const u16 = (v: number) => (buf: Buffer) => setU16(buf, v);")
	w.Line("export const u32 = (v: number) => (buf: Buffer) => setU32(buf, v);")
	w.Line("export const i8 = (v: number) => (buf: Buffer) => setI8(buf, v);")
	w.Line("export const i16 = (v: number) => (buf: Buffer) => setI16(buf, v);")
	w.Line("export const i32 = (v: number) => (buf: Buffer) => setI32(buf, v);")
	w.Line("export const f32 = (v: number) => (buf: Buffer) => setF32(buf, v);")
	w.Line("export const f64 = (v: number) => (buf: Buffer) => setF64(buf, v);")
	w.Line("export const bool = (v: boolean) => (buf: Buffer) => setBool(buf, v);")
	w.Line("export const bin = (v: Uint8Array) => (buf: Buffer) => setBin(buf, v);")
	w.Line("export const text = (v: string) => (buf: Buffer) => setText(buf, v);")
	return w.String()
}
