package internal

func (g *GoGenerator) renderAPIStub(api TplApi) []byte {
	apiName := SnakeCase(api.Name)
	var w sourceWriter
	w.Line("package sb")
	w.Blank()
	w.Line("import (")
	w.Line("\t\"context\"")
	w.Line(")")
	w.Blank()
	if api.Result.Name == "nil" {
		w.Linef("func %s(ctx context.Context%s) (errCode RpcErrCode) {", apiName, g.stubArgs(api.Args))
		w.Line("\treturn RpcRespErr")
		w.Line("}")
		return []byte(w.String())
	}
	w.Linef("func %s(ctx context.Context%s) (result %s, errCode RpcErrCode) {", apiName, g.stubArgs(api.Args), g.logicType(api.Result))
	w.Linef("\treturn %s, RpcRespErr", g.defaultReturn(api.Result))
	w.Line("}")
	return []byte(w.String())
}

func (g *GoGenerator) renderAPIFile(apis []TplApi) string {
	var w sourceWriter
	w.Line("package sb")
	w.Blank()
	w.Line("import (")
	w.Line("\t\"bytes\"")
	w.Line("\t\"context\"")
	w.Line("\t\"io\"")
	w.Line("\t\"net/http\"")
	w.Line("\t\"slices\"")
	w.Line("\t\"sync\"")
	w.Line("\t\"time\"")
	w.Line("")
	w.Line(")")
	w.Blank()
	w.Line("// Code generated by sb generator. DO NOT EDIT.")
	w.Line("var _ = slices.Equal[[]int, int]")
	w.Line("var _ = HeaderSize")
	w.Blank()
	w.Line("// --- API Handlers ---")
	for _, api := range apis {
		g.renderAPIHandler(&w, api)
	}
	w.Blank()
	g.renderAPIRoutesAndHelpers(&w, apis)
	return w.String()
}
func (g *GoGenerator) renderAPIRoutesAndHelpers(w *sourceWriter, apis []TplApi) {
	groups := groupAPIs(apis)
	w.Line("// --- 路由注册 ---")
	w.Blank()
	g.renderAPIMiddleware(w)
	g.renderAPIRouteRegistrations(w, groups)
	g.renderAPIHTTPHelpers(w)
}
