package internal

func renderGoRuntimeSource() string {
	var w sourceWriter
	w.Line("package sb")
	w.Blank()
	w.Line("import (")
	w.Line("\t\"bytes\"")
	w.Line("\t\"encoding/binary\"")
	w.Line("\t\"fmt\"")
	w.Line("\t\"math\"")
	w.Line("\t\"slices\"")
	w.Line(")")
	w.Blank()
	w.Line("type Setter func(*bytes.Buffer) error")
	w.Line("type Getter func(*bytes.Buffer) error")
	w.Blank()
	w.Line("func SetAll(buf *bytes.Buffer, args ...Setter) error {")
	w.Line("\tfor i, arg := range args {")
	w.Line("\t\tif arg == nil { return fmt.Errorf(\"SetAll arg[%d] is nil\", i) }")
	w.Line("\t\tif err := arg(buf); err != nil { return err }")
	w.Line("\t}")
	w.Line("\treturn nil")
	w.Line("}")
	w.Blank()
	w.Line("func GetAll(buf *bytes.Buffer, args ...Getter) error {")
	w.Line("\tfor i, arg := range args {")
	w.Line("\t\tif arg == nil { return fmt.Errorf(\"GetAll arg[%d] is nil\", i) }")
	w.Line("\t\tif err := arg(buf); err != nil { return err }")
	w.Line("\t}")
	w.Line("\treturn nil")
	w.Line("}")
	w.Blank()
	w.Line("// Helpers")
	w.Line("func getList[T any, L ~[]T](buf *bytes.Buffer, getItem func(*bytes.Buffer) (T, error)) (L, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\tlist := make([]T, count)")
	w.Line("\tfor i := range list {")
	w.Line("\t\tif list[i], err = getItem(buf); err != nil { return nil, err }")
	w.Line("\t}")
	w.Line("\treturn L(list), nil")
	w.Line("}")
	w.Blank()
	w.Line("func setList[T any](buf *bytes.Buffer, list []T, setItem func(*bytes.Buffer, T) error) error {")
	w.Line("\tif len(list) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tif err := SetU16(buf, uint16(len(list))); err != nil { return err }")
	w.Line("\tfor _, item := range list {")
	w.Line("\t\tif err := setItem(buf, item); err != nil { return err }")
	w.Line("\t}")
	w.Line("\treturn nil")
	w.Line("}")
	w.Blank()
	w.Line("func sizeFixedList(length int, elemSize int) (int, error) {")
	w.Line("\tif length > 65535 { return 0, fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\treturn 2 + length*elemSize, nil")
	w.Line("}")
	w.Blank()
	w.Line("func sizeBoolList(v []bool) (int, error) {")
	w.Line("\tif len(v) > 65535 { return 0, fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\treturn 2 + (len(v)+7)/8, nil")
	w.Line("}")
	w.Blank()
	w.Line("func sizeBin(v []byte) (int, error) {")
	w.Line("\tif uint64(len(v)) > uint64(^uint32(0)) { return 0, fmt.Errorf(\"bin length exceeds uint32 max\") }")
	w.Line("\treturn 4 + len(v), nil")
	w.Line("}")
	w.Blank()
	w.Line("func sizeBinList(v [][]byte) (int, error) {")
	w.Line("\tif len(v) > 65535 { return 0, fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tsize := 2")
	w.Line("\tfor i, item := range v {")
	w.Line("\t\titemSize, err := sizeBin(item)")
	w.Line("\t\tif err != nil { return 0, fmt.Errorf(\"bin list[%d]: %w\", i, err) }")
	w.Line("\t\tsize += itemSize")
	w.Line("\t}")
	w.Line("\treturn size, nil")
	w.Line("}")
	w.Blank()
	w.Line("func sizeText(v string) (int, error) {")
	w.Line("\tif len(v) > 65535 { return 0, fmt.Errorf(\"text length exceeds uint16 max\") }")
	w.Line("\treturn 2 + len(v), nil")
	w.Line("}")
	w.Blank()
	w.Line("func sizeTextList(v []string) (int, error) {")
	w.Line("\tif len(v) > 65535 { return 0, fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tsize := 2")
	w.Line("\tfor i, item := range v {")
	w.Line("\t\titemSize, err := sizeText(item)")
	w.Line("\t\tif err != nil { return 0, fmt.Errorf(\"text list[%d]: %w\", i, err) }")
	w.Line("\t\tsize += itemSize")
	w.Line("\t}")
	w.Line("\treturn size, nil")
	w.Line("}")
	w.Blank()
	w.Line("func GetBit(bits []byte, i uint8) bool {")
	w.Line("\tif int(i/8) >= len(bits) { return false }")
	w.Line("\treturn (bits[i/8] & (1 << (i % 8))) != 0")
	w.Line("}")
	w.Blank()
	w.Line("func SetBit(bits []byte, i uint8, v bool) {")
	w.Line("\tif int(i/8) >= len(bits) { return }")
	w.Line("\tif v { bits[i/8] |= (1 << (i % 8)) } else { bits[i/8] &= ^(1 << (i % 8)) }")
	w.Line("}")
	w.Blank()
	w.Line("// Bool")
	w.Line("type Bool bool")
	w.Line("func GetBool(buf *bytes.Buffer) (bool, error) {")
	w.Line("\tb, err := buf.ReadByte()")
	w.Line("\treturn b == 1, err")
	w.Line("}")
	w.Line("func SetBool(buf *bytes.Buffer, v bool) error {")
	w.Line("\tif v { return buf.WriteByte(1) }")
	w.Line("\treturn buf.WriteByte(0)")
	w.Line("}")
	w.Line("func EqBool(a, b bool) bool { return a == b }")
	w.Blank()
	w.Line("type BoolList []bool")
	w.Line("func GetBoolList(buf *bytes.Buffer) ([]bool, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\tbitSize := (int(count) + 7) / 8")
	w.Line("\tif buf.Len() < bitSize { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\tbits := buf.Next(bitSize)")
	w.Line("\tbools := make([]bool, int(count))")
	w.Line("\tfor i := 0; i < int(count); i++ { bools[i] = GetBit(bits, uint8(i)) }")
	w.Line("\treturn bools, nil")
	w.Line("}")
	w.Line("func SetBoolList(buf *bytes.Buffer, v []bool) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tbitSize := (len(v) + 7) / 8")
	w.Line("\tbuf.Grow(2 + bitSize)")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tb = binary.LittleEndian.AppendUint16(b, uint16(len(v)))")
	w.Line("\tstart := len(b)")
	w.Line("\tfor i := 0; i < bitSize; i++ { b = append(b, 0) }")
	w.Line("\tfor i, val := range v {")
	w.Line("\t\tif val { b[start+(i/8)] |= 1 << (uint(i) % 8) }")
	w.Line("\t}")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqBoolList(a, b []bool) bool { return slices.Equal(a, b) }")
	w.Blank()
	w.Line("// Primitives Macro")
	w.Line("type I8 int8")
	w.Line("func GetI8(buf *bytes.Buffer) (int8, error) {")
	w.Line("\tb, err := buf.ReadByte()")
	w.Line("\treturn int8(b), err")
	w.Line("}")
	w.Line("func SetI8(buf *bytes.Buffer, v int8) error {")
	w.Line("\treturn buf.WriteByte(uint8(v))")
	w.Line("}")
	w.Line("func EqI8(a, b int8) bool { return a == b }")
	w.Blank()
	w.Line("type I8List []int8")
	w.Line("func GetI8List(buf *bytes.Buffer) ([]int8, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\tif buf.Len() < int(count) { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\tdata := buf.Next(int(count))")
	w.Line("\tlist := make([]int8, count)")
	w.Line("\tfor i := range list { list[i] = int8(data[i]) }")
	w.Line("\treturn list, nil")
	w.Line("}")
	w.Line("func SetI8List(buf *bytes.Buffer, v []int8) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tbuf.Grow(2 + len(v))")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tif len(v) == 0 { return nil }")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tfor _, item := range v { b = append(b, byte(item)) }")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqI8List(a, b []int8) bool { return slices.Equal(a, b) }")
	w.Line("type U8 uint8")
	w.Line("func GetU8(buf *bytes.Buffer) (uint8, error) {")
	w.Line("\tb, err := buf.ReadByte()")
	w.Line("\treturn uint8(b), err")
	w.Line("}")
	w.Line("func SetU8(buf *bytes.Buffer, v uint8) error {")
	w.Line("\treturn buf.WriteByte(uint8(v))")
	w.Line("}")
	w.Line("func EqU8(a, b uint8) bool { return a == b }")
	w.Blank()
	w.Line("type U8List []uint8")
	w.Line("func GetU8List(buf *bytes.Buffer) ([]uint8, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\tif buf.Len() < int(count) { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\treturn bytes.Clone(buf.Next(int(count))), nil")
	w.Line("}")
	w.Line("func SetU8List(buf *bytes.Buffer, v []uint8) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tbuf.Grow(2 + len(v))")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tif len(v) == 0 { return nil }")
	w.Line("\t_, err := buf.Write(v)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqU8List(a, b []uint8) bool { return slices.Equal(a, b) }")
	w.Line("type I16 int16")
	w.Line("func GetI16(buf *bytes.Buffer) (int16, error) {")
	w.Line("\tvar b [2]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn int16(binary.LittleEndian.Uint16(b[:])), nil")
	w.Line("}")
	w.Line("func SetI16(buf *bytes.Buffer, v int16) error {")
	w.Line("\tbuf.Grow(2)")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tb = binary.LittleEndian.AppendUint16(b, uint16(v))")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqI16(a, b int16) bool { return a == b }")
	w.Blank()
	w.Line("type I16List []int16")
	w.Line("func GetI16List(buf *bytes.Buffer) ([]int16, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\ttotalSize := int(count) * 2")
	w.Line("\tif buf.Len() < totalSize { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\tdata := buf.Next(totalSize)")
	w.Line("\tlist := make([]int16, count)")
	w.Line("\tfor i := range list { list[i] = int16(binary.LittleEndian.Uint16(data[i*2:])) }")
	w.Line("\treturn list, nil")
	w.Line("}")
	w.Line("func SetI16List(buf *bytes.Buffer, v []int16) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tbuf.Grow(2 + len(v)*2)")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tif len(v) == 0 { return nil }")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tfor _, item := range v { b = binary.LittleEndian.AppendUint16(b, uint16(item)) }")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqI16List(a, b []int16) bool { return slices.Equal(a, b) }")
	w.Line("type U16 uint16")
	w.Line("func GetU16(buf *bytes.Buffer) (uint16, error) {")
	w.Line("\tvar b [2]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn uint16(binary.LittleEndian.Uint16(b[:])), nil")
	w.Line("}")
	w.Line("func SetU16(buf *bytes.Buffer, v uint16) error {")
	w.Line("\tbuf.Grow(2)")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tb = binary.LittleEndian.AppendUint16(b, uint16(v))")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqU16(a, b uint16) bool { return a == b }")
	w.Blank()
	w.Line("type U16List []uint16")
	w.Line("func GetU16List(buf *bytes.Buffer) ([]uint16, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\ttotalSize := int(count) * 2")
	w.Line("\tif buf.Len() < totalSize { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\tdata := buf.Next(totalSize)")
	w.Line("\tlist := make([]uint16, count)")
	w.Line("\tfor i := range list { list[i] = binary.LittleEndian.Uint16(data[i*2:]) }")
	w.Line("\treturn list, nil")
	w.Line("}")
	w.Line("func SetU16List(buf *bytes.Buffer, v []uint16) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tbuf.Grow(2 + len(v)*2)")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tif len(v) == 0 { return nil }")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tfor _, item := range v { b = binary.LittleEndian.AppendUint16(b, item) }")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqU16List(a, b []uint16) bool { return slices.Equal(a, b) }")
	w.Line("type I32 int32")
	w.Line("func GetI32(buf *bytes.Buffer) (int32, error) {")
	w.Line("\tvar b [4]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn int32(binary.LittleEndian.Uint32(b[:])), nil")
	w.Line("}")
	w.Line("func SetI32(buf *bytes.Buffer, v int32) error {")
	w.Line("\tbuf.Grow(4)")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tb = binary.LittleEndian.AppendUint32(b, uint32(v))")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqI32(a, b int32) bool { return a == b }")
	w.Blank()
	w.Line("type I32List []int32")
	w.Line("func GetI32List(buf *bytes.Buffer) ([]int32, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\ttotalSize := int(count) * 4")
	w.Line("\tif buf.Len() < totalSize { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\tdata := buf.Next(totalSize)")
	w.Line("\tlist := make([]int32, count)")
	w.Line("\tfor i := range list { list[i] = int32(binary.LittleEndian.Uint32(data[i*4:])) }")
	w.Line("\treturn list, nil")
	w.Line("}")
	w.Line("func SetI32List(buf *bytes.Buffer, v []int32) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tbuf.Grow(2 + len(v)*4)")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tif len(v) == 0 { return nil }")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tfor _, item := range v { b = binary.LittleEndian.AppendUint32(b, uint32(item)) }")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqI32List(a, b []int32) bool { return slices.Equal(a, b) }")
	w.Line("type U32 uint32")
	w.Line("func GetU32(buf *bytes.Buffer) (uint32, error) {")
	w.Line("\tvar b [4]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn uint32(binary.LittleEndian.Uint32(b[:])), nil")
	w.Line("}")
	w.Line("func SetU32(buf *bytes.Buffer, v uint32) error {")
	w.Line("\tbuf.Grow(4)")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tb = binary.LittleEndian.AppendUint32(b, uint32(v))")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqU32(a, b uint32) bool { return a == b }")
	w.Blank()
	w.Line("type U32List []uint32")
	w.Line("func GetU32List(buf *bytes.Buffer) ([]uint32, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\ttotalSize := int(count) * 4")
	w.Line("\tif buf.Len() < totalSize { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\tdata := buf.Next(totalSize)")
	w.Line("\tlist := make([]uint32, count)")
	w.Line("\tfor i := range list { list[i] = binary.LittleEndian.Uint32(data[i*4:]) }")
	w.Line("\treturn list, nil")
	w.Line("}")
	w.Line("func SetU32List(buf *bytes.Buffer, v []uint32) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tbuf.Grow(2 + len(v)*4)")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tif len(v) == 0 { return nil }")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tfor _, item := range v { b = binary.LittleEndian.AppendUint32(b, item) }")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqU32List(a, b []uint32) bool { return slices.Equal(a, b) }")
	w.Line("type I64 int64")
	w.Line("func GetI64(buf *bytes.Buffer) (int64, error) {")
	w.Line("\tvar b [8]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn int64(binary.LittleEndian.Uint64(b[:])), nil")
	w.Line("}")
	w.Line("func SetI64(buf *bytes.Buffer, v int64) error {")
	w.Line("\tbuf.Grow(8)")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tb = binary.LittleEndian.AppendUint64(b, uint64(v))")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqI64(a, b int64) bool { return a == b }")
	w.Blank()
	w.Line("type I64List []int64")
	w.Line("func GetI64List(buf *bytes.Buffer) ([]int64, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\ttotalSize := int(count) * 8")
	w.Line("\tif buf.Len() < totalSize { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\tdata := buf.Next(totalSize)")
	w.Line("\tlist := make([]int64, count)")
	w.Line("\tfor i := range list { list[i] = int64(binary.LittleEndian.Uint64(data[i*8:])) }")
	w.Line("\treturn list, nil")
	w.Line("}")
	w.Line("func SetI64List(buf *bytes.Buffer, v []int64) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tbuf.Grow(2 + len(v)*8)")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tif len(v) == 0 { return nil }")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tfor _, item := range v { b = binary.LittleEndian.AppendUint64(b, uint64(item)) }")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqI64List(a, b []int64) bool { return slices.Equal(a, b) }")
	w.Line("type U64 uint64")
	w.Line("func GetU64(buf *bytes.Buffer) (uint64, error) {")
	w.Line("\tvar b [8]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn uint64(binary.LittleEndian.Uint64(b[:])), nil")
	w.Line("}")
	w.Line("func SetU64(buf *bytes.Buffer, v uint64) error {")
	w.Line("\tbuf.Grow(8)")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tb = binary.LittleEndian.AppendUint64(b, uint64(v))")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqU64(a, b uint64) bool { return a == b }")
	w.Blank()
	w.Line("type U64List []uint64")
	w.Line("func GetU64List(buf *bytes.Buffer) ([]uint64, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\ttotalSize := int(count) * 8")
	w.Line("\tif buf.Len() < totalSize { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\tdata := buf.Next(totalSize)")
	w.Line("\tlist := make([]uint64, count)")
	w.Line("\tfor i := range list { list[i] = binary.LittleEndian.Uint64(data[i*8:]) }")
	w.Line("\treturn list, nil")
	w.Line("}")
	w.Line("func SetU64List(buf *bytes.Buffer, v []uint64) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tbuf.Grow(2 + len(v)*8)")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tif len(v) == 0 { return nil }")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tfor _, item := range v { b = binary.LittleEndian.AppendUint64(b, item) }")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqU64List(a, b []uint64) bool { return slices.Equal(a, b) }")
	w.Line("type F32 float32")
	w.Line("func GetF32(buf *bytes.Buffer) (float32, error) {")
	w.Line("\tvar b [4]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn math.Float32frombits(binary.LittleEndian.Uint32(b[:])), nil")
	w.Line("}")
	w.Line("func SetF32(buf *bytes.Buffer, v float32) error {")
	w.Line("\tbuf.Grow(4)")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tb = binary.LittleEndian.AppendUint32(b, math.Float32bits(v))")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqF32(a, b float32) bool { return math.Abs(float64(a-b)) < 1e-6 }")
	w.Blank()
	w.Line("type F32List []float32")
	w.Line("func GetF32List(buf *bytes.Buffer) ([]float32, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\ttotalSize := int(count) * 4")
	w.Line("\tif buf.Len() < totalSize { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\tdata := buf.Next(totalSize)")
	w.Line("\tlist := make([]float32, count)")
	w.Line("\tfor i := range list { list[i] = math.Float32frombits(binary.LittleEndian.Uint32(data[i*4:])) }")
	w.Line("\treturn list, nil")
	w.Line("}")
	w.Line("func SetF32List(buf *bytes.Buffer, v []float32) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tbuf.Grow(2 + len(v)*4)")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tif len(v) == 0 { return nil }")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tfor _, item := range v { b = binary.LittleEndian.AppendUint32(b, math.Float32bits(item)) }")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqF32List(a, b []float32) bool { return slices.Equal(a, b) }")
	w.Line("type F64 float64")
	w.Line("func GetF64(buf *bytes.Buffer) (float64, error) {")
	w.Line("\tvar b [8]byte")
	w.Line("\tif _, err := buf.Read(b[:]); err != nil { return 0, err }")
	w.Line("\treturn math.Float64frombits(binary.LittleEndian.Uint64(b[:])), nil")
	w.Line("}")
	w.Line("func SetF64(buf *bytes.Buffer, v float64) error {")
	w.Line("\tbuf.Grow(8)")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tb = binary.LittleEndian.AppendUint64(b, math.Float64bits(v))")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqF64(a, b float64) bool { return math.Abs(float64(a-b)) < 1e-9 }")
	w.Blank()
	w.Line("type F64List []float64")
	w.Line("func GetF64List(buf *bytes.Buffer) ([]float64, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\ttotalSize := int(count) * 8")
	w.Line("\tif buf.Len() < totalSize { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\tdata := buf.Next(totalSize)")
	w.Line("\tlist := make([]float64, count)")
	w.Line("\tfor i := range list { list[i] = math.Float64frombits(binary.LittleEndian.Uint64(data[i*8:])) }")
	w.Line("\treturn list, nil")
	w.Line("}")
	w.Line("func SetF64List(buf *bytes.Buffer, v []float64) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"list length exceeds uint16 max\") }")
	w.Line("\tbuf.Grow(2 + len(v)*8)")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tif len(v) == 0 { return nil }")
	w.Line("\tb := buf.AvailableBuffer()")
	w.Line("\tfor _, item := range v { b = binary.LittleEndian.AppendUint64(b, math.Float64bits(item)) }")
	w.Line("\t_, err := buf.Write(b)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqF64List(a, b []float64) bool { return slices.Equal(a, b) }")
	w.Blank()
	w.Blank()
	w.Line("// Bin")
	w.Line("type Bin []byte")
	w.Line("func GetBinView(buf *bytes.Buffer) ([]byte, error) {")
	w.Line("\tl, err := GetU32(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\tif uint64(buf.Len()) < uint64(l) { return nil, fmt.Errorf(\"not enough data\") }")
	w.Line("\treturn buf.Next(int(l)), nil")
	w.Line("}")
	w.Line("func GetBin(buf *bytes.Buffer) ([]byte, error) {")
	w.Line("\tres, err := GetBinView(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\treturn bytes.Clone(res), nil")
	w.Line("}")
	w.Line("func SetBin(buf *bytes.Buffer, v []byte) error {")
	w.Line("\tif uint64(len(v)) > uint64(^uint32(0)) { return fmt.Errorf(\"bin length exceeds uint32 max\") }")
	w.Line("\tbuf.Grow(4 + len(v))")
	w.Line("\tif err := SetU32(buf, uint32(len(v))); err != nil { return err }")
	w.Line("\t_, err := buf.Write(v)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqBin(a, b []byte) bool { return bytes.Equal(a, b) }")
	w.Blank()
	w.Line("type BinList [][]byte")
	w.Line("func GetBinList(buf *bytes.Buffer) ([][]byte, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\tlist := make([][]byte, count)")
	w.Line("\tfor i := range list {")
	w.Line("\t\titem, err := GetBinView(buf)")
	w.Line("\t\tif err != nil { return nil, err }")
	w.Line("\t\tlist[i] = bytes.Clone(item)")
	w.Line("\t}")
	w.Line("\treturn list, nil")
	w.Line("}")
	w.Line("func SetBinList(buf *bytes.Buffer, v [][]byte) error {")
	w.Line("\ttotalSize, err := sizeBinList(v)")
	w.Line("\tif err != nil { return err }")
	w.Line("\tbuf.Grow(totalSize)")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tfor _, item := range v {")
	w.Line("\t\tif err := SetU32(buf, uint32(len(item))); err != nil { return err }")
	w.Line("\t\tif len(item) == 0 { continue }")
	w.Line("\t\tif _, err := buf.Write(item); err != nil { return err }")
	w.Line("\t}")
	w.Line("\treturn nil")
	w.Line("}")
	w.Line("func EqBinList(a, b [][]byte) bool { return slices.EqualFunc(a, b, bytes.Equal) }")
	w.Blank()
	w.Line("// Text")
	w.Line("type Text string")
	w.Line("func GetText(buf *bytes.Buffer) (string, error) {")
	w.Line("\tl, err := GetU16(buf)")
	w.Line("\tif err != nil { return \"\", err }")
	w.Line("\tif buf.Len() < int(l) { return \"\", fmt.Errorf(\"not enough data\") }")
	w.Line("\treturn string(buf.Next(int(l))), nil")
	w.Line("}")
	w.Line("func SetText(buf *bytes.Buffer, v string) error {")
	w.Line("\tif len(v) > 65535 { return fmt.Errorf(\"text length exceeds uint16 max\") }")
	w.Line("\tbuf.Grow(2 + len(v))")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\t_, err := buf.WriteString(v)")
	w.Line("\treturn err")
	w.Line("}")
	w.Line("func EqText(a, b string) bool { return a == b }")
	w.Blank()
	w.Line("type TextList []string")
	w.Line("func GetTextList(buf *bytes.Buffer) ([]string, error) {")
	w.Line("\tcount, err := GetU16(buf)")
	w.Line("\tif err != nil { return nil, err }")
	w.Line("\tlist := make([]string, count)")
	w.Line("\tfor i := range list {")
	w.Line("\t\titem, err := GetText(buf)")
	w.Line("\t\tif err != nil { return nil, err }")
	w.Line("\t\tlist[i] = item")
	w.Line("\t}")
	w.Line("\treturn list, nil")
	w.Line("}")
	w.Line("func SetTextList(buf *bytes.Buffer, v []string) error {")
	w.Line("\ttotalSize, err := sizeTextList(v)")
	w.Line("\tif err != nil { return err }")
	w.Line("\tbuf.Grow(totalSize)")
	w.Line("\tif err := SetU16(buf, uint16(len(v))); err != nil { return err }")
	w.Line("\tfor _, item := range v {")
	w.Line("\t\tif err := SetU16(buf, uint16(len(item))); err != nil { return err }")
	w.Line("\t\tif len(item) == 0 { continue }")
	w.Line("\t\tif _, err := buf.WriteString(item); err != nil { return err }")
	w.Line("\t}")
	w.Line("\treturn nil")
	w.Line("}")
	w.Line("func EqTextList(a, b []string) bool { return slices.Equal(a, b) }")
	return w.String()
}
