package internal

import "fmt"

func (g *GoGenerator) renderRPCFile(apis []TplApi) string {
	var w sourceWriter
	w.Line("package sb")
	w.Blank()
	w.Line("import (")
	w.Line("\t\"bytes\"")
	w.Line("\t\"context\"")
	w.Line("\t\"io\"")
	w.Line("\t\"net/http\"")
	w.Line("\t\"strings\"")
	w.Line("\t\"sync\"")
	w.Line("\t\"time\"")
	w.Line("")
	w.Line(")")
	w.Blank()
	w.Line("type RpcErrCode int")
	w.Blank()
	w.Line("const (")
	w.Line("\tRpcOk        RpcErrCode = 200")
	w.Line("\tRpcNoConn    RpcErrCode = 0")
	w.Line("\tRpcTimeout   RpcErrCode = 408")
	w.Line("\tRpcReqErr    RpcErrCode = 400")
	w.Line("\tRpcRespErr   RpcErrCode = 500")
	w.Line("\tRpcNotAuth   RpcErrCode = 401")
	w.Line("\tRpcNotExist  RpcErrCode = 404")
	w.Line("\tdefaultMaxRespBytes int64 = 4 * 1024 * 1024")
	w.Line(")")
	w.Blank()
	w.Line("type Client struct {")
	w.Line("\tBaseURL string")
	w.Line("\tHTTP    *http.Client")
	w.Line("\tTimeout time.Duration")
	w.Line("\tRetries int")
	w.Line("\tEnableRetries bool")
	w.Line("\tMaxRespBytes int64")
	w.Line("\theaders map[string]string")
	w.Line("\theadersMu sync.RWMutex")
	w.Line("}")
	w.Blank()
	w.Line("func NewClient(baseURL string) *Client {")
	w.Line("\tbaseURL = strings.TrimRight(baseURL, \"/\")")
	w.Line("\treturn &Client{")
	w.Line("\t\tBaseURL: baseURL,")
	w.Line("\t\tHTTP:    &http.Client{},")
	w.Line("\t\tTimeout: 5 * time.Second,")
	w.Line("\t\tRetries: 3,")
	w.Line("\t\tMaxRespBytes: defaultMaxRespBytes,")
	w.Line("\t\theaders: make(map[string]string),")
	w.Line("\t}")
	w.Line("}")
	w.Blank()
	w.Line("func SetClientHeader(c *Client, key, value string) {")
	w.Line("\tif c == nil { return }")
	w.Line("\tc.headersMu.Lock()")
	w.Line("\tdefer c.headersMu.Unlock()")
	w.Line("\tif c.headers == nil { c.headers = make(map[string]string) }")
	w.Line("\tc.headers[key] = value")
	w.Line("}")
	w.Line("func GetClientHeader(c *Client, key string) string {")
	w.Line("\tif c == nil { return \"\" }")
	w.Line("\tc.headersMu.RLock()")
	w.Line("\tdefer c.headersMu.RUnlock()")
	w.Line("\treturn c.headers[key]")
	w.Line("}")
	w.Line("func RemoveClientHeader(c *Client, key string) {")
	w.Line("\tif c == nil { return }")
	w.Line("\tc.headersMu.Lock()")
	w.Line("\tdefer c.headersMu.Unlock()")
	w.Line("\tdelete(c.headers, key)")
	w.Line("}")
	w.Blank()
	w.Line("func SetClientAuthorization(c *Client, token string) { SetClientHeader(c, \"Authorization\", \"Bearer \"+token) }")
	w.Line("func GetClientAuthorization(c *Client) string        { return GetClientHeader(c, \"Authorization\") }")
	w.Line("func RemoveClientAuthorization(c *Client)            { RemoveClientHeader(c, \"Authorization\") }")
	w.Line("func IsClientAuthorized(c *Client) bool              { return GetClientAuthorization(c) != \"\" }")
	w.Blank()
	w.Line("func isTimeout(err error) bool {")
	w.Line("\tif err == nil { return false }")
	w.Line("\tif err == context.DeadlineExceeded { return true }")
	w.Line("\tif netErr, ok := err.(interface{ Timeout() bool }); ok && netErr.Timeout() { return true }")
	w.Line("\treturn false")
	w.Line("}")
	w.Blank()
	w.Line("func doClient(c *Client, ctx context.Context, path string, body []byte) ([]byte, RpcErrCode) {")
	w.Line("\tif c == nil { return nil, RpcNoConn }")
	w.Line("\tif ctx == nil { ctx = context.Background() }")
	w.Line("\thttpClient := c.HTTP")
	w.Line("\tif httpClient == nil { httpClient = &http.Client{} }")
	w.Line("\tmaxRetries := 0")
	w.Line("\tif c.EnableRetries {")
	w.Line("\t\tmaxRetries = c.Retries")
	w.Line("\t\tif maxRetries < 0 { maxRetries = 0 }")
	w.Line("\t}")
	w.Line("\tmaxRespBytes := c.MaxRespBytes")
	w.Line("\tif maxRespBytes <= 0 { maxRespBytes = defaultMaxRespBytes }")
	w.Blank()
	w.Line("\tfor i := 0; i <= maxRetries; i++ {")
	w.Line("\t\tif i > 0 {")
	w.Line("\t\t\ttimer := time.NewTimer(time.Duration(i) * time.Second)")
	w.Line("\t\t\tselect {")
	w.Line("\t\t\tcase <-ctx.Done():")
	w.Line("\t\t\t\ttimer.Stop()")
	w.Line("\t\t\t\treturn nil, RpcTimeout")
	w.Line("\t\t\tcase <-timer.C:")
	w.Line("\t\t\t}")
	w.Line("\t\t}")
	w.Line("\t\treqCtx := ctx")
	w.Line("\t\tcancel := func() {}")
	w.Line("\t\tif c.Timeout > 0 {")
	w.Line("\t\t\treqCtx, cancel = context.WithTimeout(ctx, c.Timeout)")
	w.Line("\t\t}")
	w.Line("\t\treq, reqErr := http.NewRequestWithContext(reqCtx, \"POST\", c.BaseURL+path, bytes.NewReader(body))")
	w.Line("\t\tif reqErr != nil {")
	w.Line("\t\t\tcancel()")
	w.Line("\t\t\treturn nil, RpcNoConn")
	w.Line("\t\t}")
	w.Line("\t\tc.headersMu.RLock()")
	w.Line("\t\tfor k, v := range c.headers {")
	w.Line("\t\t\treq.Header.Set(k, v)")
	w.Line("\t\t}")
	w.Line("\t\tc.headersMu.RUnlock()")
	w.Line("\t\tif req.Header.Get(\"Content-Type\") == \"\" {")
	w.Line("\t\t\treq.Header.Set(\"Content-Type\", \"application/octet-stream\")")
	w.Line("\t\t}")
	w.Line("\t\tresp, err := httpClient.Do(req)")
	w.Line("\t\tif err != nil {")
	w.Line("\t\t\tcancel()")
	w.Line("\t\t\tif isTimeout(err) && i < maxRetries { continue }")
	w.Line("\t\t\tif isTimeout(err) { return nil, RpcTimeout }")
	w.Line("\t\t\treturn nil, RpcNoConn")
	w.Line("\t\t}")
	w.Line("\t\tif resp.StatusCode == http.StatusRequestTimeout && i < maxRetries {")
	w.Line("\t\t\tresp.Body.Close()")
	w.Line("\t\t\tcancel()")
	w.Line("\t\t\tcontinue")
	w.Line("\t\t}")
	w.Line("\t\tif resp.StatusCode != http.StatusOK {")
	w.Line("\t\t\tresp.Body.Close()")
	w.Line("\t\t\tcancel()")
	w.Line("\t\t\treturn nil, RpcErrCode(resp.StatusCode)")
	w.Line("\t\t}")
	w.Line("\t\treadLimit := maxRespBytes")
	w.Line("\t\tif readLimit < (1<<63 - 1) { readLimit++ }")
	w.Line("\t\tb, readErr := io.ReadAll(io.LimitReader(resp.Body, readLimit))")
	w.Line("\t\tcloseErr := resp.Body.Close()")
	w.Line("\t\tif readErr != nil || closeErr != nil {")
	w.Line("\t\t\tcancel()")
	w.Line("\t\t\tif isTimeout(readErr) || isTimeout(closeErr) || reqCtx.Err() == context.DeadlineExceeded || ctx.Err() == context.DeadlineExceeded {")
	w.Line("\t\t\t\tif i < maxRetries { continue }")
	w.Line("\t\t\t\treturn nil, RpcTimeout")
	w.Line("\t\t\t}")
	w.Line("\t\t\treturn nil, RpcRespErr")
	w.Line("\t\t}")
	w.Line("\t\tcancel()")
	w.Line("\t\tif readLimit > maxRespBytes && int64(len(b)) > maxRespBytes { return nil, RpcRespErr }")
	w.Line("\t\treturn b, RpcOk")
	w.Line("\t}")
	w.Line("\tif ctx.Err() == context.DeadlineExceeded { return nil, RpcTimeout }")
	w.Line("\treturn nil, RpcNoConn")
	w.Line("}")
	for _, api := range apis {
		callName := PascalCase(api.Name)
		w.Blank()
		w.WriteLineCommentWithHead("// ", "Call"+callName+" ", api.Note)
		w.Linef("func Call%s(c *Client, ctx context.Context%s) (%s) {", callName, g.rpcArgs(api.Args), g.rpcReturn(api.Result))
		w.Line("\tvar buf bytes.Buffer")
		for _, arg := range api.Args {
			g.directWrite(&w, arg.Type, CamelCase(arg.Name), "&buf", fmt.Sprintf("return %s", g.rpcReqErrReturn(api.Result)))
		}
		w.Blank()
		w.Linef("\tbody, status := doClient(c, ctx, \"/%s\", buf.Bytes())", api.Name)
		w.Line("\tif status != RpcOk {")
		w.Linef("\t\treturn %s", g.rpcStatusReturn(api.Result))
		w.Line("\t}")
		if api.Result.Name == "nil" {
			w.Line("\tif len(body) != 0 { return RpcRespErr }")
			w.Line("\treturn status")
			w.Line("}")
			continue
		}
		w.Line("\trespBuf := bytes.NewBuffer(body)")
		g.directRead(&w, api.Result, "result", "respBuf", "return result, RpcRespErr")
		w.Line("\tif respBuf.Len() != 0 { return result, RpcRespErr }")
		w.Line("\treturn result, status")
		w.Line("}")
	}
	return w.String()
}
